// Generated by ReScript, PLEASE EDIT WITH CARE


function make() {
  return {
          str: 100.0,
          dex: 100.0,
          con: 100.0,
          int: 100.0,
          wil: 100.0,
          cha: 100.0
        };
}

function getSpeedMultiplier(attrs) {
  return attrs.dex / 100.0;
}

function getMaxJump(attrs) {
  return 5.0 * attrs.str;
}

function getJumpAcceleration(attrs) {
  return 0.1 * attrs.dex;
}

function getTrajectoryDivisor(attrs, baseIncrement, trajectoryLength) {
  return baseIncrement * attrs.int / trajectoryLength;
}

export {
  make ,
  getSpeedMultiplier ,
  getMaxJump ,
  getJumpAcceleration ,
  getTrajectoryDivisor ,
}
/* No side effect */
