// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PlayerAttributes from "./PlayerAttributes.res.mjs";

var angleJumpLimitEast = Math.PI / 4.0;

var angleJumpLimitWest = 3.0 * Math.PI / 4.0;

var Physics = {
  gravity: 400.0,
  friction: 0.75,
  frictionThreshold: 0.05,
  baseSpeed: 160.0,
  sprintMultiplier: 2.0,
  crouchMultiplier: 0.5,
  angleJumpLimitEast: angleJumpLimitEast,
  angleJumpLimitWest: angleJumpLimitWest,
  displacementDivisor: 100.0
};

function make(startX, startY, groundY) {
  return {
          x: startX,
          y: startY,
          velX: 0.0,
          velY: 0.0,
          onGround: true,
          facing: "Right",
          visualState: "Idle",
          jumpPotential: 0.0,
          isChargingJump: false,
          isSprinting: false,
          attributes: PlayerAttributes.make(),
          groundY: groundY
        };
}

function updateGroundState(state) {
  state.onGround = state.velY === 0.0 && state.y >= state.groundY;
}

function applyFriction(state) {
  if (state.onGround && !state.isChargingJump) {
    state.velX = state.velX * 0.75;
    if (Math.abs(state.velX) < 0.05) {
      state.velX = 0.0;
      return ;
    } else {
      return ;
    }
  }
  
}

function getEffectiveSpeed(state, sprinting, crouching) {
  var baseSpeed = 160.0 * PlayerAttributes.getSpeedMultiplier(state.attributes);
  if (sprinting) {
    return baseSpeed * 2.0;
  } else if (crouching) {
    return baseSpeed * 0.5;
  } else {
    return baseSpeed;
  }
}

function calculateJumpParams(state, mouseX, mouseY) {
  var relX = mouseX - state.x;
  var relY = mouseY - state.y;
  var rawAngle = Math.atan2(relY, relX);
  var angle = rawAngle > angleJumpLimitEast && rawAngle < angleJumpLimitWest ? (
      rawAngle > Math.PI / 2.0 ? angleJumpLimitWest : angleJumpLimitEast
    ) : rawAngle;
  var distance = Math.sqrt(relX * relX + relY * relY);
  var maxJump = PlayerAttributes.getMaxJump(state.attributes);
  var rawMagnitude = state.jumpPotential * (distance / 100.0);
  var magnitude = Math.min(rawMagnitude, maxJump);
  var velX = magnitude * Math.cos(angle);
  var velY = magnitude * Math.sin(angle);
  return {
          angle: angle,
          magnitude: magnitude,
          velX: velX,
          velY: velY
        };
}

function startJumpCharge(state) {
  if (state.onGround && !state.isChargingJump) {
    state.isChargingJump = true;
    state.jumpPotential = 0.0;
    state.velX = 0.0;
    state.visualState = "ChargingJump";
    return ;
  }
  
}

function chargeJump(state, mouseX) {
  if (!state.isChargingJump) {
    return ;
  }
  var maxJump = PlayerAttributes.getMaxJump(state.attributes);
  var jumpAcc = PlayerAttributes.getJumpAcceleration(state.attributes);
  if (state.jumpPotential < maxJump) {
    state.jumpPotential = state.jumpPotential + jumpAcc;
  }
  state.facing = mouseX < state.x ? "Left" : "Right";
}

function releaseJump(state, mouseX, mouseY) {
  if (state.isChargingJump && state.jumpPotential > 0.0) {
    var params = calculateJumpParams(state, mouseX, mouseY);
    state.velX = params.velX;
    state.velY = params.velY;
    state.onGround = false;
    state.visualState = "Jumping";
  }
  state.isChargingJump = false;
  state.jumpPotential = 0.0;
}

function cancelJumpCharge(state) {
  state.isChargingJump = false;
  state.jumpPotential = 0.0;
}

function setHorizontalMovement(state, direction, sprintKeyHeld, crouching) {
  if (state.isChargingJump) {
    return ;
  }
  if (!state.onGround) {
    return ;
  }
  if (direction !== undefined) {
    if (sprintKeyHeld) {
      state.isSprinting = true;
    }
    var effectivelySprinting = state.isSprinting && !crouching;
    var speed = getEffectiveSpeed(state, effectivelySprinting, crouching);
    var sign;
    sign = direction === "Left" ? -1.0 : 1.0;
    state.velX = speed * sign;
    state.facing = direction;
    state.visualState = effectivelySprinting ? "Sprinting" : (
        crouching ? "Crouching" : "Walking"
      );
    return ;
  }
  state.isSprinting = false;
  if (crouching) {
    state.visualState = "Crouching";
  } else {
    state.visualState = "Idle";
  }
}

function updatePhysics(state, deltaTime) {
  if (!state.onGround) {
    state.velY = state.velY + 400.0 * deltaTime;
  }
  applyFriction(state);
  state.x = state.x + state.velX * deltaTime;
  state.y = state.y + state.velY * deltaTime;
  if (state.y >= state.groundY) {
    state.y = state.groundY;
    state.velY = 0.0;
    state.onGround = true;
    if (state.visualState === "Jumping") {
      state.visualState = "Idle";
    }
    
  }
  updateGroundState(state);
}

function getPosition(state) {
  return [
          state.x,
          state.y
        ];
}

export {
  Physics ,
  make ,
  updateGroundState ,
  applyFriction ,
  getEffectiveSpeed ,
  calculateJumpParams ,
  startJumpCharge ,
  chargeJump ,
  releaseJump ,
  cancelJumpCharge ,
  setHorizontalMovement ,
  updatePhysics ,
  getPosition ,
}
/* angleJumpLimitEast Not a pure module */
