// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";

var Colors = {
  body: 3368652,
  bodyDark: 2245768,
  bodyCrouch: 4478361,
  bodyCharge: 13395507,
  skin: 16764074,
  laptop: 3355443,
  laptopScreen: 65280,
  outline: 0
};

var Dimensions = {
  standingWidth: 24.0,
  standingHeight: 40.0,
  headRadius: 12.0,
  headY: -52.0,
  crouchWidth: 28.0,
  crouchHeight: 24.0,
  crouchHeadY: -36.0,
  laptopWidth: 20.0,
  laptopHeight: 12.0,
  laptopY: -25.0,
  laptopScreenPadding: 2.0
};

function drawBody(graphics, state, facing) {
  graphics.clear();
  var match;
  switch (state) {
    case "Sprinting" :
        match = [
          24.0,
          40.0,
          2245768
        ];
        break;
    case "Crouching" :
        match = [
          28.0,
          24.0,
          4478361
        ];
        break;
    case "ChargingJump" :
        match = [
          28.0,
          24.0,
          13395507
        ];
        break;
    default:
      match = [
        24.0,
        40.0,
        3368652
      ];
  }
  var height = match[1];
  var width = match[0];
  graphics.rect(- width / 2.0, - height, width, height).fill({
        color: match[2]
      });
  switch (state) {
    case "Walking" :
        facing === "Left";
        break;
    case "Sprinting" :
        facing === "Left";
        break;
    default:
      
  }
}

function drawHead(graphics, state) {
  graphics.clear();
  var headY;
  switch (state) {
    case "Crouching" :
    case "ChargingJump" :
        headY = -36.0;
        break;
    default:
      headY = -52.0;
  }
  graphics.circle(0.0, headY, 12.0).fill({
        color: 16764074
      });
}

function drawLaptop(graphics, state, facing) {
  graphics.clear();
  switch (state) {
    case "Crouching" :
    case "ChargingJump" :
        return ;
    default:
      var offsetX;
      offsetX = facing === "Left" ? -2.0 : 2.0;
      graphics.rect(- 20.0 / 2.0 + offsetX, -25.0, 20.0, 12.0).fill({
            color: 3355443
          });
      return ;
  }
}

function drawLaptopScreen(graphics, state, facing) {
  graphics.clear();
  switch (state) {
    case "Crouching" :
    case "ChargingJump" :
        return ;
    default:
      var offsetX;
      offsetX = facing === "Left" ? -2.0 : 2.0;
      var y = -25.0 + 2.0;
      var screenWidth = 20.0 - 2.0 * 2.0;
      var screenHeight = 12.0 - 2.0 * 2.0;
      graphics.rect(- screenWidth / 2.0 + offsetX, y, screenWidth, screenHeight).fill({
            color: 65280
          });
      return ;
  }
}

function make() {
  var container = new PixiJs.Container();
  var body = new PixiJs.Graphics();
  var laptop = new PixiJs.Graphics();
  var laptopScreen = new PixiJs.Graphics();
  var head = new PixiJs.Graphics();
  container.addChild(body);
  container.addChild(laptop);
  container.addChild(laptopScreen);
  container.addChild(head);
  drawBody(body, "Idle", "Right");
  drawHead(head, "Idle");
  drawLaptop(laptop, "Idle", "Right");
  drawLaptopScreen(laptopScreen, "Idle", "Right");
  return {
          container: container,
          body: body,
          head: head,
          laptop: laptop,
          laptopScreen: laptopScreen,
          currentState: "Idle",
          currentFacing: "Right"
        };
}

function updateState(gfx, state, facing) {
  if (state !== gfx.currentState || facing !== gfx.currentFacing) {
    gfx.currentState = state;
    gfx.currentFacing = facing;
    drawBody(gfx.body, state, facing);
    drawHead(gfx.head, state);
    drawLaptop(gfx.laptop, state, facing);
    return drawLaptopScreen(gfx.laptopScreen, state, facing);
  }
  
}

function syncPosition(gfx, x, y) {
  gfx.container.x = x;
  gfx.container.y = y;
}

function getContainer(gfx) {
  return gfx.container;
}

export {
  Colors ,
  Dimensions ,
  drawBody ,
  drawHead ,
  drawLaptop ,
  drawLaptopScreen ,
  make ,
  updateState ,
  syncPosition ,
  getContainer ,
}
/* pixi.js Not a pure module */
