// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as PlayerState from "./PlayerState.res.mjs";
import * as PlayerGraphics from "./PlayerGraphics.res.mjs";
import * as TrajectoryPreview from "./TrajectoryPreview.res.mjs";

function make(startX, startY, groundY) {
  var state = PlayerState.make(startX, startY, groundY);
  var graphics = PlayerGraphics.make();
  var trajectory = TrajectoryPreview.make();
  var container = new PixiJs.Container();
  container.addChild(PlayerGraphics.getContainer(graphics));
  PlayerGraphics.syncPosition(graphics, startX, startY);
  return {
          state: state,
          graphics: graphics,
          trajectory: trajectory,
          container: container
        };
}

function getTrajectoryContainer(player) {
  return TrajectoryPreview.getContainer(player.trajectory);
}

function update(player, input, deltaTime) {
  var state = player.state;
  if (input.up && state.onGround) {
    if (!state.isChargingJump) {
      PlayerState.startJumpCharge(state);
    }
    PlayerState.chargeJump(state, input.mouseX);
    var params = PlayerState.calculateJumpParams(state, input.mouseX, input.mouseY);
    TrajectoryPreview.draw(player.trajectory, state.x, state.y - 30.0, params.velX, params.velY, params.magnitude, PlayerState.Physics.gravity, state.groundY, state.attributes);
  } else if (state.isChargingJump) {
    PlayerState.releaseJump(state, input.mouseX, input.mouseY);
    TrajectoryPreview.clear(player.trajectory);
  } else {
    TrajectoryPreview.clear(player.trajectory);
  }
  if (!state.isChargingJump) {
    var direction = input.left && !input.right ? "Left" : (
        input.right && !input.left ? "Right" : undefined
      );
    PlayerState.setHorizontalMovement(state, direction, input.sprint, input.crouch);
  }
  PlayerState.updatePhysics(state, deltaTime);
  TrajectoryPreview.update(player.trajectory, deltaTime);
  PlayerGraphics.updateState(player.graphics, state.visualState, state.facing);
  PlayerGraphics.syncPosition(player.graphics, state.x, state.y);
}

function getPosition(player) {
  return PlayerState.getPosition(player.state);
}

function getX(player) {
  return player.state.x;
}

function getY(player) {
  return player.state.y;
}

function setX(player, x) {
  player.state.x = x;
}

function isOnGround(player) {
  return player.state.onGround;
}

function isChargingJump(player) {
  return player.state.isChargingJump;
}

function getContainer(player) {
  return player.container;
}

function getAttributes(player) {
  return player.state.attributes;
}

function stopMovement(player) {
  player.state.velX = 0.0;
  PlayerState.cancelJumpCharge(player.state);
  TrajectoryPreview.clear(player.trajectory);
}

export {
  make ,
  getTrajectoryContainer ,
  update ,
  getPosition ,
  getX ,
  getY ,
  setX ,
  isOnGround ,
  isChargingJump ,
  getContainer ,
  getAttributes ,
  stopMovement ,
}
/* pixi.js Not a pure module */
