// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Motion from "motion";

function animateAsync(target, props, options) {
  return new Promise((function (resolve, _reject) {
                var controls = Motion.animate(target, props, options);
                controls.then(function () {
                      resolve();
                    });
              }));
}

export {
  animateAsync ,
}
/* motion Not a pure module */
