// Generated by ReScript, PLEASE EDIT WITH CARE


var Point = {};

var Circle = {};

var Rectangle = {};

var ObservablePoint = {};

var Texture = {};

var Container = {};

var Sprite = {
  toContainer: (function (prim) {
      return prim;
    })
};

var Graphics = {
  toContainer: (function (prim) {
      return prim;
    })
};

var $$Text = {
  toContainer: (function (prim) {
      return prim;
    })
};

var TextStyle = {};

var NineSliceSprite = {};

var BlurFilter = {};

var Ticker = {};

var FederatedPointerEvent = {};

var BigPool = {};

var Assets = {};

var Extensions = {};

var ExtensionType = {};

var ResizePlugin = {};

var Renderer = {};

var CanvasStyle = {};

var Application = {};

export {
  Point ,
  Circle ,
  Rectangle ,
  ObservablePoint ,
  Texture ,
  Container ,
  Sprite ,
  Graphics ,
  $$Text ,
  TextStyle ,
  NineSliceSprite ,
  BlurFilter ,
  Ticker ,
  FederatedPointerEvent ,
  BigPool ,
  Assets ,
  Extensions ,
  ExtensionType ,
  ResizePlugin ,
  Renderer ,
  CanvasStyle ,
  Application ,
}
/* No side effect */
