// Generated by ReScript, PLEASE EDIT WITH CARE


function getDeviceColor(deviceType) {
  switch (deviceType) {
    case "Laptop" :
        return 2201331;
    case "Router" :
        return 16750592;
    case "Server" :
        return 10233776;
    case "IotCamera" :
        return 16007990;
    case "Terminal" :
        return 5025616;
    case "PowerStation" :
        return 16771899;
    case "UPS" :
        return 7951688;
    
  }
}

function getSecurityColor(level) {
  switch (level) {
    case "Open" :
        return 65280;
    case "Weak" :
        return 16776960;
    case "Medium" :
        return 16750592;
    case "Strong" :
        return 16711680;
    
  }
}

export {
  getDeviceColor ,
  getSecurityColor ,
}
/* No side effect */
