// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GetEngine from "../../GetEngine.res.mjs";
import * as $$Navigation from "../../../engine/navigation/Navigation.res.mjs";
import * as LocationBase from "./LocationBase.res.mjs";
import * as LocationData from "../LocationData.res.mjs";
import * as WorldMapScreen from "../WorldMapScreen.res.mjs";
import * as LocationRegistry from "../LocationRegistry.res.mjs";

var assetBundles = ["main"];

var loc = LocationData.getLocationById("city");

var locationData = loc !== undefined ? loc : ({
      id: "city",
      name: "Downtown Office",
      description: "Error loading location",
      devicePositions: [],
      environment: "city",
      worldWidth: 1800.0,
      backgroundColor: 4868682
    });

function make() {
  return LocationBase.makeLocationScreen(locationData, (function () {
                var engine = GetEngine.get();
                if (engine !== undefined) {
                  $$Navigation.showScreen(engine.navigation, WorldMapScreen.constructor);
                  return ;
                }
                
              }));
}

var constructor_assetBundles = assetBundles;

var constructor = {
  make: make,
  assetBundles: constructor_assetBundles
};

LocationRegistry.register("city", constructor);

export {
  assetBundles ,
  locationData ,
  make ,
  constructor ,
}
/* loc Not a pure module */
