// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GetEngine from "../../GetEngine.res.mjs";
import * as $$Navigation from "../../../engine/navigation/Navigation.res.mjs";
import * as LocationBase from "./LocationBase.res.mjs";
import * as LocationData from "../LocationData.res.mjs";
import * as WorldMapScreen from "../WorldMapScreen.res.mjs";
import * as LocationRegistry from "../LocationRegistry.res.mjs";

var assetBundles = ["main"];

var loc = LocationData.getLocationById("rural-isp");

var locationData = loc !== undefined ? loc : ({
      id: "rural-isp",
      name: "Rural ISP",
      description: "Error loading location",
      devicePositions: [],
      environment: "datacenter",
      worldWidth: 2000.0,
      backgroundColor: 1723694
    });

function make() {
  return LocationBase.makeLocationScreen(locationData, (function () {
                var engine = GetEngine.get();
                if (engine !== undefined) {
                  $$Navigation.showScreen(engine.navigation, WorldMapScreen.constructor);
                  return ;
                }
                
              }));
}

var constructor_assetBundles = assetBundles;

var constructor = {
  make: make,
  assetBundles: constructor_assetBundles
};

LocationRegistry.register("rural-isp", constructor);

export {
  assetBundles ,
  locationData ,
  make ,
  constructor ,
}
/* loc Not a pure module */
