// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Audio from "./audio/Audio.res.mjs";
import * as Resize from "./resize/Resize.res.mjs";
import * as PixiJs from "pixi.js";
import * as $$Navigation from "./navigation/Navigation.res.mjs";
import * as Sound from "@pixi/sound";
import * as GetResolution from "./utils/GetResolution.res.mjs";
import ManifestJson from "../manifest.json";

var manifest = ManifestJson;

function make() {
  return {
          app: new PixiJs.Application(),
          audio: $$Audio.makeAudioManager(),
          navigation: $$Navigation.make(),
          resizeOptions: {
            minWidth: 768.0,
            minHeight: 1024.0,
            letterbox: true
          },
          visibilityHandler: undefined
        };
}

function createVisibilityHandler(engine) {
  return function (param) {
    if (document.hidden) {
      Sound.sound.pauseAll();
      return $$Navigation.blur(engine.navigation);
    } else {
      Sound.sound.resumeAll();
      return $$Navigation.focus(engine.navigation);
    }
  };
}

var setCanvasSize = (function(canvas, width, height) {
    canvas.style.width = width + "px";
    canvas.style.height = height + "px";
    window.scrollTo(0, 0);
  });

function handleResize(engine) {
  var width = window.innerWidth;
  var height = window.innerHeight;
  Resize.resize(width, height, engine.resizeOptions.minWidth, engine.resizeOptions.minHeight, engine.resizeOptions.letterbox);
  var renderer = engine.app.renderer;
  renderer.resize(width, height);
  $$Navigation.resize(engine.navigation, width, height);
}

async function init(engine, background, resizeOptions) {
  engine.resizeOptions = resizeOptions;
  var resolution = GetResolution.getResolution();
  await engine.app.init({
        background: background,
        resizeTo: window,
        resolution: resolution,
        autoDensity: true
      });
  var stage = engine.app.stage;
  stage.eventMode = "static";
  stage.interactiveChildren = true;
  var container = document.getElementById("pixi-container");
  if (!(container == null)) {
    container.appendChild(engine.app.canvas);
  }
  $$Navigation.init(engine.navigation, engine.app);
  var handler = createVisibilityHandler(engine);
  engine.visibilityHandler = handler;
  document.addEventListener("visibilitychange", handler);
  var setupResizeListener = (function(handler) {
      window.addEventListener("resize", handler);
    });
  setupResizeListener(function () {
        handleResize(engine);
      });
  handleResize(engine);
  await PixiJs.Assets.init({
        manifest: manifest,
        basePath: "assets"
      });
  await PixiJs.Assets.loadBundle("preload");
  var allBundles = manifest.bundles.map(function (item) {
        return item.name;
      });
  PixiJs.Assets.backgroundLoadBundle(allBundles);
}

function destroy(engine) {
  var handler = engine.visibilityHandler;
  if (handler !== undefined) {
    document.removeEventListener("visibilitychange", handler);
  }
  engine.app.destroy(true);
}

export {
  manifest ,
  make ,
  createVisibilityHandler ,
  setCanvasSize ,
  handleResize ,
  init ,
  destroy ,
}
/* manifest Not a pure module */
