// Generated by ReScript, PLEASE EDIT WITH CARE


function getDistance(bxOpt, byOpt, ax, ay) {
  var bx = bxOpt !== undefined ? bxOpt : 0.0;
  var by = byOpt !== undefined ? byOpt : 0.0;
  var dx = bx - ax;
  var dy = by - ay;
  return Math.sqrt(dx * dx + dy * dy);
}

function lerp(a, b, t) {
  return (1.0 - t) * a + t * b;
}

function clamp(minOpt, maxOpt, v) {
  var min = minOpt !== undefined ? minOpt : 0.0;
  var max = maxOpt !== undefined ? maxOpt : 1.0;
  var match = min > max ? [
      max,
      min
    ] : [
      min,
      max
    ];
  var minVal = match[0];
  if (v < minVal) {
    return minVal;
  }
  var maxVal = match[1];
  if (v > maxVal) {
    return maxVal;
  } else {
    return v;
  }
}

export {
  getDistance ,
  lerp ,
  clamp ,
}
/* No side effect */
