// Generated by ReScript, PLEASE EDIT WITH CARE


var lxor = ((a, b) => a ^ b);

var lor = ((a, b) => a | b);

var land = ((a, b) => a & b);

var lsl = ((a, b) => a << b);

var lsr = ((a, b) => a >>> b);

var xmur3 = (function(str) {
    var h = 1779033703 ^ str.length;
    for (var i = 0; i < str.length; i++) {
      h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
      h = (h << 13) | (h >>> 19);
    }
    return function() {
      h = Math.imul(h ^ (h >>> 16), 2246822507);
      h = Math.imul(h ^ (h >>> 13), 3266489909);
      return (h ^= h >>> 16) >>> 0;
    };
  });

var mulberry32 = (function(seed) {
    var a = seed;
    return function() {
      a = (a + 0x6d2b79f5) | 0;
      var t = a;
      t = Math.imul(t ^ (t >>> 15), t | 1);
      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  });

var hashCharset = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

function seeded(seed) {
  return mulberry32(xmur3(seed)());
}

function color(randomFnOpt, param) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  var r = Math.floor(255.0 * randomFn());
  var g = Math.floor(255.0 * randomFn());
  var b = Math.floor(255.0 * randomFn());
  return lor(lor(lsl(r, 16), lsl(g, 8)), b);
}

function range(randomFnOpt, min, max) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  var a = Math.min(min, max);
  var b = Math.max(min, max);
  return a + (b - a) * randomFn();
}

function item(randomFnOpt, arr) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  var len = arr.length;
  if (len === 0) {
    return ;
  } else {
    return arr[Math.floor(randomFn() * len)];
  }
}

function bool(weightOpt, randomFnOpt, param) {
  var weight = weightOpt !== undefined ? weightOpt : 0.5;
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  return randomFn() < weight;
}

var shuffle = (function(randomFn, arr) {
    var rng = randomFn || Math.random;
    var currentIndex = arr.length;
    while (currentIndex !== 0) {
      var randomIndex = Math.floor(rng() * currentIndex);
      currentIndex--;
      var temp = arr[currentIndex];
      arr[currentIndex] = arr[randomIndex];
      arr[randomIndex] = temp;
    }
    return arr;
  });

function hash(randomFnOpt, charsetOpt, length) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  var charset = charsetOpt !== undefined ? charsetOpt : hashCharset;
  var charsetLength = charset.length;
  var result = "";
  for(var _for = 0; _for < length; ++_for){
    var idx = Math.floor(randomFn() * charsetLength);
    result = result + charset.charAt(idx);
  }
  return result;
}

function $$float(randomFnOpt, min, max) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  return randomFn() * (max - min) + min;
}

function $$int(randomFnOpt, min, max) {
  var randomFn = randomFnOpt !== undefined ? randomFnOpt : (function (prim) {
        return Math.random();
      });
  return Math.floor(randomFn() * ((max - min | 0) + 1 | 0)) + min | 0;
}

export {
  lxor ,
  lor ,
  land ,
  lsl ,
  lsr ,
  xmur3 ,
  mulberry32 ,
  hashCharset ,
  seeded ,
  color ,
  range ,
  item ,
  bool ,
  shuffle ,
  hash ,
  $$float ,
  $$int ,
}
/* No side effect */
