// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Random from "../../../engine/utils/Random.res.mjs";
import * as PixiJs from "pixi.js";

function make(title, width, height, titleBarColorOpt, backgroundColorOpt, param) {
  var titleBarColor = titleBarColorOpt !== undefined ? titleBarColorOpt : 30932;
  var backgroundColor = backgroundColorOpt !== undefined ? backgroundColorOpt : 1710618;
  var container = new PixiJs.Container();
  container.eventMode = "static";
  container.interactiveChildren = true;
  container.zIndex = 10;
  container.x = 100.0 + Random.$$float(undefined, 0.0, 100.0);
  container.y = 100.0 + Random.$$float(undefined, 0.0, 50.0);
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, height).fill({
          color: backgroundColor
        }).stroke({
        width: 2,
        color: 0
      });
  container.addChild(bg);
  var titleBar = new PixiJs.Graphics();
  titleBar.rect(0.0, 0.0, width, 30.0).fill({
        color: titleBarColor
      });
  titleBar.eventMode = "static";
  titleBar.interactiveChildren = true;
  titleBar.cursor = "grab";
  container.addChild(titleBar);
  var titleText = new PixiJs.Text({
        text: title,
        style: {
          fontSize: 12,
          fill: 16777215,
          fontFamily: "monospace"
        }
      });
  titleText.x = 10.0;
  titleText.y = 8.0;
  titleBar.addChild(titleText);
  var closeBtn = new PixiJs.Graphics();
  closeBtn.x = width - 30.0;
  closeBtn.y = 5.0;
  closeBtn.rect(0.0, 0.0, 25.0, 20.0).fill({
        color: 16711680
      });
  closeBtn.eventMode = "static";
  closeBtn.cursor = "pointer";
  var closeX = new PixiJs.Text({
        text: "X",
        style: {
          fontSize: 14,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  closeX.x = 8.0;
  closeX.y = 2.0;
  closeBtn.addChild(closeX);
  titleBar.addChild(closeBtn);
  var content = new PixiJs.Container();
  content.eventMode = "static";
  content.interactiveChildren = true;
  content.y = 30.0;
  container.addChild(content);
  var windowState = {
    container: container,
    titleBar: titleBar,
    content: content,
    closeBtn: closeBtn,
    isDragging: false,
    dragOffset: {
      x: 0.0,
      y: 0.0
    },
    onCloseCallback: undefined
  };
  titleBar.on("pointerdown", (function (e) {
          windowState.isDragging = true;
          titleBar.cursor = "grabbing";
          windowState.dragOffset = {
            x: e.global.x - container.x,
            y: e.global.y - container.y
          };
          var parent = container.parent;
          if (!(parent == null)) {
            parent.on("pointermove", (function (e) {
                    if (windowState.isDragging) {
                      container.x = e.global.x - windowState.dragOffset.x;
                      container.y = e.global.y - windowState.dragOffset.y;
                      return ;
                    }
                    
                  }));
            parent.on("pointerup", (function (param) {
                    windowState.isDragging = false;
                    titleBar.cursor = "grab";
                  }));
            parent.on("pointerupoutside", (function (param) {
                    windowState.isDragging = false;
                    titleBar.cursor = "grab";
                  }));
            return ;
          }
          
        }));
  closeBtn.on("pointerdown", (function (param) {
          console.log("Close button clicked!");
          var callback = windowState.onCloseCallback;
          if (callback !== undefined) {
            callback();
          }
          container.destroy();
        }));
  return windowState;
}

function setOnClose(win, callback) {
  win.onCloseCallback = callback;
}

function getContent(win) {
  return win.content;
}

function close(win) {
  win.container.destroy();
}

export {
  make ,
  setOnClose ,
  getContent ,
  close ,
}
/* pixi.js Not a pure module */
