// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Motion from "motion";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Sound from "@pixi/sound";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make() {
  return {
          currentAlias: undefined,
          current: undefined,
          volume: 1.0
        };
}

async function play(bgm, alias, volumeOpt, param) {
  var volume = volumeOpt !== undefined ? volumeOpt : 1.0;
  if (Caml_obj.equal(bgm.currentAlias, alias)) {
    return ;
  }
  var current = bgm.current;
  if (current !== undefined) {
    var current$1 = Caml_option.valFromOption(current);
    Motion.animate(current$1, {
          volume: 0.0
        }, {
          duration: 1.0,
          ease: "linear"
        });
    await new Promise((function (resolve, param) {
            setTimeout((function () {
                    current$1.stop();
                    resolve();
                  }), 1000);
          }));
  }
  var newSound = Sound.sound.find(alias);
  bgm.current = Caml_option.some(newSound);
  bgm.currentAlias = alias;
  newSound.play({
        loop: true,
        volume: volume
      });
  newSound.volume = 0.0;
  Motion.animate(newSound, {
        volume: bgm.volume
      }, {
        duration: 1.0,
        ease: "linear"
      });
}

function getVolume(bgm) {
  return bgm.volume;
}

function setVolume(bgm, v) {
  bgm.volume = v;
  var sound = bgm.current;
  if (sound !== undefined) {
    Caml_option.valFromOption(sound).volume = v;
    return ;
  }
  
}

var BGM = {
  make: make,
  play: play,
  getVolume: getVolume,
  setVolume: setVolume
};

function make$1() {
  return {
          volume: 1.0
        };
}

function play$1(sfx, alias, volumeOpt, param) {
  var volume = volumeOpt !== undefined ? volumeOpt : 1.0;
  var finalVolume = sfx.volume * volume;
  Sound.sound.play(alias, {
        volume: finalVolume
      });
}

function getVolume$1(sfx) {
  return sfx.volume;
}

function setVolume$1(sfx, v) {
  sfx.volume = v;
}

var SFX = {
  make: make$1,
  play: play$1,
  getVolume: getVolume$1,
  setVolume: setVolume$1
};

function makeAudioManager() {
  return {
          bgm: {
            currentAlias: undefined,
            current: undefined,
            volume: 1.0
          },
          sfx: {
            volume: 1.0
          }
        };
}

function getMasterVolume() {
  return Sound.sound.volumeAll;
}

var setVolumeAllRaw = (function(sound, volume) {
    sound.volumeAll = volume;
  });

function setMasterVolume(volume) {
  setVolumeAllRaw(Sound.sound, volume);
  if (volume === 0.0) {
    Sound.sound.muteAll();
  } else {
    Sound.sound.unmuteAll();
  }
}

export {
  BGM ,
  SFX ,
  makeAudioManager ,
  getMasterVolume ,
  setVolumeAllRaw ,
  setMasterVolume ,
}
/* motion Not a pure module */
