// Generated by ReScript, PLEASE EDIT WITH CARE


var instance = {
  contents: undefined
};

function get() {
  return instance.contents;
}

function set(engine) {
  instance.contents = engine;
}

export {
  instance ,
  get ,
  set ,
}
/* No side effect */
