// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Audio from "../../engine/audio/Audio.res.mjs";
import * as Label from "./Label.res.mjs";
import * as Ui from "@pixi/ui";
import * as GetEngine from "../GetEngine.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var defaultOptions = {
  text: "",
  width: 301.0,
  height: 112.0,
  fontSize: 28
};

function playSfx(alias) {
  var engine = GetEngine.get();
  if (engine !== undefined) {
    return $$Audio.SFX.play(engine.audio.sfx, alias, undefined, undefined);
  }
  
}

function make(optionsOpt, param) {
  var options = optionsOpt !== undefined ? optionsOpt : defaultOptions;
  var text = Core__Option.getOr(options.text, "");
  var width = Core__Option.getOr(options.width, 301.0);
  var height = Core__Option.getOr(options.height, 112.0);
  var fontSize = Core__Option.getOr(options.fontSize, 28);
  var label = Label.make(text, {
        align: "center",
        fill: 4868682,
        fontSize: fontSize
      }, undefined);
  var button = new Ui.FancyButton({
        defaultView: "button.png",
        nineSliceSprite: [
          38,
          50,
          38,
          50
        ],
        anchor: 0.5,
        text: label,
        textOffset: {
          x: 0,
          y: -13
        },
        defaultTextAnchor: 0.5,
        animations: {
          hover: {
            props: {
              scale: {
                x: 1.03,
                y: 1.03
              },
              y: 0
            },
            duration: 100
          },
          pressed: {
            props: {
              scale: {
                x: 0.97,
                y: 0.97
              },
              y: 10
            },
            duration: 100
          }
        }
      });
  button.width = width;
  button.height = height;
  button.onDown.connect(function () {
        playSfx("main/sounds/sfx-press.wav");
      });
  button.onHover.connect(function () {
        playSfx("main/sounds/sfx-hover.wav");
      });
  return button;
}

export {
  defaultOptions ,
  playSfx ,
  make ,
}
/* Audio Not a pure module */
