// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var defaultStyle = {
  fontFamily: "Arial Rounded MT Bold",
  align: "center"
};

function make(text, styleOpt, param) {
  var style = styleOpt !== undefined ? styleOpt : defaultStyle;
  var label = new PixiJs.Text({
        text: text,
        style: {
          fontFamily: Core__Option.getOr(style.fontFamily, Core__Option.getOr("Arial Rounded MT Bold", "Arial Rounded MT Bold")),
          align: Core__Option.getOr(style.align, Core__Option.getOr("center", "center")),
          fill: Core__Option.getOr(style.fill, 16777215),
          fontSize: Core__Option.getOr(style.fontSize, 24),
          fontWeight: Core__Option.getOr(style.fontWeight, "normal")
        }
      });
  label.anchor.set(0.5, 0.5);
  return label;
}

export {
  defaultStyle ,
  make ,
}
/* pixi.js Not a pure module */
