// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var defaultOptions = {
  color: 16777215,
  width: 350.0,
  height: 600.0,
  shadow: true,
  shadowColor: 10526880,
  shadowOffset: 22.0
};

function make(optionsOpt, param) {
  var options = optionsOpt !== undefined ? optionsOpt : defaultOptions;
  var container = new PixiJs.Container();
  var color = Core__Option.getOr(options.color, 16777215);
  var width = Core__Option.getOr(options.width, 350.0);
  var height = Core__Option.getOr(options.height, 600.0);
  var showShadow = Core__Option.getOr(options.shadow, true);
  var shadowColor = Core__Option.getOr(options.shadowColor, 10526880);
  var shadowOffset = Core__Option.getOr(options.shadowOffset, 22.0);
  var image = new PixiJs.NineSliceSprite({
        texture: PixiJs.Texture.from("rounded-rectangle.png"),
        leftWidth: 34,
        topHeight: 34,
        rightWidth: 34,
        bottomHeight: 34,
        width: width,
        height: height,
        tint: color
      });
  image.x = - width * 0.5;
  image.y = - height * 0.5;
  container.addChild(image);
  var shadow;
  if (showShadow) {
    var shadowSprite = new PixiJs.NineSliceSprite({
          texture: PixiJs.Texture.from("rounded-rectangle.png"),
          leftWidth: 34,
          topHeight: 34,
          rightWidth: 34,
          bottomHeight: 34,
          width: width,
          height: height,
          tint: shadowColor
        });
    shadowSprite.x = - width * 0.5;
    shadowSprite.y = - height * 0.5 + shadowOffset;
    container.addChildAt(shadowSprite, 0);
    shadow = Caml_option.some(shadowSprite);
  } else {
    shadow = undefined;
  }
  return {
          container: container,
          image: image,
          shadow: shadow,
          boxWidth: width,
          boxHeight: height
        };
}

export {
  defaultOptions ,
  make ,
}
/* pixi.js Not a pure module */
