// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Label from "./Label.res.mjs";
import * as PixiJs from "pixi.js";
import * as Ui from "@pixi/ui";

function make(label, minOpt, maxOpt, valueOpt, param) {
  var min = minOpt !== undefined ? minOpt : -0.1;
  var max = maxOpt !== undefined ? maxOpt : 100.0;
  var value = valueOpt !== undefined ? valueOpt : 100.0;
  var bg = new PixiJs.Graphics();
  bg.roundRect(0.0, 0.0, 280.0, 20.0, 20.0).fill({
            color: 15471969
          }).roundRect(4.0, 4.0, 280.0 - 4.0 * 2.0, 20.0 - 4.0 * 2.0, 20.0).fill({
        color: 16777215
      });
  var fill = new PixiJs.Graphics();
  fill.roundRect(0.0, 0.0, 280.0, 20.0, 20.0).fill({
            color: 15471969
          }).roundRect(4.0, 4.0, 280.0 - 4.0 * 2.0, 20.0 - 4.0 * 2.0, 20.0).fill({
        color: 15688340
      });
  var sliderHandle = new PixiJs.Graphics();
  sliderHandle.circle(0.0, 0.0, 14.0 + 4.0).fill({
        color: 15471969
      });
  var slider = new Ui.Slider({
        bg: bg,
        fill: fill,
        slider: sliderHandle,
        min: min,
        max: max
      });
  slider.value = value;
  var messageLabel = Label.make(label, {
        align: "left",
        fill: 4868682,
        fontSize: 18
      }, undefined);
  messageLabel.anchor.x = 0.0;
  messageLabel.x = 10.0;
  messageLabel.y = -18.0;
  slider.addChild(messageLabel);
  return {
          slider: slider,
          messageLabel: messageLabel
        };
}

export {
  make ,
}
/* Label Not a pure module */
