// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pixi from "../../bindings/Pixi.res.mjs";
import * as Motion from "../../bindings/Motion.res.mjs";
import * as PixiJs from "pixi.js";

var assetBundles = ["preload"];

function make() {
  var container = new PixiJs.Container();
  var progressBg = new PixiJs.Graphics();
  progressBg.rect(-100.0, -10.0, 200.0, 20.0);
  progressBg.fill({
        color: 3355443
      });
  container.addChild(progressBg);
  var progressFill = new PixiJs.Graphics();
  progressFill.rect(-100.0, -10.0, 200.0, 20.0);
  progressFill.fill({
        color: 15471969
      });
  Pixi.Graphics.toContainer(progressFill).scale.set(0.0, 1.0);
  container.addChild(progressFill);
  var pixiLogo = new PixiJs.Sprite({
        texture: PixiJs.Texture.from("logo.svg"),
        anchor: 0.5,
        scale: 0.2
      });
  container.addChild(Pixi.Sprite.toContainer(pixiLogo));
  return {
          container: container,
          prepare: undefined,
          show: (async function () {
              container.alpha = 1.0;
            }),
          hide: (async function () {
              return await Motion.animateAsync(container, {
                          alpha: 0.0
                        }, {
                          duration: 0.3,
                          ease: "linear",
                          delay: 1.0
                        });
            }),
          pause: undefined,
          resume: undefined,
          reset: undefined,
          update: undefined,
          resize: (function (width, height) {
              pixiLogo.position.set(width * 0.5, height * 0.5);
              progressBg.x = width * 0.5;
              progressBg.y = height * 0.5 + 80.0;
              progressFill.x = width * 0.5;
              progressFill.y = height * 0.5 + 80.0;
            }),
          blur: undefined,
          focus: undefined,
          onLoad: (function (progress) {
              Pixi.Graphics.toContainer(progressFill).scale.x = progress / 100.0;
            })
        };
}

var constructor_assetBundles = assetBundles;

var constructor = {
  make: make,
  assetBundles: constructor_assetBundles
};

export {
  assetBundles ,
  make ,
  constructor ,
}
/* Motion Not a pure module */
