// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GetEngine from "../GetEngine.res.mjs";
import * as $$Navigation from "../../engine/navigation/Navigation.res.mjs";

var registry = {};

function register(locationId, constructor) {
  registry[locationId] = constructor;
}

function get(locationId) {
  return registry[locationId];
}

function navigateTo(locationId) {
  var engine = GetEngine.get();
  if (engine === undefined) {
    return ;
  }
  var constructor = registry[locationId];
  if (constructor !== undefined) {
    $$Navigation.showScreen(engine.navigation, constructor);
    return ;
  }
  
}

export {
  registry ,
  register ,
  get ,
  navigateTo ,
}
/* Navigation Not a pure module */
