// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pixi from "../../bindings/Pixi.res.mjs";
import * as Button from "../ui/Button.res.mjs";
import * as Motion from "../../bindings/Motion.res.mjs";
import * as Player from "../player/Player.res.mjs";
import * as PixiJs from "pixi.js";
import * as GetEngine from "../GetEngine.res.mjs";
import * as PowerView from "../popups/PowerView.res.mjs";
import * as CameraFeed from "../devices/CameraFeed.res.mjs";
import * as $$Navigation from "../../engine/navigation/Navigation.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as DeviceTypes from "../devices/types/DeviceTypes.res.mjs";
import * as LaptopState from "../devices/LaptopState.res.mjs";
import * as DeviceWindow from "../devices/common/DeviceWindow.res.mjs";
import * as PowerManager from "../devices/PowerManager.res.mjs";
import * as RouterDevice from "../devices/RouterDevice.res.mjs";
import * as DesktopDevice from "../devices/DesktopDevice.res.mjs";
import * as NetworkDesktop from "../popups/NetworkDesktop.res.mjs";
import * as NetworkManager from "../devices/NetworkManager.res.mjs";
import * as WorldMapScreen from "./WorldMapScreen.res.mjs";
import * as NetworkTransfer from "../devices/NetworkTransfer.res.mjs";
import * as GlobalNetworkManager from "../devices/GlobalNetworkManager.res.mjs";

function make(device, x) {
  var info = device.getInfo();
  var container = new PixiJs.Container();
  container.eventMode = "static";
  container.cursor = "pointer";
  container.x = x;
  container.y = 500.0;
  var deviceGraphic = new PixiJs.Graphics();
  var deviceColor = DeviceTypes.getDeviceColor(info.deviceType);
  var match = info.deviceType;
  switch (match) {
    case "Laptop" :
        deviceGraphic.rect(-35.0, -20.0, 70.0, 20.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-30.0, 0.0, 8.0, 20.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(22.0, 0.0, 8.0, 20.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-25.0, -55.0, 50.0, 35.0).fill({
              color: 3355443
            });
        deviceGraphic.rect(-22.0, -52.0, 44.0, 29.0).fill({
              color: deviceColor
            });
        deviceGraphic.rect(-28.0, -20.0, 56.0, 8.0).fill({
              color: 4473924
            });
        break;
    case "Router" :
        deviceGraphic.rect(-30.0, -40.0, 60.0, 8.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-5.0, -40.0, 10.0, 40.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-25.0, -60.0, 50.0, 20.0).fill({
              color: deviceColor
            });
        deviceGraphic.rect(-18.0, -85.0, 4.0, 25.0).fill({
              color: 3355443
            });
        deviceGraphic.rect(14.0, -85.0, 4.0, 25.0).fill({
              color: 3355443
            });
        for(var i = 0; i <= 3; ++i){
          deviceGraphic.circle(-15.0 + i * 10.0, -50.0, 3.0).fill({
                color: 65280
              });
        }
        break;
    case "Server" :
        deviceGraphic.rect(-25.0, -120.0, 50.0, 120.0).fill({
              color: 3355443
            });
        for(var i$1 = 0; i$1 <= 5; ++i$1){
          var yPos = -115.0 + i$1 * 18.0;
          deviceGraphic.rect(-22.0, yPos, 44.0, 16.0).fill({
                color: deviceColor
              });
          deviceGraphic.circle(17.0, yPos + 8.0, 3.0).fill({
                color: 65280
              });
        }
        break;
    case "IotCamera" :
        deviceGraphic.rect(-4.0, -100.0, 8.0, 100.0).fill({
              color: 6710886
            });
        deviceGraphic.rect(-15.0, -110.0, 30.0, 10.0).fill({
              color: 4473924
            });
        deviceGraphic.circle(0.0, -125.0, 18.0).fill({
              color: deviceColor
            });
        deviceGraphic.circle(0.0, -125.0, 10.0).fill({
              color: 2236962
            });
        break;
    case "Terminal" :
        deviceGraphic.rect(-40.0, -30.0, 80.0, 30.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-35.0, 0.0, 8.0, 25.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(27.0, 0.0, 8.0, 25.0).fill({
              color: 4863784
            });
        deviceGraphic.rect(-30.0, -80.0, 60.0, 50.0).fill({
              color: 3355443
            });
        deviceGraphic.rect(-27.0, -77.0, 54.0, 44.0).fill({
              color: 0
            });
        var termText = new PixiJs.Text({
              text: ">_",
              style: {
                fill: 65280,
                fontSize: 16
              }
            });
        termText.x = -20.0;
        termText.y = -70.0;
        deviceGraphic.addChild(termText);
        deviceGraphic.rect(-8.0, -30.0, 16.0, 10.0).fill({
              color: 3355443
            });
        deviceGraphic.rect(-25.0, -28.0, 50.0, 8.0).fill({
              color: 2236962
            });
        break;
    case "PowerStation" :
        deviceGraphic.rect(-40.0, -150.0, 80.0, 150.0).fill({
              color: 2763306
            });
        deviceGraphic.rect(-35.0, -145.0, 70.0, 140.0).fill({
                color: 3355443
              }).stroke({
              width: 2,
              color: 4473924
            });
        for(var i$2 = 0; i$2 <= 5; ++i$2){
          var yPos$1 = -140.0 + i$2 * 12.0;
          deviceGraphic.rect(-30.0, yPos$1, 60.0, 8.0).fill({
                color: 1710618
              });
        }
        deviceGraphic.rect(-25.0, -60.0, 50.0, 30.0).fill({
                color: 0
              }).stroke({
              width: 1,
              color: deviceColor
            });
        for(var i$3 = 0; i$3 <= 4; ++i$3){
          deviceGraphic.rect(-20.0 + i$3 * 10.0, -55.0, 6.0, 20.0).fill({
                color: deviceColor
              });
        }
        deviceGraphic.rect(-40.0, -20.0, 80.0, 20.0).fill({
              color: 16763904
            });
        for(var i$4 = 0; i$4 <= 7; ++i$4){
          deviceGraphic.rect(-40.0 + i$4 * 20.0, -20.0, 10.0, 20.0).fill({
                color: 2236962
              });
        }
        deviceGraphic.circle(0.0, -130.0, 8.0).fill({
              color: 65280
            });
        break;
    case "UPS" :
        deviceGraphic.rect(-30.0, -80.0, 60.0, 80.0).fill({
                color: 4013373
              }).stroke({
              width: 2,
              color: 5263440
            });
        deviceGraphic.rect(-25.0, -75.0, 50.0, 70.0).fill({
              color: deviceColor
            });
        deviceGraphic.rect(-20.0, -70.0, 40.0, 20.0).fill({
                color: 1718810
              }).stroke({
              width: 1,
              color: 65280
            });
        deviceGraphic.rect(-15.0, -65.0, 20.0, 10.0).fill({
              color: 65280
            });
        deviceGraphic.rect(5.0, -63.0, 3.0, 6.0).fill({
              color: 65280
            });
        deviceGraphic.circle(-10.0, -40.0, 4.0).fill({
              color: 65280
            });
        deviceGraphic.circle(0.0, -40.0, 4.0).fill({
              color: 65280
            });
        deviceGraphic.circle(10.0, -40.0, 4.0).fill({
              color: 65280
            });
        for(var i$5 = 0; i$5 <= 2; ++i$5){
          deviceGraphic.rect(-18.0 + i$5 * 14.0, -25.0, 10.0, 12.0).fill({
                color: 2236962
              });
        }
        break;
    
  }
  container.addChild(deviceGraphic);
  var match$1 = info.deviceType;
  if (match$1 === "IotCamera") {
    var cameraIndicator = new PixiJs.Graphics();
    cameraIndicator.circle(0.0, -125.0, 5.0).fill({
          color: 26316
        });
    container.addChild(cameraIndicator);
    CameraFeed.registerCameraPosition(info.ipAddress, x, 300.0);
    CameraFeed.registerMotionCallback(info.ipAddress, (function (status) {
            cameraIndicator.clear();
            var indicatorColor = status !== undefined ? (
                status ? 16737792 : 26316
              ) : 6710886;
            cameraIndicator.circle(0.0, -125.0, 5.0).fill({
                  color: indicatorColor
                });
          }));
  }
  var nameText = new PixiJs.Text({
        text: info.name,
        style: {
          fontSize: 12,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  nameText.anchor.set(0.5, 0.0);
  nameText.x = 0.0;
  nameText.y = 10.0;
  container.addChild(nameText);
  var match$2 = info.deviceType;
  var powerIndicator;
  switch (match$2) {
    case "PowerStation" :
    case "UPS" :
        powerIndicator = undefined;
        break;
    default:
      var indicatorContainer = new PixiJs.Container();
      indicatorContainer.x = -40.0;
      indicatorContainer.y = -60.0;
      indicatorContainer.eventMode = "static";
      indicatorContainer.cursor = "pointer";
      indicatorContainer.hitArea = new PixiJs.Circle(0.0, 0.0, 10.0);
      var indicator = new PixiJs.Graphics();
      var hasPower = PowerManager.deviceHasPower(info.ipAddress);
      indicator.circle(0.0, 0.0, 8.0).fill({
            color: hasPower ? 65280 : 16711680
          });
      indicatorContainer.addChild(indicator);
      var ip = info.ipAddress;
      indicatorContainer.on("pointertap", (function (e) {
              console.log("Power indicator clicked for " + ip);
              e.stopPropagation();
              var feedData = CameraFeed.getFeedData();
              var isNearby;
              if (feedData !== undefined) {
                var match = feedData.getHackerPosition();
                var distance = Math.abs(match[0] - x);
                isNearby = distance <= 100.0;
              } else {
                isNearby = false;
              }
              if (isNearby) {
                var isShutdown = PowerManager.isDeviceShutdown(ip);
                if (isShutdown) {
                  if (PowerManager.deviceHasPower(ip)) {
                    PowerManager.bootDevice(ip);
                    console.log("Booting device " + ip);
                  } else {
                    console.log("Cannot boot " + ip + " - no power available");
                  }
                } else {
                  PowerManager.manualShutdownDevice(ip);
                  console.log("Manually shutting down device " + ip);
                }
                return ;
              }
              console.log("Too far from " + ip + " - must be within " + (100.0).toString() + " units");
            }));
      container.addChild(indicatorContainer);
      powerIndicator = Caml_option.some(indicator);
  }
  return {
          container: container,
          device: device,
          x: x,
          y: 500.0,
          powerIndicator: powerIndicator,
          ipAddress: info.ipAddress
        };
}

function updatePowerIndicator(wd) {
  var indicator = wd.powerIndicator;
  if (indicator === undefined) {
    return ;
  }
  var indicator$1 = Caml_option.valFromOption(indicator);
  var hasPower = PowerManager.deviceHasPower(wd.ipAddress);
  var isShutdown = PowerManager.isDeviceShutdown(wd.ipAddress);
  indicator$1.clear();
  var color = isShutdown ? 4473924 : (
      hasPower ? 65280 : 16711680
    );
  indicator$1.circle(0.0, 0.0, 8.0).fill({
        color: color
      });
}

var WorldDeviceIcon = {
  make: make,
  updatePowerIndicator: updatePowerIndicator
};

var globalKeyState = {
  up: false,
  down: false,
  left: false,
  right: false,
  sprint: false,
  crouch: false
};

var globalMouseState = {
  x: 0.0,
  y: 0.0
};

var setupKeyboard = (function(updateCallback) {
    // Remove old handlers if they exist (for hot-reload support)
    if (window.__worldKeydownHandler) {
      window.removeEventListener('keydown', window.__worldKeydownHandler);
      window.removeEventListener('keyup', window.__worldKeyupHandler);
      window.removeEventListener('blur', window.__worldBlurHandler);
    }
    console.log('Setting up keyboard handlers (fresh)');

    const keyState = { up: false, down: false, left: false, right: false, sprint: false, crouch: false };

    window.__worldKeydownHandler = (e) => {
      if (e.key === 'w' || e.key === 'W' || e.key === 'ArrowUp' || e.key === ' ') { keyState.up = true; }
      if (e.key === 's' || e.key === 'S' || e.key === 'ArrowDown') { keyState.down = true; }
      if (e.key === 'a' || e.key === 'A' || e.key === 'ArrowLeft') { keyState.left = true; }
      if (e.key === 'd' || e.key === 'D' || e.key === 'ArrowRight') { keyState.right = true; }
      if (e.key === 'Control' || e.key === 'c' || e.key === 'C') { keyState.crouch = true; }
      // Use shiftKey property - always reflects current shift state
      keyState.sprint = e.shiftKey;
      updateCallback(keyState);
    };

    window.__worldKeyupHandler = (e) => {
      if (e.key === 'w' || e.key === 'W' || e.key === 'ArrowUp' || e.key === ' ') { keyState.up = false; }
      if (e.key === 's' || e.key === 'S' || e.key === 'ArrowDown') { keyState.down = false; }
      if (e.key === 'a' || e.key === 'A' || e.key === 'ArrowLeft') { keyState.left = false; }
      if (e.key === 'd' || e.key === 'D' || e.key === 'ArrowRight') { keyState.right = false; }
      if (e.key === 'Control' || e.key === 'c' || e.key === 'C') { keyState.crouch = false; }
      // Use shiftKey property - always reflects current shift state
      keyState.sprint = e.shiftKey;
      updateCallback(keyState);
    };

    // Also handle blur to reset all keys when window loses focus
    window.__worldBlurHandler = () => {
      keyState.up = false;
      keyState.down = false;
      keyState.left = false;
      keyState.right = false;
      keyState.sprint = false;
      keyState.crouch = false;
      updateCallback(keyState);
    };

    window.addEventListener('keydown', window.__worldKeydownHandler);
    window.addEventListener('keyup', window.__worldKeyupHandler);
    window.addEventListener('blur', window.__worldBlurHandler);
  });

var globalMouseScreenPos = {
  screenX: 0.0,
  screenY: 0.0
};

var setupMouseTrackingOnStage = (function(container, updateCallback) {
    console.log('Setting up mouse tracking on PixiJS container');

    // Container should already have eventMode='static' and interactiveChildren=true set
    // We just need to listen for pointer events on the stage/app level
    const mousePos = { screenX: 0, screenY: 0 };

    // Listen on globalThis to capture all pointer moves regardless of hitArea
    container.on('globalpointermove', (e) => {
      // e.global contains properly converted stage coordinates
      mousePos.screenX = e.global.x;
      mousePos.screenY = e.global.y;
      updateCallback(mousePos);
    });
  });

var buttonAnimations = {
  hover: {
    props: {
      scale: {
        x: 1.1,
        y: 1.1
      }
    },
    duration: 100
  },
  pressed: {
    props: {
      scale: {
        x: 0.9,
        y: 0.9
      }
    },
    duration: 100
  }
};

function buildLocationScreen($$location) {
  var container = new PixiJs.Container();
  container.eventMode = "static";
  container.interactiveChildren = true;
  var worldContainer = new PixiJs.Container();
  container.addChild(worldContainer);
  var exitBtn = new PixiJs.Graphics();
  exitBtn.rect(0.0, 0.0, 120.0, 40.0).fill({
          color: 11141120
        }).stroke({
        width: 2,
        color: 0
      });
  exitBtn.eventMode = "static";
  exitBtn.cursor = "pointer";
  exitBtn.x = 20.0;
  exitBtn.y = 20.0;
  container.addChild(exitBtn);
  var exitText = new PixiJs.Text({
        text: "Exit to Map",
        style: {
          fontFamily: "Arial",
          fontSize: 14,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  exitText.anchor.set(0.5, 0.5);
  exitText.x = 60.0;
  exitText.y = 20.0;
  container.addChild(exitText);
  exitBtn.on("pointertap", (function (param) {
          var engine = GetEngine.get();
          if (engine !== undefined) {
            $$Navigation.showScreen(engine.navigation, WorldMapScreen.constructor);
            return ;
          }
          
        }));
  var escKeyHandler = {
    contents: undefined
  };
  var networkManager = GlobalNetworkManager.get();
  DesktopDevice.setGlobalNetworkInterfaceSetter(function (state) {
        var ni = NetworkManager.createNetworkInterfaceFor(networkManager, state.ipAddress);
        LaptopState.setNetworkInterface(state, ni);
      });
  DesktopDevice.setGlobalStateGetter(function (ipAddress) {
        return NetworkManager.getDeviceState(networkManager, ipAddress);
      });
  RouterDevice.setGlobalNetworkManager({
        getConnectedDevices: (function () {
            return NetworkManager.getConnectedDevices(networkManager);
          }),
        getConfiguredDns: (function () {
            return NetworkManager.getConfiguredDns(networkManager);
          }),
        setConfiguredDns: (function (dnsIp) {
            NetworkManager.setConfiguredDns(networkManager, dnsIp);
          })
      });
  var player = Player.make(150.0, 500.0, 500.0);
  CameraFeed.setFeedData({
        worldContainer: worldContainer,
        getHackerPosition: (function () {
            return Player.getPosition(player);
          })
      });
  var sky = new PixiJs.Graphics();
  sky.rect(0.0, 0.0, $$location.worldWidth, 500.0 + 200.0).fill({
        color: $$location.backgroundColor
      });
  worldContainer.addChild(sky);
  var buildings = new PixiJs.Graphics();
  var buildingCount = $$location.worldWidth / 200.0 | 0;
  for(var i = 0; i <= buildingCount; ++i){
    var bx = i * 200.0;
    var bh = 100.0 + Math.random() * 150.0;
    buildings.rect(bx, 500.0 - bh, 150.0, bh).fill({
          color: 2434368
        });
    for(var wy = 0 ,wy_finish = bh / 30.0 | 0; wy <= wy_finish; ++wy){
      for(var wx = 0; wx <= 3; ++wx){
        var windowLit = Math.random() > 0.5;
        buildings.rect(bx + 15.0 + wx * 35.0, 500.0 - bh + 15.0 + wy * 30.0, 20.0, 15.0).fill({
              color: windowLit ? 16777130 : 1710640
            });
      }
    }
  }
  worldContainer.addChild(buildings);
  var ground = new PixiJs.Graphics();
  ground.rect(0.0, 500.0, $$location.worldWidth, 200.0).fill({
        color: 2968126
      });
  ground.rect(0.0, 500.0, $$location.worldWidth, 4.0).fill({
        color: 4880990
      });
  worldContainer.addChild(ground);
  var devicePositions = $$location.devicePositions;
  var devices = Core__Array.filterMap(devicePositions, (function (param) {
          var device = NetworkManager.getDevice(networkManager, param[0]);
          if (device !== undefined) {
            return make(device, param[1]);
          }
          
        }));
  devices.forEach(function (wd) {
        worldContainer.addChild(wd.container);
      });
  worldContainer.addChild(Player.getTrajectoryContainer(player));
  worldContainer.addChild(Player.getContainer(player));
  var debugButton = Button.make({
        text: "Network View (Debug)",
        width: 180.0,
        height: 40.0
      }, undefined);
  debugButton.onPress.connect(function () {
        console.log("Network View button pressed!");
        var engine = GetEngine.get();
        if (engine !== undefined) {
          $$Navigation.presentPopup(engine.navigation, NetworkDesktop.constructor);
          return ;
        }
        
      });
  debugButton.onDown.connect(function () {
        console.log("Network View button down!");
      });
  container.addChild(debugButton);
  var powerButton = Button.make({
        text: "Power View (Debug)",
        width: 180.0,
        height: 40.0
      }, undefined);
  powerButton.onPress.connect(function () {
        var engine = GetEngine.get();
        if (engine !== undefined) {
          $$Navigation.presentPopup(engine.navigation, PowerView.constructor);
          return ;
        }
        
      });
  container.addChild(powerButton);
  var dimOverlay = new PixiJs.Graphics();
  dimOverlay.eventMode = "none";
  Pixi.Graphics.toContainer(dimOverlay).visible = false;
  container.addChild(dimOverlay);
  var instructions = new PixiJs.Text({
        text: "A/D to move | Shift to sprint | C/Ctrl to crouch | W/Space + Mouse to aim jump | Click nearby device",
        style: {
          fontSize: 14,
          fill: 8947848
        }
      });
  container.addChild(instructions);
  var screenState = {
    container: container,
    worldContainer: worldContainer,
    dimOverlay: dimOverlay,
    player: player,
    devices: devices,
    networkManager: networkManager,
    debugButton: debugButton,
    powerButton: powerButton,
    paused: false,
    currentDeviceWindow: undefined,
    controlsDisabled: false
  };
  var closeDeviceWindow = function () {
    var win = screenState.currentDeviceWindow;
    if (win !== undefined) {
      container.removeChild(win.container);
      win.container.destroy();
      screenState.currentDeviceWindow = undefined;
      screenState.controlsDisabled = false;
      Pixi.Graphics.toContainer(dimOverlay).visible = false;
      return ;
    }
    
  };
  setupKeyboard(function (ks) {
        globalKeyState.up = ks.up;
        globalKeyState.down = ks.down;
        globalKeyState.left = ks.left;
        globalKeyState.right = ks.right;
        globalKeyState.sprint = ks.sprint;
        globalKeyState.crouch = ks.crouch;
      });
  setupMouseTrackingOnStage(container, (function (ms) {
          globalMouseScreenPos.screenX = ms.screenX;
          globalMouseScreenPos.screenY = ms.screenY;
        }));
  var setupEscKey = (function() {
      if (!window.__escKeySetup) {
        window.__escKeySetup = true;
        window.addEventListener('keydown', (e) => {
          if (e.key === 'Escape') {
            if (window.__closeDeviceWindow) window.__closeDeviceWindow();
          }
        });
      }
      window.__closeDeviceWindow = function() {};
    });
  setupEscKey();
  var setCloseCallback = (function(callback) {
      window.__closeDeviceWindow = callback;
    });
  setCloseCallback(closeDeviceWindow);
  devices.forEach(function (wd) {
        wd.container.on("pointertap", (function (param) {
                var distance = Math.abs(Player.getX(player) - wd.x);
                if (distance > 100.0) {
                  return ;
                }
                var info = wd.device.getInfo();
                var match = info.deviceType;
                var canOpen;
                switch (match) {
                  case "PowerStation" :
                  case "UPS" :
                      canOpen = true;
                      break;
                  default:
                    canOpen = PowerManager.isDeviceOperational(wd.ipAddress);
                }
                if (canOpen) {
                  closeDeviceWindow();
                  var $$window = wd.device.openGUI();
                  DeviceWindow.setOnClose($$window, (function () {
                          screenState.currentDeviceWindow = undefined;
                          screenState.controlsDisabled = false;
                          Pixi.Graphics.toContainer(dimOverlay).visible = false;
                        }));
                  container.addChild($$window.container);
                  $$window.container.x = 100.0;
                  $$window.container.y = 50.0;
                  screenState.currentDeviceWindow = $$window;
                  screenState.controlsDisabled = true;
                  Pixi.Graphics.toContainer(dimOverlay).visible = true;
                  return ;
                }
                console.log("Device " + wd.ipAddress + " is shutdown - no power");
              }));
      });
  var screenWidth = {
    contents: 800.0
  };
  var screenHeight = {
    contents: 600.0
  };
  return {
          container: container,
          prepare: (function () {
              
            }),
          show: (async function () {
              container.alpha = 0.0;
              var handler = (function() {
          return function(e) {
            if (e.key === 'Escape') {
              e.preventDefault();
              const engine = require('../GetEngine.res.mjs');
              const worldMap = require('./WorldMapScreen.res.mjs');
              const nav = require('../../engine/navigation/Navigation.res.mjs');
              const eng = engine.get();
              if (eng) {
                nav.showScreen(eng.navigation, worldMap.constructor);
              }
            }
          }
        })();
              escKeyHandler.contents = Caml_option.some(handler);
              ((window.addEventListener('keydown', handler)));
              return await Motion.animateAsync(container, {
                          alpha: 1.0
                        }, {
                          duration: 0.5,
                          ease: "easeOut"
                        });
            }),
          hide: (async function () {
              var handler = escKeyHandler.contents;
              if (handler !== undefined) {
                ((window.removeEventListener('keydown', handler)));
              }
              return await Motion.animateAsync(container, {
                          alpha: 0.0
                        }, {
                          duration: 0.3
                        });
            }),
          pause: (async function () {
              screenState.paused = true;
            }),
          resume: (async function () {
              screenState.paused = false;
            }),
          reset: (function () {
              var handler = escKeyHandler.contents;
              if (handler !== undefined) {
                return (window.removeEventListener('keydown', handler));
              }
              
            }),
          update: (function (ticker) {
              var dt = ticker.deltaTime / 60.0;
              NetworkTransfer.updateTransfers(dt);
              var worldContainerX = worldContainer.x;
              var mouseWorldX = globalMouseScreenPos.screenX - worldContainerX;
              var mouseWorldY = globalMouseScreenPos.screenY;
              var input = !screenState.paused && !screenState.controlsDisabled ? ({
                    left: globalKeyState.left,
                    right: globalKeyState.right,
                    up: globalKeyState.up,
                    crouch: globalKeyState.crouch || globalKeyState.down,
                    sprint: globalKeyState.sprint,
                    mouseX: mouseWorldX,
                    mouseY: mouseWorldY
                  }) : ({
                    left: false,
                    right: false,
                    up: false,
                    crouch: false,
                    sprint: false,
                    mouseX: mouseWorldX,
                    mouseY: mouseWorldY
                  });
              if (screenState.paused) {
                return ;
              }
              Player.update(player, input, dt);
              var playerX = Player.getX(player);
              if (playerX < 50.0) {
                Player.setX(player, 50.0);
              }
              if (playerX > $$location.worldWidth - 50.0) {
                Player.setX(player, $$location.worldWidth - 50.0);
              }
              var targetCameraX = - Player.getX(player) + screenWidth.contents / 2.0;
              var minCameraX = - $$location.worldWidth + screenWidth.contents;
              var clampedCameraX = Math.max(minCameraX, Math.min(0.0, targetCameraX));
              worldContainer.x = clampedCameraX;
              CameraFeed.updateAllCameraMotion();
              PowerManager.updateUPSBatteries(dt);
              var deviceIps = devices.map(function (wd) {
                    return wd.ipAddress;
                  });
              PowerManager.updateAllDevicePowerStates(deviceIps);
              devices.forEach(updatePowerIndicator);
            }),
          resize: (function (width, height) {
              screenWidth.contents = width;
              screenHeight.contents = height;
              debugButton.x = width - 100.0;
              debugButton.y = 30.0;
              powerButton.x = width - 100.0;
              powerButton.y = 80.0;
              dimOverlay.clear();
              dimOverlay.rect(0.0, 0.0, width, height).fill({
                    color: 0,
                    alpha: 0.6
                  });
              instructions.x = 20.0;
              instructions.y = height - 30.0;
            }),
          blur: undefined,
          focus: undefined,
          onLoad: undefined
        };
}

var groundY = 500.0;

var interactionDistance = 100.0;

export {
  groundY ,
  interactionDistance ,
  WorldDeviceIcon ,
  globalKeyState ,
  globalMouseState ,
  setupKeyboard ,
  globalMouseScreenPos ,
  setupMouseTrackingOnStage ,
  buttonAnimations ,
  buildLocationScreen ,
}
/* Button Not a pure module */
