// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Label from "../ui/Label.res.mjs";
import * as Button from "../ui/Button.res.mjs";
import * as Motion from "../../bindings/Motion.res.mjs";
import * as Motion$1 from "motion";
import * as PixiJs from "pixi.js";
import * as GetEngine from "../GetEngine.res.mjs";
import * as $$Navigation from "../../engine/navigation/Navigation.res.mjs";
import * as RoundedBox from "../ui/RoundedBox.res.mjs";

function make() {
  var container = new PixiJs.Container();
  var bg = new PixiJs.Sprite({
        texture: PixiJs.Texture.WHITE,
        anchor: 0.0
      });
  bg.tint = 0;
  bg.interactive = true;
  container.addChild(bg);
  var panel = new PixiJs.Container();
  container.addChild(panel);
  var panelBase = RoundedBox.make({
        height: 300.0
      }, undefined);
  panel.addChild(panelBase.container);
  var title = Label.make("Paused", {
        fill: 15471969,
        fontSize: 50
      }, undefined);
  title.y = -80.0;
  panel.addChild(title);
  var doneButton = Button.make({
        text: "Resume"
      }, undefined);
  doneButton.y = 70.0;
  doneButton.onPress.connect(function () {
        var engine = GetEngine.get();
        if (engine !== undefined) {
          $$Navigation.dismissPopup(engine.navigation);
          return ;
        }
        
      });
  panel.addChild(doneButton);
  return {
          container: container,
          prepare: undefined,
          show: (async function () {
              var engine = GetEngine.get();
              if (engine !== undefined) {
                var screen = engine.navigation.currentScreen;
                if (screen !== undefined) {
                  var blurFilter = new PixiJs.BlurFilter({
                        strength: 5
                      });
                  screen.container.filters = [blurFilter];
                }
                
              }
              bg.alpha = 0.0;
              panel.pivot.y = -400.0;
              Motion$1.animate(bg, {
                    alpha: 0.8
                  }, {
                    duration: 0.2,
                    ease: "linear"
                  });
              return await Motion.animateAsync(panel.pivot, {
                          y: 0.0
                        }, {
                          duration: 0.3,
                          ease: "backOut"
                        });
            }),
          hide: (async function () {
              var engine = GetEngine.get();
              if (engine !== undefined) {
                var screen = engine.navigation.currentScreen;
                if (screen !== undefined) {
                  screen.container.filters = [];
                }
                
              }
              Motion$1.animate(bg, {
                    alpha: 0.0
                  }, {
                    duration: 0.2,
                    ease: "linear"
                  });
              return await Motion.animateAsync(panel.pivot, {
                          y: -500.0
                        }, {
                          duration: 0.3,
                          ease: "backIn"
                        });
            }),
          pause: undefined,
          resume: undefined,
          reset: undefined,
          update: undefined,
          resize: (function (width, height) {
              bg.width = width;
              bg.height = height;
              panel.x = width * 0.5;
              panel.y = height * 0.5;
            }),
          blur: undefined,
          focus: undefined,
          onLoad: undefined
        };
}

var constructor = {
  make: make,
  assetBundles: undefined
};

export {
  make ,
  constructor ,
}
/* Label Not a pure module */
