// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make() {
  return {
          app: undefined,
          container: new PixiJs.Container(),
          width: 0.0,
          height: 0.0,
          background: undefined,
          currentScreen: undefined,
          currentPopup: undefined
        };
}

function init(nav, app) {
  nav.app = Caml_option.some(app);
}

async function addAndShowScreen(nav, screen) {
  var app = nav.app;
  if (app === undefined) {
    return ;
  }
  var app$1 = Caml_option.valFromOption(app);
  if (nav.container.parent == null) {
    app$1.stage.addChild(nav.container);
  }
  nav.container.addChild(screen.container);
  var fn = screen.prepare;
  if (fn !== undefined) {
    fn();
  }
  var fn$1 = screen.resize;
  if (fn$1 !== undefined) {
    fn$1(nav.width, nav.height);
  }
  var updateFn = screen.update;
  if (updateFn !== undefined) {
    app$1.ticker.add(updateFn, screen);
  }
  var showFn = screen.show;
  if (showFn !== undefined) {
    screen.container.interactiveChildren = false;
    await showFn();
    screen.container.interactiveChildren = true;
    return ;
  }
  
}

async function hideAndRemoveScreen(nav, screen) {
  screen.container.interactiveChildren = false;
  var hideFn = screen.hide;
  if (hideFn !== undefined) {
    await hideFn();
  }
  var app = nav.app;
  if (app !== undefined) {
    var updateFn = screen.update;
    if (updateFn !== undefined) {
      Caml_option.valFromOption(app).ticker.remove(updateFn, screen);
    }
    
  }
  if ((screen.container.parent == null) === false) {
    nav.container.removeChild(screen.container);
  }
  var fn = screen.reset;
  if (fn !== undefined) {
    return fn();
  }
  
}

function setBackground(nav, ctor) {
  var screen = ctor.make();
  nav.background = screen;
  addAndShowScreen(nav, screen);
}

async function showScreen(nav, ctor) {
  var screen = nav.currentScreen;
  if (screen !== undefined) {
    screen.container.interactiveChildren = false;
  }
  var bundles = ctor.assetBundles;
  if (bundles !== undefined) {
    await PixiJs.Assets.loadBundle(bundles, (function (progress) {
            var screen = nav.currentScreen;
            if (screen === undefined) {
              return ;
            }
            var fn = screen.onLoad;
            if (fn !== undefined) {
              return fn(progress * 100.0);
            }
            
          }));
  }
  var screen$1 = nav.currentScreen;
  if (screen$1 !== undefined) {
    var fn = screen$1.onLoad;
    if (fn !== undefined) {
      fn(100.0);
    }
    
  }
  var screen$2 = nav.currentScreen;
  if (screen$2 !== undefined) {
    await hideAndRemoveScreen(nav, screen$2);
  }
  var newScreen = ctor.make();
  nav.currentScreen = newScreen;
  return await addAndShowScreen(nav, newScreen);
}

function resize(nav, width, height) {
  nav.width = width;
  nav.height = height;
  var screen = nav.currentScreen;
  if (screen !== undefined) {
    var fn = screen.resize;
    if (fn !== undefined) {
      fn(width, height);
    }
    
  }
  var popup = nav.currentPopup;
  if (popup !== undefined) {
    var fn$1 = popup.resize;
    if (fn$1 !== undefined) {
      fn$1(width, height);
    }
    
  }
  var bg = nav.background;
  if (bg === undefined) {
    return ;
  }
  var fn$2 = bg.resize;
  if (fn$2 !== undefined) {
    return fn$2(width, height);
  }
  
}

async function presentPopup(nav, ctor) {
  var screen = nav.currentScreen;
  if (screen !== undefined) {
    screen.container.interactiveChildren = false;
    var fn = screen.pause;
    if (fn !== undefined) {
      await fn();
    }
    
  }
  var popup = nav.currentPopup;
  if (popup !== undefined) {
    await hideAndRemoveScreen(nav, popup);
  }
  var newPopup = ctor.make();
  nav.currentPopup = newPopup;
  return await addAndShowScreen(nav, newPopup);
}

async function dismissPopup(nav) {
  var popup = nav.currentPopup;
  if (popup === undefined) {
    return ;
  }
  nav.currentPopup = undefined;
  await hideAndRemoveScreen(nav, popup);
  var screen = nav.currentScreen;
  if (screen === undefined) {
    return ;
  }
  screen.container.interactiveChildren = true;
  var fn = screen.resume;
  if (fn !== undefined) {
    fn();
    return ;
  }
  
}

function blur(nav) {
  var screen = nav.currentScreen;
  if (screen !== undefined) {
    var fn = screen.blur;
    if (fn !== undefined) {
      fn();
    }
    
  }
  var popup = nav.currentPopup;
  if (popup !== undefined) {
    var fn$1 = popup.blur;
    if (fn$1 !== undefined) {
      fn$1();
    }
    
  }
  var bg = nav.background;
  if (bg === undefined) {
    return ;
  }
  var fn$2 = bg.blur;
  if (fn$2 !== undefined) {
    return fn$2();
  }
  
}

function focus(nav) {
  var screen = nav.currentScreen;
  if (screen !== undefined) {
    var fn = screen.focus;
    if (fn !== undefined) {
      fn();
    }
    
  }
  var popup = nav.currentPopup;
  if (popup !== undefined) {
    var fn$1 = popup.focus;
    if (fn$1 !== undefined) {
      fn$1();
    }
    
  }
  var bg = nav.background;
  if (bg === undefined) {
    return ;
  }
  var fn$2 = bg.focus;
  if (fn$2 !== undefined) {
    return fn$2();
  }
  
}

export {
  make ,
  init ,
  addAndShowScreen ,
  hideAndRemoveScreen ,
  setBackground ,
  showScreen ,
  resize ,
  presentPopup ,
  dismissPopup ,
  blur ,
  focus ,
}
/* pixi.js Not a pure module */
