// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Audio from "../../engine/audio/Audio.res.mjs";
import * as $$Storage from "../../engine/utils/Storage.res.mjs";
import * as GetEngine from "../GetEngine.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var keyVolumeMaster = "volume-master";

var keyVolumeBgm = "volume-bgm";

var keyVolumeSfx = "volume-sfx";

function getMasterVolume() {
  return Core__Option.getOr($$Storage.getNumber(keyVolumeMaster), 0.5);
}

function getBgmVolume() {
  return Core__Option.getOr($$Storage.getNumber(keyVolumeBgm), 1.0);
}

function getSfxVolume() {
  return Core__Option.getOr($$Storage.getNumber(keyVolumeSfx), 1.0);
}

function init() {
  var engine = GetEngine.get();
  if (engine !== undefined) {
    $$Audio.setMasterVolume(getMasterVolume());
    $$Audio.BGM.setVolume(engine.audio.bgm, getBgmVolume());
    return $$Audio.SFX.setVolume(engine.audio.sfx, getSfxVolume());
  }
  
}

function setMasterVolume(value) {
  var match = GetEngine.get();
  if (match !== undefined) {
    $$Audio.setMasterVolume(value);
    return $$Storage.setNumber(keyVolumeMaster, value);
  }
  
}

function setBgmVolume(value) {
  var engine = GetEngine.get();
  if (engine !== undefined) {
    $$Audio.BGM.setVolume(engine.audio.bgm, value);
    return $$Storage.setNumber(keyVolumeBgm, value);
  }
  
}

function setSfxVolume(value) {
  var engine = GetEngine.get();
  if (engine !== undefined) {
    $$Audio.SFX.setVolume(engine.audio.sfx, value);
    return $$Storage.setNumber(keyVolumeSfx, value);
  }
  
}

export {
  keyVolumeMaster ,
  keyVolumeBgm ,
  keyVolumeSfx ,
  getMasterVolume ,
  getBgmVolume ,
  getSfxVolume ,
  init ,
  setMasterVolume ,
  setBgmVolume ,
  setSfxVolume ,
}
/* Audio Not a pure module */
