// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logo from "./Logo.res.mjs";
import * as Pixi from "../../../bindings/Pixi.res.mjs";
import * as Random from "../../../engine/utils/Random.res.mjs";
import * as Motion from "motion";
import * as WaitFor from "../../../engine/utils/WaitFor.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function make() {
  return {
          screen: undefined,
          mainContainer: undefined,
          allLogoArray: [],
          activeLogoArray: [],
          yMin: -400.0,
          yMax: 400.0,
          xMin: -400.0,
          xMax: 400.0
        };
}

function add(bouncer) {
  var container = bouncer.mainContainer;
  if (container === undefined) {
    return ;
  }
  var width = Random.$$float(undefined, bouncer.xMin, bouncer.xMax);
  var height = Random.$$float(undefined, bouncer.yMin, bouncer.yMax);
  var logo = Logo.make();
  logo.sprite.alpha = 0.0;
  logo.sprite.position.set(width, height);
  Motion.animate(logo.sprite, {
        alpha: 1.0
      }, {
        duration: 1.0
      });
  Caml_option.valFromOption(container).addChild(logo.sprite);
  bouncer.allLogoArray = bouncer.allLogoArray.concat([logo]);
  bouncer.activeLogoArray = bouncer.activeLogoArray.concat([logo]);
}

function remove(bouncer) {
  var len = bouncer.activeLogoArray.length;
  if (len <= 0) {
    return ;
  }
  var logo = bouncer.activeLogoArray[len - 1 | 0];
  if (logo !== undefined) {
    bouncer.activeLogoArray = bouncer.activeLogoArray.slice(0, len - 1 | 0);
    Motion.animate(logo.sprite, {
            alpha: 0.0
          }, {
            duration: 1.0
          }).then(function () {
          var container = bouncer.mainContainer;
          if (container === undefined) {
            return ;
          }
          Caml_option.valFromOption(container).removeChild(Pixi.Sprite.toContainer(logo.sprite));
          var idx = bouncer.allLogoArray.findIndex(function (l) {
                return l === logo;
              });
          if (idx >= 0) {
            bouncer.allLogoArray = bouncer.allLogoArray.filter(function (param, i) {
                  return i !== idx;
                });
            return ;
          }
          
        });
    return ;
  }
  
}

function setDirection(logo) {
  var sprite = logo.sprite;
  var speed = logo.speed;
  var match = logo.direction;
  switch (match) {
    case "NE" :
        sprite.x = sprite.x + speed;
        sprite.y = sprite.y - speed;
        return ;
    case "NW" :
        sprite.x = sprite.x - speed;
        sprite.y = sprite.y - speed;
        return ;
    case "SE" :
        sprite.x = sprite.x + speed;
        sprite.y = sprite.y + speed;
        return ;
    case "SW" :
        sprite.x = sprite.x - speed;
        sprite.y = sprite.y + speed;
        return ;
    
  }
}

function setLimits(bouncer, logo) {
  var pos = logo.sprite.position;
  var x = pos.x;
  var y = pos.y;
  var topBound = Logo.top(logo);
  var bottomBound = Logo.bottom(logo);
  var leftBound = Logo.left(logo);
  var rightBound = Logo.right(logo);
  var direction = logo.direction;
  if (y + topBound <= bouncer.yMin) {
    var match = direction;
    var tmp;
    tmp = match === "NW" ? "SW" : "SE";
    direction = tmp;
  }
  if (y + bottomBound >= bouncer.yMax) {
    var match$1 = direction;
    var tmp$1;
    tmp$1 = match$1 === "SE" ? "NE" : "NW";
    direction = tmp$1;
  }
  if (x + leftBound <= bouncer.xMin) {
    var match$2 = direction;
    var tmp$2;
    tmp$2 = match$2 === "NW" ? "NE" : "SE";
    direction = tmp$2;
  }
  if (x + rightBound >= bouncer.xMax) {
    var match$3 = direction;
    var tmp$3;
    tmp$3 = match$3 === "NE" ? "NW" : "SW";
    direction = tmp$3;
  }
  logo.direction = direction;
}

function update(bouncer) {
  bouncer.allLogoArray.forEach(function (logo) {
        setDirection(logo);
        setLimits(bouncer, logo);
      });
}

async function show(bouncer, mainContainer) {
  bouncer.mainContainer = Caml_option.some(mainContainer);
  for(var _for = 0; _for <= 2; ++_for){
    add(bouncer);
    await WaitFor.waitFor(0.5, undefined);
  }
}

function resize(bouncer, w, h) {
  bouncer.xMin = - w / 2.0;
  bouncer.xMax = w / 2.0;
  bouncer.yMin = - h / 2.0;
  bouncer.yMax = h / 2.0;
}

var logoCount = 3;

var animationDuration = 1.0;

var waitDuration = 0.5;

export {
  logoCount ,
  animationDuration ,
  waitDuration ,
  make ,
  add ,
  remove ,
  setDirection ,
  setLimits ,
  update ,
  show ,
  resize ,
}
/* Logo Not a pure module */
