// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pixi from "../../bindings/Pixi.res.mjs";
import * as PixiJs from "pixi.js";
import * as CameraFeed from "./CameraFeed.res.mjs";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

var $$setInterval = (function(fn, ms) { return setInterval(fn, ms); });

var $$clearInterval = (function(id) { clearInterval(id); });

function make(name, ipAddress, securityLevel, worldXOpt, param) {
  var worldX = worldXOpt !== undefined ? worldXOpt : 0.0;
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel,
          worldX: worldX
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "IotCamera",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

var cameraStates = {};

function getCameraState(ipAddress) {
  var state = cameraStates[ipAddress];
  if (state !== undefined) {
    return state;
  }
  var state$1 = {
    isRecording: true,
    isEnabled: true,
    isLooping: false,
    loopedMotionState: false,
    loopedHackerPosition: undefined
  };
  cameraStates[ipAddress] = state$1;
  return state$1;
}

function createCameraInterface(container, cameraWorldX, ipAddress) {
  var state = getCameraState(ipAddress);
  var headerStyle = {
    fontFamily: "Arial",
    fontSize: 14,
    fill: 16711680,
    fontWeight: "bold"
  };
  var recIndicator = new PixiJs.Graphics();
  recIndicator.circle(30.0, 20.0, 6.0).fill({
        color: 16711680
      });
  container.addChild(recIndicator);
  var header = new PixiJs.Text({
        text: "REC - LIVE FEED",
        style: headerStyle
      });
  header.x = 45.0;
  header.y = 12.0;
  container.addChild(header);
  var feedBg = new PixiJs.Graphics();
  feedBg.rect(20.0, 50.0, 450.0, 240.0).fill({
        color: 1710638
      });
  container.addChild(feedBg);
  var feedGround = new PixiJs.Graphics();
  var groundInFeedY = 50.0 + 240.0 * 0.7;
  feedGround.rect(20.0, groundInFeedY, 450.0, 240.0 - (groundInFeedY - 50.0)).fill({
        color: 2968126
      });
  container.addChild(feedGround);
  var hackerIndicator = new PixiJs.Graphics();
  hackerIndicator.rect(-8.0, -40.0, 16.0, 40.0).fill({
        color: 3368652
      });
  hackerIndicator.circle(0.0, -50.0, 10.0).fill({
        color: 16764074
      });
  Pixi.Graphics.toContainer(hackerIndicator).visible = false;
  container.addChild(hackerIndicator);
  var scanlines = new PixiJs.Graphics();
  for(var i = 0 ,i_finish = 240.0 / 4.0 | 0; i <= i_finish; ++i){
    scanlines.rect(20.0, 50.0 + i * 4.0, 450.0, 1.0).fill({
          color: 0,
          alpha: 0.15
        });
  }
  container.addChild(scanlines);
  var feedBorder = new PixiJs.Graphics();
  feedBorder.rect(20.0, 50.0, 450.0, 240.0).stroke({
        width: 2,
        color: 65280
      });
  container.addChild(feedBorder);
  var disabledOverlay = new PixiJs.Graphics();
  disabledOverlay.rect(20.0, 50.0, 450.0, 240.0).fill({
        color: 0,
        alpha: 0.8
      });
  Pixi.Graphics.toContainer(disabledOverlay).visible = false;
  container.addChild(disabledOverlay);
  var disabledText = new PixiJs.Text({
        text: "CAMERA DISABLED",
        style: {
          fontSize: 24,
          fill: 16711680,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  disabledText.anchor.set(0.5, 0.5);
  disabledText.x = 20.0 + 450.0 / 2.0;
  disabledText.y = 50.0 + 240.0 / 2.0;
  Pixi.$$Text.toContainer(disabledText).visible = false;
  container.addChild(disabledText);
  var timestamp = new PixiJs.Text({
        text: "2024-12-08 09:45:32",
        style: {
          fontSize: 10,
          fill: 65280,
          fontFamily: "monospace"
        }
      });
  timestamp.x = 20.0 + 10.0;
  timestamp.y = 50.0 + 10.0;
  container.addChild(timestamp);
  var camName = new PixiJs.Text({
        text: "CAM-ENTRANCE",
        style: {
          fontSize: 10,
          fill: 65280,
          fontFamily: "monospace"
        }
      });
  camName.x = 20.0 + 450.0 - 100.0;
  camName.y = 50.0 + 10.0;
  container.addChild(camName);
  var motionNone = new PixiJs.Text({
        text: "MOTION: NONE",
        style: {
          fontSize: 12,
          fill: 65280,
          fontFamily: "monospace"
        }
      });
  motionNone.x = 20.0 + 10.0;
  motionNone.y = 50.0 + 240.0 - 25.0;
  container.addChild(motionNone);
  var motionDetected = new PixiJs.Text({
        text: "MOTION: DETECTED",
        style: {
          fontSize: 12,
          fill: 16711680,
          fontFamily: "monospace"
        }
      });
  motionDetected.x = 20.0 + 10.0;
  motionDetected.y = 50.0 + 240.0 - 25.0;
  Pixi.$$Text.toContainer(motionDetected).visible = false;
  container.addChild(motionDetected);
  var stopRecBtn = new PixiJs.Graphics();
  stopRecBtn.rect(20.0, 310.0, 100.0, 30.0).fill({
          color: 16711680
        }).stroke({
        width: 1,
        color: 0
      });
  stopRecBtn.eventMode = "static";
  stopRecBtn.cursor = "pointer";
  container.addChild(stopRecBtn);
  var stopRecText = new PixiJs.Text({
        text: "STOP REC",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  stopRecText.anchor.set(0.5, 0.5);
  stopRecText.x = 70.0;
  stopRecText.y = 310.0 + 15.0;
  container.addChild(stopRecText);
  stopRecBtn.on("pointertap", (function (param) {
          state.isRecording = !state.isRecording;
          if (state.isRecording) {
            stopRecText.text = "STOP REC";
            header.text = "REC - LIVE FEED";
          } else {
            stopRecText.text = "START REC";
            header.text = "PAUSED";
            Pixi.Graphics.toContainer(recIndicator).visible = false;
          }
        }));
  var loopBtn = new PixiJs.Graphics();
  loopBtn.rect(130.0, 310.0, 100.0, 30.0).fill({
          color: 16755200
        }).stroke({
        width: 1,
        color: 0
      });
  loopBtn.eventMode = "static";
  loopBtn.cursor = "pointer";
  container.addChild(loopBtn);
  var loopText = new PixiJs.Text({
        text: "LOOP FEED",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  loopText.anchor.set(0.5, 0.5);
  loopText.x = 180.0;
  loopText.y = 310.0 + 15.0;
  container.addChild(loopText);
  loopBtn.on("pointertap", (function (param) {
          state.isLooping = !state.isLooping;
          if (state.isLooping) {
            var hackerRelPos = CameraFeed.getHackerRelativePosition(cameraWorldX, 300.0);
            state.loopedHackerPosition = hackerRelPos;
            state.loopedMotionState = Core__Option.isSome(hackerRelPos);
            loopText.text = "STOP LOOP";
            header.text = "REC - LOOPED";
            return CameraFeed.setCameraLooping(ipAddress, true, state.loopedMotionState);
          }
          loopText.text = "LOOP FEED";
          header.text = state.isRecording ? "REC - LIVE FEED" : "PAUSED";
          CameraFeed.setCameraLooping(ipAddress, false, false);
        }));
  var downloadBtn = new PixiJs.Graphics();
  downloadBtn.rect(240.0, 310.0, 100.0, 30.0).fill({
          color: 35071
        }).stroke({
        width: 1,
        color: 0
      });
  downloadBtn.eventMode = "static";
  downloadBtn.cursor = "pointer";
  container.addChild(downloadBtn);
  var downloadText = new PixiJs.Text({
        text: "DOWNLOAD",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  downloadText.anchor.set(0.5, 0.5);
  downloadText.x = 290.0;
  downloadText.y = 310.0 + 15.0;
  container.addChild(downloadText);
  var disableBtn = new PixiJs.Graphics();
  disableBtn.rect(350.0, 310.0, 100.0, 30.0).fill({
          color: 6710886
        }).stroke({
        width: 1,
        color: 0
      });
  disableBtn.eventMode = "static";
  disableBtn.cursor = "pointer";
  container.addChild(disableBtn);
  var disableText = new PixiJs.Text({
        text: "DISABLE",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  disableText.anchor.set(0.5, 0.5);
  disableText.x = 400.0;
  disableText.y = 310.0 + 15.0;
  container.addChild(disableText);
  disableBtn.on("pointertap", (function (param) {
          state.isEnabled = !state.isEnabled;
          if (state.isEnabled) {
            disableText.text = "DISABLE";
            Pixi.Graphics.toContainer(disabledOverlay).visible = false;
            Pixi.$$Text.toContainer(disabledText).visible = false;
            header.text = state.isRecording ? "REC - LIVE FEED" : "PAUSED";
            CameraFeed.setCameraEnabled(ipAddress, true);
            return CameraFeed.notifyMotionStatus(ipAddress, false);
          } else {
            disableText.text = "ENABLE";
            Pixi.Graphics.toContainer(disabledOverlay).visible = true;
            Pixi.$$Text.toContainer(disabledText).visible = true;
            header.text = "DISABLED";
            Pixi.Graphics.toContainer(recIndicator).visible = false;
            CameraFeed.setCameraEnabled(ipAddress, false);
            return CameraFeed.notifyCameraDisabled(ipAddress);
          }
        }));
  var powerBtnY = 310.0 + 40.0;
  var powerBtn = new PixiJs.Graphics();
  var isShutdown = PowerManager.isDeviceShutdown(ipAddress);
  var powerBtnColor = isShutdown ? 43520 : 11141120;
  powerBtn.rect(20.0, powerBtnY, 100.0, 30.0).fill({
          color: powerBtnColor
        }).stroke({
        width: 1,
        color: 0
      });
  powerBtn.eventMode = "static";
  powerBtn.cursor = "pointer";
  container.addChild(powerBtn);
  var powerText = new PixiJs.Text({
        text: isShutdown ? "POWER ON" : "POWER OFF",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  powerText.anchor.set(0.5, 0.5);
  powerText.x = 70.0;
  powerText.y = powerBtnY + 15.0;
  container.addChild(powerText);
  powerBtn.on("pointertap", (function (param) {
          var currentlyShutdown = PowerManager.isDeviceShutdown(ipAddress);
          if (currentlyShutdown) {
            if (PowerManager.deviceHasPower(ipAddress)) {
              PowerManager.bootDevice(ipAddress);
              powerText.text = "POWER OFF";
              powerBtn.clear();
              powerBtn.rect(20.0, powerBtnY, 100.0, 30.0).fill({
                      color: 11141120
                    }).stroke({
                    width: 1,
                    color: 0
                  });
              return ;
            } else {
              return ;
            }
          } else {
            PowerManager.manualShutdownDevice(ipAddress);
            powerText.text = "POWER ON";
            powerBtn.clear();
            powerBtn.rect(20.0, powerBtnY, 100.0, 30.0).fill({
                    color: 43520
                  }).stroke({
                  width: 1,
                  color: 0
                });
            return ;
          }
        }));
  var blinkState = {
    contents: true
  };
  if (!state.isRecording) {
    stopRecText.text = "START REC";
    header.text = state.isEnabled ? "PAUSED" : "DISABLED";
    Pixi.Graphics.toContainer(recIndicator).visible = false;
  }
  if (!state.isEnabled) {
    disableText.text = "ENABLE";
    Pixi.Graphics.toContainer(disabledOverlay).visible = true;
    Pixi.$$Text.toContainer(disabledText).visible = true;
    header.text = "DISABLED";
    Pixi.Graphics.toContainer(recIndicator).visible = false;
    CameraFeed.setCameraEnabled(ipAddress, false);
    CameraFeed.notifyCameraDisabled(ipAddress);
  }
  if (state.isLooping) {
    loopText.text = "STOP LOOP";
    header.text = "REC - LOOPED";
    Pixi.Graphics.toContainer(recIndicator).visible = true;
    CameraFeed.setCameraLooping(ipAddress, true, state.loopedMotionState);
  }
  return $$setInterval((function () {
                if (state.isRecording && state.isEnabled && !state.isLooping) {
                  blinkState.contents = !blinkState.contents;
                  Pixi.Graphics.toContainer(recIndicator).visible = blinkState.contents;
                }
                if (state.isEnabled) {
                  if (state.isLooping) {
                    if (state.loopedMotionState) {
                      Pixi.$$Text.toContainer(motionNone).visible = false;
                      Pixi.$$Text.toContainer(motionDetected).visible = true;
                    } else {
                      Pixi.$$Text.toContainer(motionNone).visible = true;
                      Pixi.$$Text.toContainer(motionDetected).visible = false;
                    }
                    var relX = state.loopedHackerPosition;
                    if (relX !== undefined) {
                      var hackerFeedX = 20.0 + relX * 450.0;
                      hackerIndicator.x = hackerFeedX;
                      hackerIndicator.y = groundInFeedY;
                      Pixi.Graphics.toContainer(hackerIndicator).visible = true;
                      return ;
                    }
                    Pixi.Graphics.toContainer(hackerIndicator).visible = false;
                    return ;
                  }
                  var relX$1 = CameraFeed.getHackerRelativePosition(cameraWorldX, 300.0);
                  if (relX$1 !== undefined) {
                    Pixi.$$Text.toContainer(motionNone).visible = false;
                    Pixi.$$Text.toContainer(motionDetected).visible = true;
                    CameraFeed.notifyMotionStatus(ipAddress, true);
                    var hackerFeedX$1 = 20.0 + relX$1 * 450.0;
                    hackerIndicator.x = hackerFeedX$1;
                    hackerIndicator.y = groundInFeedY;
                    Pixi.Graphics.toContainer(hackerIndicator).visible = true;
                    return ;
                  }
                  Pixi.$$Text.toContainer(motionNone).visible = true;
                  Pixi.$$Text.toContainer(motionDetected).visible = false;
                  Pixi.Graphics.toContainer(hackerIndicator).visible = false;
                  return CameraFeed.notifyMotionStatus(ipAddress, false);
                }
                Pixi.Graphics.toContainer(hackerIndicator).visible = false;
                Pixi.$$Text.toContainer(motionNone).visible = true;
                Pixi.$$Text.toContainer(motionDetected).visible = false;
              }), 200);
}

function openGUI(device) {
  var win = DeviceWindow.make("CAMERA - " + device.name + " [" + device.ipAddress + "]", 500.0, 400.0, DeviceTypes.getDeviceColor("IotCamera"), 657930, undefined);
  var intervalId = createCameraInterface(DeviceWindow.getContent(win), device.worldX, device.ipAddress);
  DeviceWindow.setOnClose(win, (function () {
          $$clearInterval(intervalId);
          CameraFeed.notifyMotionStatus(device.ipAddress, false);
        }));
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

var cameraViewWidth = 300.0;

var skyColor = 1710638;

var groundColor = 2968126;

export {
  cameraViewWidth ,
  $$setInterval ,
  $$clearInterval ,
  make ,
  getInfo ,
  skyColor ,
  groundColor ,
  cameraStates ,
  getCameraState ,
  createCameraInterface ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
