// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

var globalFeedData = {
  contents: undefined
};

function setFeedData(data) {
  globalFeedData.contents = data;
}

function getFeedData() {
  return globalFeedData.contents;
}

var motionCallbacks = {};

function registerMotionCallback(cameraIp, callback) {
  motionCallbacks[cameraIp] = callback;
}

function unregisterMotionCallback(cameraIp) {
  Core__Dict.$$delete(motionCallbacks, cameraIp);
}

function notifyMotionStatus(cameraIp, motionDetected) {
  var callback = motionCallbacks[cameraIp];
  if (callback !== undefined) {
    return callback(motionDetected);
  }
  
}

function notifyCameraDisabled(cameraIp) {
  var callback = motionCallbacks[cameraIp];
  if (callback !== undefined) {
    return callback(undefined);
  }
  
}

function isHackerInView(cameraX, viewWidth) {
  var data = globalFeedData.contents;
  if (data === undefined) {
    return false;
  }
  var match = data.getHackerPosition();
  var hackerX = match[0];
  var leftBound = cameraX - viewWidth / 2.0;
  var rightBound = cameraX + viewWidth / 2.0;
  if (hackerX >= leftBound) {
    return hackerX <= rightBound;
  } else {
    return false;
  }
}

function getHackerRelativePosition(cameraX, viewWidth) {
  var data = globalFeedData.contents;
  if (data === undefined) {
    return ;
  }
  var match = data.getHackerPosition();
  var hackerX = match[0];
  var leftBound = cameraX - viewWidth / 2.0;
  var rightBound = cameraX + viewWidth / 2.0;
  if (hackerX >= leftBound && hackerX <= rightBound) {
    return (hackerX - leftBound) / viewWidth;
  }
  
}

var cameraPositions = {};

var disabledCameras = new Set();

var loopingCameras = {};

function registerCameraPosition(cameraIp, worldX, viewWidth) {
  cameraPositions[cameraIp] = [
    worldX,
    viewWidth
  ];
}

function setCameraEnabled(cameraIp, enabled) {
  if (enabled) {
    disabledCameras.delete(cameraIp);
  } else {
    disabledCameras.add(cameraIp);
  }
}

function setCameraLooping(cameraIp, looping, frozenMotionState) {
  if (looping) {
    loopingCameras[cameraIp] = frozenMotionState;
    return ;
  } else {
    return Core__Dict.$$delete(loopingCameras, cameraIp);
  }
}

function updateAllCameraMotion() {
  Core__Dict.forEachWithKey(cameraPositions, (function (position, ip) {
          if (disabledCameras.has(ip)) {
            return ;
          }
          var hasPower = PowerManager.isDeviceOperational(ip);
          if (hasPower) {
            var callback = motionCallbacks[ip];
            if (callback === undefined) {
              return ;
            }
            var frozenMotion = loopingCameras[ip];
            if (frozenMotion !== undefined) {
              return callback(frozenMotion);
            }
            var motionDetected = isHackerInView(position[0], position[1]);
            return callback(motionDetected);
          }
          var callback$1 = motionCallbacks[ip];
          if (callback$1 !== undefined) {
            return callback$1(undefined);
          }
          
        }));
}

export {
  globalFeedData ,
  setFeedData ,
  getFeedData ,
  motionCallbacks ,
  registerMotionCallback ,
  unregisterMotionCallback ,
  notifyMotionStatus ,
  notifyCameraDisabled ,
  isHackerInView ,
  getHackerRelativePosition ,
  cameraPositions ,
  disabledCameras ,
  loopingCameras ,
  registerCameraPosition ,
  setCameraEnabled ,
  setCameraLooping ,
  updateAllCameraMotion ,
}
/* disabledCameras Not a pure module */
