// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LaptopGUI from "./LaptopGUI.res.mjs";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "Laptop",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

var globalNetworkInterfaceSetter = {
  contents: undefined
};

function setGlobalNetworkInterfaceSetter(setter) {
  globalNetworkInterfaceSetter.contents = setter;
}

var globalStateGetter = {
  contents: undefined
};

function setGlobalStateGetter(getter) {
  globalStateGetter.contents = getter;
}

function openGUI(device) {
  var win = DeviceWindow.make("LAPTOP - " + device.name + " [" + device.ipAddress + "]", 500.0, 400.0, DeviceTypes.getDeviceColor("Laptop"), 2840471, undefined);
  var getter = globalStateGetter.contents;
  var state = getter !== undefined ? getter(device.ipAddress) : undefined;
  var laptop;
  if (state !== undefined) {
    laptop = LaptopGUI.makeWithState(490.0, 360.0, state, undefined);
  } else {
    var newLaptop = LaptopGUI.make(490.0, 360.0, device.ipAddress, device.name, undefined);
    var setter = globalNetworkInterfaceSetter.contents;
    if (setter !== undefined) {
      setter(newLaptop.state);
    }
    laptop = newLaptop;
  }
  DeviceWindow.getContent(win).addChild(laptop.container);
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  globalNetworkInterfaceSetter ,
  setGlobalNetworkInterfaceSetter ,
  globalStateGetter ,
  setGlobalStateGetter ,
  openGUI ,
  toDevice ,
}
/* LaptopGUI Not a pure module */
