// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UPSDevice from "./UPSDevice.res.mjs";
import * as CameraDevice from "./CameraDevice.res.mjs";
import * as RouterDevice from "./RouterDevice.res.mjs";
import * as ServerDevice from "./ServerDevice.res.mjs";
import * as DesktopDevice from "./DesktopDevice.res.mjs";
import * as TerminalDevice from "./TerminalDevice.res.mjs";
import * as PowerStationDevice from "./PowerStationDevice.res.mjs";

function createDevice(deviceType, name, ipAddress, securityLevel, worldXOpt, connectedStationIpOpt) {
  var worldX = worldXOpt !== undefined ? worldXOpt : 0.0;
  var connectedStationIp = connectedStationIpOpt !== undefined ? connectedStationIpOpt : "192.168.1.250";
  switch (deviceType) {
    case "Laptop" :
        var d = DesktopDevice.make(name, ipAddress, securityLevel, undefined);
        return DesktopDevice.toDevice(d);
    case "Router" :
        var d$1 = RouterDevice.make(name, ipAddress, securityLevel, undefined);
        return RouterDevice.toDevice(d$1);
    case "Server" :
        var d$2 = ServerDevice.make(name, ipAddress, securityLevel, undefined);
        return ServerDevice.toDevice(d$2);
    case "IotCamera" :
        var d$3 = CameraDevice.make(name, ipAddress, securityLevel, worldX, undefined);
        return CameraDevice.toDevice(d$3);
    case "Terminal" :
        var d$4 = TerminalDevice.make(name, ipAddress, securityLevel, undefined);
        return TerminalDevice.toDevice(d$4);
    case "PowerStation" :
        var d$5 = PowerStationDevice.make(name, ipAddress, securityLevel, undefined);
        return PowerStationDevice.toDevice(d$5);
    case "UPS" :
        var d$6 = UPSDevice.make(name, ipAddress, securityLevel, connectedStationIp, undefined);
        return UPSDevice.toDevice(d$6);
    
  }
}

export {
  createDevice ,
}
/* UPSDevice Not a pure module */
