// Generated by ReScript, PLEASE EDIT WITH CARE


var getCurrentTime = (function() { return Date.now(); });

var lastActivity = {};

function recordActivity(ip) {
  lastActivity[ip] = getCurrentTime();
}

function isActive(ip) {
  var time = lastActivity[ip];
  if (time !== undefined) {
    return getCurrentTime() - time < 30000.0;
  } else {
    return false;
  }
}

var activityTimeoutMs = 30000.0;

export {
  getCurrentTime ,
  lastActivity ,
  activityTimeoutMs ,
  recordActivity ,
  isActive ,
}
/* No side effect */
