// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as GlobalNetworkData from "./GlobalNetworkData.res.mjs";

var filesystems = {};

function resolvePath(fs, path) {
  var normalizedPath = path.replace(/\//g, "\\");
  var parts = normalizedPath.split("\\").filter(function (p) {
        if (p !== "" && p !== "." && p !== "C:") {
          return p !== "/";
        } else {
          return false;
        }
      });
  if (parts.length === 0) {
    return fs.root;
  }
  var current = {
    contents: fs.root
  };
  var found = {
    contents: true
  };
  parts.forEach(function (part) {
        if (!found.contents) {
          return ;
        }
        var match = current.contents;
        if (match.TAG === "File") {
          found.contents = false;
          return ;
        }
        var contents = match.contents;
        var node = contents[part];
        if (node !== undefined) {
          current.contents = node;
        } else {
          found.contents = false;
        }
      });
  if (found.contents) {
    return current.contents;
  }
  
}

function getParentPath(path) {
  var parts = path.split("\\").filter(function (p) {
        return p !== "";
      });
  parts.pop();
  if (parts.length === 0) {
    return "C:\\";
  } else {
    return parts.join("\\");
  }
}

function getFilename(path) {
  var parts = path.split("\\").filter(function (p) {
        return p !== "";
      });
  return Core__Option.getOr(parts[parts.length - 1 | 0], "Untitled");
}

function getFilesystem(deviceIp) {
  return filesystems[deviceIp];
}

function listFiles(deviceIp, path) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return ;
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return ;
  }
  if (match.TAG === "File") {
    return ;
  }
  var contents = match.contents;
  return Object.entries(contents).map(function (param) {
              var node = param[1];
              var name = param[0];
              if (node.TAG !== "File") {
                return [
                        name,
                        true,
                        false,
                        0.0
                      ];
              }
              var globalContentId = node.globalContentId;
              var locked = node.locked;
              var content = GlobalNetworkData.getContent(globalContentId);
              var sizeMB = content !== undefined ? content.sizeMB : 0.0;
              return [
                      name,
                      false,
                      locked,
                      sizeMB
                    ];
            });
}

function readFile(deviceIp, path) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "File not found: " + path
          };
  }
  if (match.TAG !== "File") {
    return {
            TAG: "Error",
            _0: "Is a directory: " + path
          };
  }
  var globalContentId = match.globalContentId;
  var match$1 = match.locked;
  if (match$1) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + path
          };
  }
  var content = GlobalNetworkData.getContent(globalContentId);
  if (content !== undefined) {
    return {
            TAG: "Ok",
            _0: content.content
          };
  } else {
    return {
            TAG: "Error",
            _0: "Content not found in global store"
          };
  }
}

function writeFile(deviceIp, path, newContent) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "File not found: " + path
          };
  }
  if (match.TAG !== "File") {
    return {
            TAG: "Error",
            _0: "Is a directory: " + path
          };
  }
  var match$1 = match.locked;
  if (match$1) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + path
          };
  }
  var newContentId = GlobalNetworkData.updateContent(match.globalContentId, newContent);
  match.globalContentId = newContentId;
  return {
          TAG: "Ok",
          _0: undefined
        };
}

function createDirectory(deviceIp, path, name) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Directory not found: " + path
          };
  }
  if (match.TAG === "File") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + path
          };
  }
  var contents = match.contents;
  var match$1 = contents[name];
  if (match$1 !== undefined) {
    return {
            TAG: "Error",
            _0: "Already exists: " + name
          };
  } else {
    contents[name] = {
      TAG: "Directory",
      name: name,
      contents: {}
    };
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
}

function createFile(deviceIp, path, name, content) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Directory not found: " + path
          };
  }
  if (match.TAG === "File") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + path
          };
  }
  var contents = match.contents;
  var match$1 = contents[name];
  if (match$1 !== undefined) {
    return {
            TAG: "Error",
            _0: "Already exists: " + name
          };
  }
  var contentId = GlobalNetworkData.storeContent(content, content.length / 1024.0 / 1024.0);
  contents[name] = {
    TAG: "File",
    name: name,
    globalContentId: contentId,
    locked: false
  };
  return {
          TAG: "Ok",
          _0: undefined
        };
}

function copyFile(deviceIp, sourcePath, destPath, destName) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, sourcePath);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Source not found: " + sourcePath
          };
  }
  if (match.TAG !== "File") {
    return {
            TAG: "Error",
            _0: "Cannot copy directory: " + sourcePath
          };
  }
  var globalContentId = match.globalContentId;
  var match$1 = resolvePath(fs, destPath);
  if (match$1 === undefined) {
    return {
            TAG: "Error",
            _0: "Destination not found: " + destPath
          };
  }
  if (match$1.TAG === "File") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + destPath
          };
  }
  var contents = match$1.contents;
  var match$2 = contents[destName];
  if (match$2 !== undefined) {
    return {
            TAG: "Error",
            _0: "Already exists: " + destName
          };
  } else {
    contents[destName] = {
      TAG: "File",
      name: destName,
      globalContentId: globalContentId,
      locked: false
    };
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
}

function deleteFile(deviceIp, path, name, recursive) {
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return {
            TAG: "Error",
            _0: "Device not found"
          };
  }
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Directory not found: " + path
          };
  }
  if (match.TAG === "File") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + path
          };
  }
  var contents = match.contents;
  var match$1 = contents[name];
  if (match$1 === undefined) {
    return {
            TAG: "Error",
            _0: "Not found: " + name
          };
  }
  if (match$1.TAG === "File") {
    var match$2 = match$1.locked;
    if (match$2) {
      return {
              TAG: "Error",
              _0: "Permission denied: " + name
            };
    } else {
      Core__Dict.$$delete(contents, name);
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
  }
  var dirContents = match$1.contents;
  if (!recursive && Object.values(dirContents).length > 0) {
    return {
            TAG: "Error",
            _0: "Directory not empty: " + name
          };
  } else {
    Core__Dict.$$delete(contents, name);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
}

function getTotalStorageUsed(deviceIp) {
  var calculateSize = function (node) {
    if (node.TAG === "File") {
      var globalContentId = node.globalContentId;
      var content = GlobalNetworkData.getContent(globalContentId);
      if (content !== undefined) {
        return content.sizeMB;
      } else {
        return 0.0;
      }
    }
    var contents = node.contents;
    return Core__Array.reduce(Object.values(contents), 0.0, (function (acc, child) {
                  return acc + calculateSize(child);
                }));
  };
  var fs = filesystems[deviceIp];
  if (fs !== undefined) {
    return calculateSize(fs.root);
  } else {
    return 0.0;
  }
}

function clear() {
  Object.keys(filesystems).forEach(function (key) {
        Core__Dict.$$delete(filesystems, key);
      });
}

function createFilesystem(deviceIp, deviceName) {
  filesystems[deviceIp] = {
    deviceIp: deviceIp,
    deviceName: deviceName,
    root: {
      TAG: "Directory",
      name: "C:",
      contents: {}
    }
  };
}

function addFileToFilesystem(deviceIp, path, name, content, locked, sizeMB) {
  var contentId = GlobalNetworkData.storeContent(content, sizeMB);
  var fs = filesystems[deviceIp];
  if (fs === undefined) {
    return ;
  }
  var parts = path.split("\\").filter(function (p) {
        if (p !== "") {
          return p !== "C:";
        } else {
          return false;
        }
      });
  var current = {
    contents: fs.root
  };
  parts.forEach(function (part) {
        var match = current.contents;
        if (match.TAG === "File") {
          return ;
        }
        var contents = match.contents;
        var dir = contents[part];
        if (dir !== undefined) {
          if (dir.TAG === "File") {
            return ;
          } else {
            current.contents = dir;
            return ;
          }
        }
        var newDir = {
          TAG: "Directory",
          name: part,
          contents: {}
        };
        contents[part] = newDir;
        current.contents = newDir;
      });
  var match = current.contents;
  if (match.TAG === "File") {
    return ;
  }
  var contents = match.contents;
  contents[name] = {
    TAG: "File",
    name: name,
    globalContentId: contentId,
    locked: locked
  };
}

function initializeDefaultFilesystems() {
  createFilesystem("192.168.1.1", "MAIN-ROUTER");
  createFilesystem("192.168.1.102", "CORP-LAPTOP-42");
  createFilesystem("192.168.1.103", "CORP-LAPTOP-17");
  createFilesystem("192.168.1.200", "ADMIN-PANEL");
  createFilesystem("192.168.2.1", "RURAL-ROUTER");
  createFilesystem("192.168.2.100", "HOME-LAPTOP");
  createFilesystem("100.64.1.1", "RURAL-ISP");
  createFilesystem("100.64.2.1", "BUSINESS-ISP");
  createFilesystem("198.51.100.1", "REGIONAL-ISP");
  createFilesystem("203.0.113.1", "TIER1-BACKBONE");
  createFilesystem("10.0.0.25", "MAIL-SERVER");
  createFilesystem("10.0.0.50", "DB-SERVER-01");
  createFilesystem("10.0.0.99", "SECRET-SERVER");
  createFilesystem("10.0.0.100", "CORP-INTRANET");
  addFileToFilesystem("10.0.0.50", "C:\\data", "customers.db", "=== CUSTOMER DATABASE ===\nID,Name,Email,Phone\n1,John Doe,john@example.com,555-0101\n2,Jane Smith,jane@example.com,555-0102\n3,Bob Johnson,bob@example.com,555-0103\n[... 50,000 more records ...]", true, 150.0);
  addFileToFilesystem("10.0.0.50", "C:\\admin", "passwords.txt", "=== ADMIN PASSWORDS ===\nadmin:P@ssw0rd123\nroot:toor\ndbadmin:mysql_secure_2024\nsysadmin:Adm1n!2024", true, 0.001);
  addFileToFilesystem("10.0.0.50", "C:\\config", "server.json", "{\n  \"database\": {\n    \"host\": \"localhost\",\n    \"port\": 3306,\n    \"user\": \"dbadmin\",\n    \"password\": \"mysql_secure_2024\"\n  },\n  \"api\": {\n    \"port\": 8080,\n    \"ssl\": true\n  }\n}", true, 0.002);
  addFileToFilesystem("192.168.1.200", "C:\\var\\log\\apache2", "access.log", "192.168.1.102 - - [08/Dec/2024:10:15:32] \"GET /admin HTTP/1.1\" 200 1234\n192.168.1.103 - - [08/Dec/2024:10:16:45] \"POST /login HTTP/1.1\" 302 0\n192.168.1.104 - - [08/Dec/2024:10:17:12] \"GET /dashboard HTTP/1.1\" 200 5678", true, 5.0);
  addFileToFilesystem("192.168.1.200", "C:\\var\\www\\html", ".env", "DB_HOST=10.0.0.50\nDB_USER=webserver\nDB_PASS=W3bS3rv3r!2024\nAPI_KEY=sk_live_abcdef123456\nSECRET_KEY=super_secret_key_do_not_share", true, 0.001);
  addFileToFilesystem("192.168.1.200", "C:\\var\\www\\html\\data", "users.json", "[\n  {\"id\": 1, \"username\": \"admin\", \"email\": \"admin@corp.local\", \"role\": \"administrator\"},\n  {\"id\": 2, \"username\": \"jdoe\", \"email\": \"john.doe@corp.local\", \"role\": \"user\"}\n]", false, 0.01);
  addFileToFilesystem("10.0.0.25", "C:\\var\\mail", "inbox.mbox", "From: security@corp.local\nSubject: Security Alert\n\nUnauthorized access attempt detected.\n\n---\nFrom: admin@corp.local\nSubject: Password Reset\n\nYour temporary password is: Temp123!", true, 2.5);
  addFileToFilesystem("10.0.0.25", "C:\\etc\\mail", "mail.conf", "SMTP_HOST=10.0.0.25\nSMTP_PORT=25\nADMIN_EMAIL=admin@corp.local", true, 0.001);
  addFileToFilesystem("10.0.0.99", "C:\\secure", "vault.dat", "=== ENCRYPTED VAULT ===\n[ENCRYPTION KEY REQUIRED]\nAES-256 Encrypted Data...", true, 10.0);
  addFileToFilesystem("10.0.0.99", "C:\\secure", "master.key", "-----BEGIN MASTER KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7x2...\n-----END MASTER KEY-----", true, 0.005);
  addFileToFilesystem("10.0.0.100", "C:\\var\\www\\intranet", "index.html", "<html><head><title>Corp Intranet</title></head><body><h1>Welcome to Corporate Intranet</h1></body></html>", false, 0.002);
  addFileToFilesystem("10.0.0.100", "C:\\var\\www\\intranet\\data", "employees.db", "[SQLite Database - 5000 employee records with salaries, SSNs, and addresses]", true, 25.0);
  addFileToFilesystem("192.168.1.102", "C:\\Users\\Admin\\Documents", "notes.txt", "Meeting Notes - Dec 7, 2024\n- Server maintenance scheduled for Friday\n- Update firewall rules\n- Check database backup integrity\n- TODO: Change admin password (currently: P@ssw0rd123)\n- VPN key stored in C:\\sys\\keys\\vpn.key", false, 0.001);
  addFileToFilesystem("192.168.1.102", "C:\\sys\\keys", "vpn.key", "-----BEGIN VPN KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEF\nAASCBKgwggSkAgEAAoIBAQC7x2\n-----END VPN KEY-----", true, 0.001);
  addFileToFilesystem("192.168.1.103", "C:\\projects\\webapp", "app.js", "// Main application\nconst express = require('express');\nconst app = express();\n\n// Hardcoded credentials (TODO: move to env)\nconst DB_PASSWORD = 'dev_password_123';\n\napp.listen(3000);", false, 0.05);
  addFileToFilesystem("192.168.1.103", "C:\\Users\\Developer\\.ssh", "id_rsa", "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA1234567890abcdef...\n-----END RSA PRIVATE KEY-----", true, 0.002);
  addFileToFilesystem("192.168.2.100", "C:\\Users\\Player\\Documents", "readme.txt", "Welcome to your home network!\n\nYou're connected to a small rural router.\nTry exploring the network with commands like:\n- ping <ip>\n- ssh <ip>\n- nmap\n\nGood luck!", false, 0.001);
  addFileToFilesystem("192.168.2.100", "C:\\Users\\Player\\Downloads", "tools.zip", "[Archive containing network scanning tools]", false, 0.5);
}

export {
  filesystems ,
  resolvePath ,
  getParentPath ,
  getFilename ,
  getFilesystem ,
  listFiles ,
  readFile ,
  writeFile ,
  createDirectory ,
  createFile ,
  copyFile ,
  deleteFile ,
  getTotalStorageUsed ,
  clear ,
  createFilesystem ,
  addFileToFilesystem ,
  initializeDefaultFilesystems ,
}
/* No side effect */
