// Generated by ReScript, PLEASE EDIT WITH CARE

import * as NetworkManager from "./NetworkManager.res.mjs";

var instance = {
  contents: undefined
};

function get() {
  var nm = instance.contents;
  if (nm !== undefined) {
    return nm;
  }
  var nm$1 = NetworkManager.make();
  instance.contents = nm$1;
  return nm$1;
}

function reset() {
  instance.contents = undefined;
}

export {
  instance ,
  get ,
  reset ,
}
/* NetworkManager Not a pure module */
