// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";

var hashContent = (function(content) {
    const len = content.length;
    if (len < 100) {
      // Short content: use full content + length
      return 'hash-' + len + '-' + content;
    }
    // Long content: use length + first 50 + last 50 chars
    return 'hash-' + len + '-' + content.slice(0, 50) + '-' + content.slice(-50);
  });

var contentStore = {};

function getContent(id) {
  return contentStore[id];
}

function storeContent(content, sizeMB) {
  var hash = hashContent(content);
  var match = contentStore[hash];
  if (match !== undefined) {
    return hash;
  } else {
    contentStore[hash] = {
      id: hash,
      content: content,
      sizeMB: sizeMB
    };
    return hash;
  }
}

function updateContent(oldId, newContent) {
  var old = contentStore[oldId];
  var sizeMB = old !== undefined ? old.sizeMB : newContent.length / 1024.0 / 1024.0;
  return storeContent(newContent, sizeMB);
}

function getAllContentIds() {
  return Object.keys(contentStore);
}

function getContentStoreSize() {
  return Object.values(contentStore).length;
}

function clearContent() {
  Object.keys(contentStore).forEach(function (key) {
        Core__Dict.$$delete(contentStore, key);
      });
}

function initializeDefaultContent() {
  storeContent("=== CUSTOMER DATABASE ===\nID,Name,Email,Phone\n1,John Doe,john@example.com,555-0101\n2,Jane Smith,jane@example.com,555-0102\n3,Bob Johnson,bob@example.com,555-0103\n[... 50,000 more records ...]", 150.0);
  storeContent("=== ADMIN PASSWORDS ===\nadmin:P@ssw0rd123\nroot:toor\ndbadmin:mysql_secure_2024\nsysadmin:Adm1n!2024", 0.001);
  storeContent("{\n  \"database\": {\n    \"host\": \"localhost\",\n    \"port\": 3306,\n    \"user\": \"dbadmin\",\n    \"password\": \"mysql_secure_2024\"\n  },\n  \"api\": {\n    \"port\": 8080,\n    \"ssl\": true\n  }\n}", 0.002);
  storeContent("192.168.1.102 - - [08/Dec/2024:10:15:32] \"GET /admin HTTP/1.1\" 200 1234\n192.168.1.103 - - [08/Dec/2024:10:16:45] \"POST /login HTTP/1.1\" 302 0\n192.168.1.104 - - [08/Dec/2024:10:17:12] \"GET /dashboard HTTP/1.1\" 200 5678", 5.0);
  storeContent("DB_HOST=10.0.0.50\nDB_USER=webserver\nDB_PASS=W3bS3rv3r!2024\nAPI_KEY=sk_live_abcdef123456\nSECRET_KEY=super_secret_key_do_not_share", 0.001);
  storeContent("[\n  {\"id\": 1, \"username\": \"admin\", \"email\": \"admin@corp.local\", \"role\": \"administrator\"},\n  {\"id\": 2, \"username\": \"jdoe\", \"email\": \"john.doe@corp.local\", \"role\": \"user\"}\n]", 0.01);
  storeContent("From: security@corp.local\nSubject: Security Alert\n\nUnauthorized access attempt detected.\n\n---\nFrom: admin@corp.local\nSubject: Password Reset\n\nYour temporary password is: Temp123!", 2.5);
  storeContent("SMTP_HOST=10.0.0.25\nSMTP_PORT=25\nADMIN_EMAIL=admin@corp.local", 0.001);
  storeContent("=== ENCRYPTED VAULT ===\n[ENCRYPTION KEY REQUIRED]\nAES-256 Encrypted Data...", 10.0);
  storeContent("-----BEGIN MASTER KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7x2...\n-----END MASTER KEY-----", 0.005);
  storeContent("<html><head><title>Corp Intranet</title></head><body><h1>Welcome to Corporate Intranet</h1></body></html>", 0.002);
  storeContent("[SQLite Database - 5000 employee records with salaries, SSNs, and addresses]", 25.0);
  storeContent("Meeting Notes - Dec 7, 2024\n- Server maintenance scheduled for Friday\n- Update firewall rules\n- Check database backup integrity\n- TODO: Change admin password (currently: P@ssw0rd123)\n- VPN key stored in C:\\sys\\keys\\vpn.key", 0.001);
  storeContent("-----BEGIN VPN KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEF\nAASCBKgwggSkAgEAAoIBAQC7x2\n-----END VPN KEY-----", 0.001);
  storeContent("// Main application\nconst express = require('express');\nconst app = express();\n\n// Hardcoded credentials (TODO: move to env)\nconst DB_PASSWORD = 'dev_password_123';\n\napp.listen(3000);", 0.05);
  storeContent("-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA1234567890abcdef...\n-----END RSA PRIVATE KEY-----", 0.002);
}

export {
  hashContent ,
  contentStore ,
  getContent ,
  storeContent ,
  updateContent ,
  getAllContentIds ,
  getContentStoreSize ,
  clearContent ,
  initializeDefaultContent ,
}
/* No side effect */
