// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";
import * as DeviceView from "./DeviceView.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

var serviceDefinitions = [
  {
    serviceType: "SSH",
    processName: "sshd.exe",
    port: 22,
    cpuPercent: 0.3,
    sizeGq: 1
  },
  {
    serviceType: "HTTP",
    processName: "httpd.exe",
    port: 80,
    cpuPercent: 0.8,
    sizeGq: 2
  },
  {
    serviceType: "RDP",
    processName: "rdp-svc.exe",
    port: 3389,
    cpuPercent: 0.5,
    sizeGq: 1
  },
  {
    serviceType: "Desktop",
    processName: "explorer.exe",
    port: undefined,
    cpuPercent: 1.5,
    sizeGq: 2
  },
  {
    serviceType: "Desktop",
    processName: "dwm.exe",
    port: undefined,
    cpuPercent: 1.2,
    sizeGq: 1
  },
  {
    serviceType: "Security",
    processName: "secmon.exe",
    port: undefined,
    cpuPercent: 0.5,
    sizeGq: 1
  }
];

var runningServices = {};

function getDeviceServices(ip) {
  var services = runningServices[ip];
  if (services !== undefined) {
    return services;
  }
  var services$1 = {};
  runningServices[ip] = services$1;
  return services$1;
}

function serviceTypeToKey(st) {
  switch (st) {
    case "SSH" :
        return "ssh";
    case "HTTP" :
        return "http";
    case "RDP" :
        return "rdp";
    case "Desktop" :
        return "desktop";
    case "Security" :
        return "security";
    
  }
}

function isServiceRunning(ip, service) {
  var services = getDeviceServices(ip);
  var key = serviceTypeToKey(service);
  var running = services[key];
  if (running !== undefined) {
    return running;
  } else {
    return false;
  }
}

function startService(ip, service) {
  var services = getDeviceServices(ip);
  var key = serviceTypeToKey(service);
  services[key] = true;
}

function stopService(ip, service) {
  var services = getDeviceServices(ip);
  var key = serviceTypeToKey(service);
  services[key] = false;
}

function getRunningServiceProcesses(ip) {
  var services = getDeviceServices(ip);
  var runningProcs = [];
  serviceDefinitions.forEach(function (def) {
        var key = serviceTypeToKey(def.serviceType);
        var match = services[key];
        var isRunning = match !== undefined && match ? true : false;
        if (isRunning) {
          runningProcs.push([
                def.processName,
                def.cpuPercent,
                def.sizeGq
              ]);
          return ;
        }
        
      });
  return runningProcs;
}

function isPortOpen(ip, port) {
  var services = getDeviceServices(ip);
  var matchingService = serviceDefinitions.find(function (def) {
        var p = def.port;
        if (p !== undefined) {
          return p === port;
        } else {
          return false;
        }
      });
  if (matchingService === undefined) {
    return false;
  }
  var key = serviceTypeToKey(matchingService.serviceType);
  var running = services[key];
  if (running !== undefined) {
    return running;
  } else {
    return false;
  }
}

function initializeServices(ip, isServer) {
  if (isServer) {
    startService(ip, "SSH");
    startService(ip, "HTTP");
    return startService(ip, "Security");
  } else {
    startService(ip, "Desktop");
    return startService(ip, "Security");
  }
}

var ServiceManager = {
  serviceDefinitions: serviceDefinitions,
  runningServices: runningServices,
  getDeviceServices: getDeviceServices,
  serviceTypeToKey: serviceTypeToKey,
  isServiceRunning: isServiceRunning,
  startService: startService,
  stopService: stopService,
  getRunningServiceProcesses: getRunningServiceProcesses,
  isPortOpen: isPortOpen,
  initializeServices: initializeServices
};

function createProcessManager() {
  var coreProcesses = [
    {
      pid: 1,
      name: "System",
      cpuPercent: 0.5,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 4,
      name: "smss.exe",
      cpuPercent: 0.1,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 128,
      name: "csrss.exe",
      cpuPercent: 0.2,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 256,
      name: "services.exe",
      cpuPercent: 0.3,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 512,
      name: "lsass.exe",
      cpuPercent: 0.2,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 768,
      name: "svchost.exe",
      cpuPercent: 0.8,
      sizeGq: 1,
      isSystem: true
    }
  ];
  return {
          spec: {
            totalStorageGq: 8192,
            cpuCores: 4
          },
          nextPid: 1024,
          processes: coreProcesses,
          openApps: {},
          windowClosers: {},
          cpuSpike: 0.0,
          lastSpikeTime: 0.0
        };
}

function syncServicesWithProcesses(pm, ipAddress) {
  var runningServiceProcs = getRunningServiceProcesses(ipAddress);
  pm.processes = pm.processes.filter(function (proc) {
        if (proc.pid < 1024) {
          return true;
        }
        var isUserApp = Object.entries(pm.openApps).some(function (param) {
              return param[1] === proc.pid;
            });
        if (isUserApp) {
          return true;
        } else {
          return runningServiceProcs.some(function (param) {
                      return param[0] === proc.name;
                    });
        }
      });
  runningServiceProcs.forEach(function (param) {
        var processName = param[0];
        var alreadyExists = pm.processes.some(function (proc) {
              return proc.name === processName;
            });
        if (alreadyExists) {
          return ;
        }
        var pid = pm.nextPid;
        pm.nextPid = pm.nextPid + 1 | 0;
        var proc = {
          pid: pid,
          name: processName,
          cpuPercent: param[1],
          sizeGq: param[2],
          isSystem: true
        };
        pm.processes = pm.processes.concat([proc]);
      });
}

function appSize(appName) {
  switch (appName) {
    case "explorer.exe" :
        return 2;
    default:
      return 1;
  }
}

function openApp(pm, appName) {
  var pid = pm.openApps[appName];
  if (pid !== undefined) {
    return pid;
  }
  var pid$1 = pm.nextPid;
  pm.nextPid = pm.nextPid + 1 | 0;
  var cpuPercent = 0.3 + pid$1 % 10 / 20.0;
  var $$process = {
    pid: pid$1,
    name: appName,
    cpuPercent: cpuPercent,
    sizeGq: appSize(appName),
    isSystem: false
  };
  pm.processes = pm.processes.concat([$$process]);
  pm.openApps[appName] = pid$1;
  return pid$1;
}

function registerWindowCloser(pm, pid, closer) {
  pm.windowClosers[pid.toString()] = closer;
}

function closeApp(pm, appName) {
  var pid = pm.openApps[appName];
  if (pid !== undefined) {
    pm.processes = pm.processes.filter(function (p) {
          return p.pid !== pid;
        });
    Core__Dict.$$delete(pm.openApps, appName);
    return Core__Dict.$$delete(pm.windowClosers, pid.toString());
  }
  
}

function processNameToService(processName) {
  switch (processName) {
    case "dwm.exe" :
    case "explorer.exe" :
        return "Desktop";
    case "httpd.exe" :
        return "HTTP";
    case "rdp-svc.exe" :
        return "RDP";
    case "secmon.exe" :
        return "Security";
    case "sshd.exe" :
        return "SSH";
    default:
      return ;
  }
}

function killProcess(pm, pid, ipAddress) {
  var proc = pm.processes.find(function (p) {
        return p.pid === pid;
      });
  if (proc === undefined) {
    return {
            TAG: "Error",
            _0: "No such process: " + pid.toString()
          };
  }
  var isCoreOS = proc.pid < 1024 && processNameToService(proc.name) === undefined;
  if (isCoreOS) {
    return {
            TAG: "Error",
            _0: "Cannot kill core OS process: " + proc.name
          };
  }
  var serviceType = processNameToService(proc.name);
  if (serviceType !== undefined) {
    stopService(ipAddress, serviceType);
  }
  var closer = pm.windowClosers[pid.toString()];
  if (closer !== undefined) {
    closer();
  }
  pm.processes = pm.processes.filter(function (p) {
        return p.pid !== pid;
      });
  Object.entries(pm.openApps).forEach(function (param) {
        if (param[1] === pid) {
          return Core__Dict.$$delete(pm.openApps, param[0]);
        }
        
      });
  Core__Dict.$$delete(pm.windowClosers, pid.toString());
  return {
          TAG: "Ok",
          _0: undefined
        };
}

function getProcesses(pm) {
  return pm.processes;
}

function getProcessStorageUsage(pm) {
  return Core__Array.reduce(pm.processes, 0, (function (acc, p) {
                return acc + p.sizeGq | 0;
              }));
}

function getTotalStorageUsage(pm, ipAddress) {
  var processUsage = getProcessStorageUsage(pm);
  var fileUsageMB = DeviceView.getTotalStorageUsed(ipAddress);
  var fileUsageGq = fileUsageMB / 100.0 | 0;
  var fileUsageGq$1 = fileUsageGq < 1 ? 1 : fileUsageGq;
  return [
          processUsage + fileUsageGq$1 | 0,
          pm.spec.totalStorageGq
        ];
}

function addCpuSpike(pm, amount) {
  pm.cpuSpike = pm.cpuSpike + amount;
  if (pm.cpuSpike > 50.0) {
    pm.cpuSpike = 50.0;
    return ;
  }
  
}

function updateCpuSpike(pm, deltaSeconds) {
  pm.cpuSpike = pm.cpuSpike * (1.0 - deltaSeconds * 2.0);
  if (pm.cpuSpike < 0.1) {
    pm.cpuSpike = 0.0;
    return ;
  }
  
}

function getCpuUsage(pm) {
  var base = Core__Array.reduce(pm.processes, 0.0, (function (acc, p) {
          return acc + p.cpuPercent;
        }));
  var total = base + pm.cpuSpike;
  var maxCpu = pm.spec.cpuCores * 100.0;
  if (total < maxCpu) {
    return total;
  } else {
    return maxCpu;
  }
}

function createLaptopState(ipAddressOpt, hostnameOpt, isServerOpt, param) {
  var ipAddress = ipAddressOpt !== undefined ? ipAddressOpt : "192.168.1.102";
  var hostname = hostnameOpt !== undefined ? hostnameOpt : "WORKSTATION-PC";
  var isServer = isServerOpt !== undefined ? isServerOpt : false;
  initializeServices(ipAddress, isServer);
  var pm = createProcessManager();
  syncServicesWithProcesses(pm, ipAddress);
  return {
          processManager: pm,
          commandHistory: [],
          loginHistory: [
            [
              "Admin",
              "Dec 07 22:15:32"
            ],
            [
              "Admin",
              "Dec 06 10:23:01"
            ]
          ],
          currentUser: "Admin",
          bootTime: 0.0,
          ipAddress: ipAddress,
          hostname: hostname,
          networkInterface: undefined
        };
}

function setNetworkInterface(state, ni) {
  state.networkInterface = ni;
}

function addToHistory(state, cmd) {
  state.commandHistory = state.commandHistory.concat([cmd]);
}

function clearHistory(state) {
  state.commandHistory = [];
}

function getHistory(state) {
  return state.commandHistory;
}

export {
  ServiceManager ,
  createProcessManager ,
  syncServicesWithProcesses ,
  appSize ,
  openApp ,
  registerWindowCloser ,
  closeApp ,
  processNameToService ,
  killProcess ,
  getProcesses ,
  getProcessStorageUsage ,
  getTotalStorageUsage ,
  addCpuSpike ,
  updateCpuSpike ,
  getCpuUsage ,
  createLaptopState ,
  setNetworkInterface ,
  addToHistory ,
  clearHistory ,
  getHistory ,
}
/* No side effect */
