// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function calcFileSize(content) {
  var len = content.length;
  if (len < 100) {
    return 1;
  } else if (len < 500) {
    return 2;
  } else if (len < 1000) {
    return 3;
  } else {
    return 4;
  }
}

function createFilesystem() {
  return {
          root: {
            TAG: "Dir",
            contents: Object.fromEntries([[
                    "C:",
                    {
                      TAG: "Dir",
                      contents: Object.fromEntries([
                            [
                              "Users",
                              {
                                TAG: "Dir",
                                contents: Object.fromEntries([[
                                        "Admin",
                                        {
                                          TAG: "Dir",
                                          contents: Object.fromEntries([
                                                [
                                                  "Documents",
                                                  {
                                                    TAG: "Dir",
                                                    contents: Object.fromEntries([
                                                          [
                                                            "notes.txt",
                                                            {
                                                              TAG: "File",
                                                              content: "Meeting Notes:\n- Server maintenance scheduled for Friday\n- Update firewall rules\n- Check database backup integrity\n- Admin password: [REDACTED]\n- VPN key stored in C:\\sys\\keys\\vpn.key",
                                                              locked: false,
                                                              size: 1
                                                            }
                                                          ],
                                                          [
                                                            "passwords.txt",
                                                            {
                                                              TAG: "File",
                                                              content: "admin:P@ssw0rd123\nroot:toor\ndbuser:mysql_secure_2024",
                                                              locked: true,
                                                              size: 1
                                                            }
                                                          ]
                                                        ])
                                                  }
                                                ],
                                                [
                                                  "Downloads",
                                                  {
                                                    TAG: "Dir",
                                                    contents: {}
                                                  }
                                                ],
                                                [
                                                  "Desktop",
                                                  {
                                                    TAG: "Dir",
                                                    contents: {}
                                                  }
                                                ]
                                              ])
                                        }
                                      ]])
                              }
                            ],
                            [
                              "Program Files",
                              {
                                TAG: "Dir",
                                contents: Object.fromEntries([[
                                        "readme.txt",
                                        {
                                          TAG: "File",
                                          content: "System programs directory",
                                          locked: true,
                                          size: 1
                                        }
                                      ]])
                              }
                            ],
                            [
                              "sys",
                              {
                                TAG: "Dir",
                                contents: Object.fromEntries([
                                      [
                                        "keys",
                                        {
                                          TAG: "Dir",
                                          contents: Object.fromEntries([[
                                                  "vpn.key",
                                                  {
                                                    TAG: "File",
                                                    content: "-----BEGIN VPN KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEF\nAASCBKgwggSkAgEAAoIBAQC7x2\n-----END VPN KEY-----",
                                                    locked: true,
                                                    size: 1
                                                  }
                                                ]])
                                        }
                                      ],
                                      [
                                        "config",
                                        {
                                          TAG: "Dir",
                                          contents: Object.fromEntries([[
                                                  "network.conf",
                                                  {
                                                    TAG: "File",
                                                    content: "INTERFACE=eth0\nDHCP=enabled\nDNS=8.8.8.8",
                                                    locked: true,
                                                    size: 1
                                                  }
                                                ]])
                                        }
                                      ]
                                    ])
                              }
                            ],
                            [
                              "Windows",
                              {
                                TAG: "Dir",
                                contents: Object.fromEntries([[
                                        "System32",
                                        {
                                          TAG: "Dir",
                                          contents: Object.fromEntries([[
                                                  "config.sys",
                                                  {
                                                    TAG: "File",
                                                    content: "SYSTEM CONFIGURATION\nDO NOT MODIFY",
                                                    locked: true,
                                                    size: 1
                                                  }
                                                ]])
                                        }
                                      ]])
                              }
                            ],
                            [
                              "secret_keys.dat",
                              {
                                TAG: "File",
                                content: "ENCRYPTED KEY DATA\n---BEGIN KEY---\nABCDEF1234567890\n---END KEY---",
                                locked: true,
                                size: 1
                              }
                            ]
                          ])
                    }
                  ]])
          }
        };
}

function getNodeSize(node) {
  if (node.TAG !== "Dir") {
    return node.size;
  }
  var contents = node.contents;
  return Core__Array.reduce(Object.values(contents), 0, (function (acc, child) {
                return acc + getNodeSize(child) | 0;
              }));
}

function getFilesystemUsage(fs) {
  return getNodeSize(fs.root);
}

function resolvePath(fs, path) {
  var normalizedPath = path.replace(/\//g, "\\");
  var parts = normalizedPath.split("\\").filter(function (p) {
        if (p !== "") {
          return p !== ".";
        } else {
          return false;
        }
      });
  if (parts.length === 0) {
    return fs.root;
  }
  var current = {
    contents: fs.root
  };
  var found = {
    contents: true
  };
  parts.forEach(function (part) {
        if (!(found.contents && part !== "..")) {
          return ;
        }
        var match = current.contents;
        if (match.TAG !== "Dir") {
          found.contents = false;
          return ;
        }
        var contents = match.contents;
        var node = contents[part];
        if (node !== undefined) {
          current.contents = node;
        } else {
          found.contents = false;
        }
      });
  if (found.contents) {
    return current.contents;
  }
  
}

function listDir(fs, path) {
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return ;
  }
  if (match.TAG !== "Dir") {
    return ;
  }
  var contents = match.contents;
  return Object.entries(contents).map(function (param) {
              var node = param[1];
              var name = param[0];
              if (node.TAG === "Dir") {
                return [
                        name,
                        true,
                        false,
                        getNodeSize(node)
                      ];
              }
              var locked = node.locked;
              return [
                      name,
                      false,
                      locked,
                      node.size
                    ];
            });
}

function readFile(fs, path) {
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "File not found: " + path
          };
  }
  if (match.TAG === "Dir") {
    return {
            TAG: "Error",
            _0: "Is a directory: " + path
          };
  }
  var content = match.content;
  var match$1 = match.locked;
  if (match$1) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + path
          };
  } else {
    return {
            TAG: "Ok",
            _0: content
          };
  }
}

function getFileInfo(fs, path) {
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return ;
  }
  if (match.TAG === "Dir") {
    return [
            true,
            false,
            getNodeSize(match),
            0
          ];
  }
  var content = match.content;
  var locked = match.locked;
  return [
          false,
          locked,
          match.size,
          content.length
        ];
}

function writeFile(fs, path, content) {
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "File not found: " + path
          };
  }
  if (match.TAG === "Dir") {
    return {
            TAG: "Error",
            _0: "Is a directory: " + path
          };
  }
  var match$1 = match.locked;
  if (match$1) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + path
          };
  } else {
    match.content = content;
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
}

function createFile(fs, dirPath, fileName, content) {
  var match = resolvePath(fs, dirPath);
  if (match !== undefined) {
    if (match.TAG === "Dir") {
      if (Core__Option.isSome(match.contents[fileName])) {
        return {
                TAG: "Error",
                _0: "File already exists: " + fileName
              };
      } else {
        match.contents[fileName] = {
          TAG: "File",
          content: content,
          locked: false,
          size: calcFileSize(content)
        };
        return {
                TAG: "Ok",
                _0: undefined
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: "Not a directory: " + dirPath
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "Directory not found: " + dirPath
          };
  }
}

function createDir(fs, dirPath, dirName) {
  var match = resolvePath(fs, dirPath);
  if (match !== undefined) {
    if (match.TAG === "Dir") {
      if (Core__Option.isSome(match.contents[dirName])) {
        return {
                TAG: "Error",
                _0: "Already exists: " + dirName
              };
      } else {
        match.contents[dirName] = {
          TAG: "Dir",
          contents: {}
        };
        return {
                TAG: "Ok",
                _0: undefined
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: "Not a directory: " + dirPath
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "Directory not found: " + dirPath
          };
  }
}

function deleteNode(fs, dirPath, nodeName) {
  var match = resolvePath(fs, dirPath);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Directory not found: " + dirPath
          };
  }
  if (match.TAG !== "Dir") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + dirPath
          };
  }
  var match$1 = match.contents[nodeName];
  if (match$1 === undefined) {
    return {
            TAG: "Error",
            _0: "Not found: " + nodeName
          };
  }
  if (match$1.TAG === "Dir") {
    var contents = match$1.contents;
    if (Object.keys(contents).length > 0) {
      return {
              TAG: "Error",
              _0: "Directory not empty: " + nodeName
            };
    } else {
      Core__Dict.$$delete(match.contents, nodeName);
      return {
              TAG: "Ok",
              _0: undefined
            };
    }
  }
  var match$2 = match$1.locked;
  if (match$2) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + nodeName
          };
  } else {
    Core__Dict.$$delete(match.contents, nodeName);
    return {
            TAG: "Ok",
            _0: undefined
          };
  }
}

function copyFile(fs, srcPath, destDirPath, destName) {
  var match = resolvePath(fs, srcPath);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Source not found: " + srcPath
          };
  }
  if (match.TAG === "Dir") {
    return {
            TAG: "Error",
            _0: "Cannot copy directory: " + srcPath
          };
  }
  var content = match.content;
  var match$1 = match.locked;
  if (match$1) {
    return {
            TAG: "Error",
            _0: "Permission denied: " + srcPath
          };
  }
  var match$2 = resolvePath(fs, destDirPath);
  if (match$2 !== undefined) {
    if (match$2.TAG === "Dir") {
      if (Core__Option.isSome(match$2.contents[destName])) {
        return {
                TAG: "Error",
                _0: "File already exists: " + destName
              };
      } else {
        match$2.contents[destName] = {
          TAG: "File",
          content: content,
          locked: false,
          size: match.size
        };
        return {
                TAG: "Ok",
                _0: undefined
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: "Not a directory: " + destDirPath
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "Destination directory not found: " + destDirPath
          };
  }
}

function moveFile(fs, srcDirPath, srcName, destDirPath, destName) {
  var match = resolvePath(fs, srcDirPath);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "Source directory not found: " + srcDirPath
          };
  }
  if (match.TAG !== "Dir") {
    return {
            TAG: "Error",
            _0: "Not a directory: " + srcDirPath
          };
  }
  var node = match.contents[srcName];
  if (node === undefined) {
    return {
            TAG: "Error",
            _0: "Not found: " + srcName
          };
  }
  if (node.TAG !== "Dir") {
    var match$1 = node.locked;
    if (match$1) {
      return {
              TAG: "Error",
              _0: "Permission denied: " + srcName
            };
    }
    
  }
  var match$2 = resolvePath(fs, destDirPath);
  if (match$2 !== undefined) {
    if (match$2.TAG === "Dir") {
      if (Core__Option.isSome(match$2.contents[destName])) {
        return {
                TAG: "Error",
                _0: "Already exists: " + destName
              };
      } else {
        Core__Dict.$$delete(match.contents, srcName);
        match$2.contents[destName] = node;
        return {
                TAG: "Ok",
                _0: undefined
              };
      }
    } else {
      return {
              TAG: "Error",
              _0: "Not a directory: " + destDirPath
            };
    }
  } else {
    return {
            TAG: "Error",
            _0: "Destination directory not found: " + destDirPath
          };
  }
}

function setFileLocked(fs, path, locked) {
  var match = resolvePath(fs, path);
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "File not found: " + path
          };
  }
  if (match.TAG === "Dir") {
    return {
            TAG: "Error",
            _0: "Is a directory: " + path
          };
  }
  match.locked = locked;
  return {
          TAG: "Ok",
          _0: undefined
        };
}

function createProcessManager() {
  var systemProcesses = [
    {
      pid: 1,
      name: "System",
      cpuPercent: 0.5,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 4,
      name: "smss.exe",
      cpuPercent: 0.1,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 128,
      name: "csrss.exe",
      cpuPercent: 0.2,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 256,
      name: "services.exe",
      cpuPercent: 0.3,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 512,
      name: "lsass.exe",
      cpuPercent: 0.2,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 768,
      name: "svchost.exe",
      cpuPercent: 0.8,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 1024,
      name: "explorer.exe",
      cpuPercent: 1.5,
      sizeGq: 2,
      isSystem: true
    },
    {
      pid: 1280,
      name: "dwm.exe",
      cpuPercent: 1.2,
      sizeGq: 1,
      isSystem: true
    },
    {
      pid: 1536,
      name: "secmon.exe",
      cpuPercent: 0.5,
      sizeGq: 1,
      isSystem: true
    }
  ];
  return {
          spec: {
            totalStorageGq: 8192,
            cpuCores: 4
          },
          nextPid: 2000,
          processes: systemProcesses,
          openApps: {},
          windowClosers: {},
          cpuSpike: 0.0,
          lastSpikeTime: 0.0
        };
}

function appSize(appName) {
  switch (appName) {
    case "explorer.exe" :
        return 2;
    default:
      return 1;
  }
}

function openApp(pm, appName) {
  var pid = pm.openApps[appName];
  if (pid !== undefined) {
    return pid;
  }
  var pid$1 = pm.nextPid;
  pm.nextPid = pm.nextPid + 1 | 0;
  var cpuPercent = 0.3 + pid$1 % 10 / 20.0;
  var $$process = {
    pid: pid$1,
    name: appName,
    cpuPercent: cpuPercent,
    sizeGq: appSize(appName),
    isSystem: false
  };
  pm.processes = pm.processes.concat([$$process]);
  pm.openApps[appName] = pid$1;
  return pid$1;
}

function registerWindowCloser(pm, pid, closer) {
  pm.windowClosers[pid.toString()] = closer;
}

function closeApp(pm, appName) {
  var pid = pm.openApps[appName];
  if (pid !== undefined) {
    pm.processes = pm.processes.filter(function (p) {
          return p.pid !== pid;
        });
    Core__Dict.$$delete(pm.openApps, appName);
    return Core__Dict.$$delete(pm.windowClosers, pid.toString());
  }
  
}

function killProcess(pm, pid) {
  var proc = pm.processes.find(function (p) {
        return p.pid === pid;
      });
  if (proc === undefined) {
    return {
            TAG: "Error",
            _0: "No such process: " + pid.toString()
          };
  }
  if (proc.isSystem) {
    return {
            TAG: "Error",
            _0: "Cannot kill system process: " + proc.name
          };
  }
  var closer = pm.windowClosers[pid.toString()];
  if (closer !== undefined) {
    closer();
  }
  pm.processes = pm.processes.filter(function (p) {
        return p.pid !== pid;
      });
  Object.entries(pm.openApps).forEach(function (param) {
        if (param[1] === pid) {
          return Core__Dict.$$delete(pm.openApps, param[0]);
        }
        
      });
  Core__Dict.$$delete(pm.windowClosers, pid.toString());
  return {
          TAG: "Ok",
          _0: undefined
        };
}

function getProcesses(pm) {
  return pm.processes;
}

function getProcessStorageUsage(pm) {
  return Core__Array.reduce(pm.processes, 0, (function (acc, p) {
                return acc + p.sizeGq | 0;
              }));
}

function getTotalStorageUsage(pm, fs) {
  var processUsage = getProcessStorageUsage(pm);
  var fileUsage = getNodeSize(fs.root);
  return [
          processUsage + fileUsage | 0,
          pm.spec.totalStorageGq
        ];
}

function addCpuSpike(pm, amount) {
  pm.cpuSpike = pm.cpuSpike + amount;
  if (pm.cpuSpike > 50.0) {
    pm.cpuSpike = 50.0;
    return ;
  }
  
}

function updateCpuSpike(pm, deltaSeconds) {
  pm.cpuSpike = pm.cpuSpike * (1.0 - deltaSeconds * 2.0);
  if (pm.cpuSpike < 0.1) {
    pm.cpuSpike = 0.0;
    return ;
  }
  
}

function getCpuUsage(pm) {
  var base = Core__Array.reduce(pm.processes, 0.0, (function (acc, p) {
          return acc + p.cpuPercent;
        }));
  var total = base + pm.cpuSpike;
  var maxCpu = pm.spec.cpuCores * 100.0;
  if (total < maxCpu) {
    return total;
  } else {
    return maxCpu;
  }
}

function createLaptopState(ipAddressOpt, hostnameOpt, param) {
  var ipAddress = ipAddressOpt !== undefined ? ipAddressOpt : "192.168.1.102";
  var hostname = hostnameOpt !== undefined ? hostnameOpt : "WORKSTATION-PC";
  return {
          filesystem: createFilesystem(),
          processManager: createProcessManager(),
          commandHistory: [],
          loginHistory: [
            [
              "Admin",
              "Dec 07 22:15:32"
            ],
            [
              "Admin",
              "Dec 06 10:23:01"
            ]
          ],
          currentUser: "Admin",
          bootTime: 0.0,
          ipAddress: ipAddress,
          hostname: hostname,
          networkInterface: undefined
        };
}

function setNetworkInterface(state, ni) {
  state.networkInterface = ni;
}

function addToHistory(state, cmd) {
  state.commandHistory = state.commandHistory.concat([cmd]);
}

function clearHistory(state) {
  state.commandHistory = [];
}

function getHistory(state) {
  return state.commandHistory;
}

export {
  calcFileSize ,
  createFilesystem ,
  getNodeSize ,
  getFilesystemUsage ,
  resolvePath ,
  listDir ,
  readFile ,
  getFileInfo ,
  writeFile ,
  createFile ,
  createDir ,
  deleteNode ,
  copyFile ,
  moveFile ,
  setFileLocked ,
  createProcessManager ,
  appSize ,
  openApp ,
  registerWindowCloser ,
  closeApp ,
  killProcess ,
  getProcesses ,
  getProcessStorageUsage ,
  getTotalStorageUsage ,
  addCpuSpike ,
  updateCpuSpike ,
  getCpuUsage ,
  createLaptopState ,
  setNetworkInterface ,
  addToHistory ,
  clearHistory ,
  getHistory ,
}
/* No side effect */
