// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Ui from "@pixi/ui";
import * as Terminal from "./Terminal.res.mjs";
import * as DeviceView from "./DeviceView.res.mjs";
import * as LaptopState from "./LaptopState.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";
import * as NetworkManagerResMjs from "./NetworkManager.res.mjs";
import * as GlobalNetworkManagerResMjs from "./GlobalNetworkManager.res.mjs";

function make(title, w, h, appName, onClose, param) {
  var container = new PixiJs.Container();
  container.eventMode = "static";
  container.zIndex = 1;
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, w, h).fill({
          color: 15790320
        }).stroke({
        width: 1,
        color: 0
      });
  container.addChild(bg);
  var titleBar = new PixiJs.Graphics();
  titleBar.rect(0.0, 0.0, w, 25.0).fill({
        color: 30932
      });
  titleBar.eventMode = "static";
  titleBar.cursor = "grab";
  container.addChild(titleBar);
  var titleText = new PixiJs.Text({
        text: title,
        style: {
          fontSize: 12,
          fill: 16777215,
          fontFamily: "Arial"
        }
      });
  titleText.x = 5.0;
  titleText.y = 6.0;
  titleBar.addChild(titleText);
  var closeBtn = new PixiJs.Graphics();
  closeBtn.rect(w - 25.0, 2.0, 20.0, 20.0).fill({
        color: 16711680
      });
  closeBtn.eventMode = "static";
  closeBtn.cursor = "pointer";
  var closeX = new PixiJs.Text({
        text: "X",
        style: {
          fontSize: 12,
          fill: 16777215
        }
      });
  closeX.x = w - 18.0;
  closeX.y = 5.0;
  closeBtn.addChild(closeX);
  titleBar.addChild(closeBtn);
  var content = new PixiJs.Container();
  content.y = 25.0;
  container.addChild(content);
  var windowState = {
    container: container,
    titleBar: titleBar,
    content: content,
    closeBtn: closeBtn,
    isDragging: false,
    dragOffset: {
      x: 0.0,
      y: 0.0
    },
    appName: appName
  };
  closeBtn.on("pointertap", (function (param) {
          onClose();
          container.destroy();
        }));
  titleBar.on("pointerdown", (function (e) {
          windowState.isDragging = true;
          titleBar.cursor = "grabbing";
          windowState.dragOffset = {
            x: e.global.x - container.x,
            y: e.global.y - container.y
          };
          var parent = container.parent;
          if (!(parent == null)) {
            parent.on("pointermove", (function (e) {
                    if (windowState.isDragging) {
                      container.x = e.global.x - windowState.dragOffset.x;
                      container.y = e.global.y - windowState.dragOffset.y;
                      return ;
                    }
                    
                  }));
            parent.on("pointerup", (function (param) {
                    windowState.isDragging = false;
                    titleBar.cursor = "grab";
                  }));
            parent.on("pointerupoutside", (function (param) {
                    windowState.isDragging = false;
                    titleBar.cursor = "grab";
                  }));
            return ;
          }
          
        }));
  return windowState;
}

function getContent(win) {
  return win.content;
}

var AppWindow = {
  make: make,
  getContent: getContent
};

function splitPath(path) {
  var parts = path.split("\\").filter(function (p) {
        return p !== "";
      });
  var fileName = Core__Option.getOr(parts.pop(), "");
  var dirPath = parts.length === 0 ? "C:\\" : parts.join("\\");
  return [
          dirPath,
          fileName
        ];
}

function openNotepad(laptop, desktop, filePath, param) {
  var pid = LaptopState.openApp(laptop.state.processManager, "notepad.exe");
  var path = Core__Option.getOr(filePath, "C:\\Users\\Admin\\Documents\\notes.txt");
  var fileName = Core__Option.getOr((function (__x) {
            return __x[path.split("\\").length - 1 | 0];
          })(path.split("\\")), "Untitled");
  var content = DeviceView.readFile(laptop.state.ipAddress, path);
  var initialContent;
  initialContent = content.TAG === "Ok" ? content._0 : "";
  var setInputFocused = (function(focused) { window.__pixiui_input_focused = focused; });
  var win = make("Notepad - " + fileName, 380.0, 280.0, "Notepad", (function () {
          setInputFocused(false);
          LaptopState.closeApp(laptop.state.processManager, "notepad.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          win.container.destroy();
        }));
  win.container.x = 200.0;
  win.container.y = 150.0;
  var content$1 = win.content;
  var textBg = new PixiJs.Graphics();
  textBg.rect(5.0, 5.0, 360.0, 235.0).fill({
          color: 16777215
        }).stroke({
        width: 1,
        color: 13421772
      });
  textBg.eventMode = "static";
  textBg.cursor = "text";
  content$1.addChild(textBg);
  var inputBg = new PixiJs.Graphics();
  inputBg.rect(0.0, 0.0, 350.0, 225.0).fill({
        color: 16777215
      });
  var textInput = new Ui.Input({
        bg: inputBg,
        value: initialContent,
        textStyle: {
          fontSize: 11,
          fill: 0,
          fontFamily: "monospace",
          wordWrap: true,
          wordWrapWidth: 340
        },
        padding: 5
      });
  textInput.x = 10.0;
  textInput.y = 10.0;
  content$1.addChild(textInput);
  textInput.onChange.connect(function (newText) {
        DeviceView.writeFile(laptop.state.ipAddress, path, newText);
      });
  textInput.eventMode = "static";
  textInput.on("pointerdown", (function (param) {
          setInputFocused(true);
        }));
  desktop.addChild(win.container);
}

function openFileManager(laptop, desktop) {
  var pid = LaptopState.openApp(laptop.state.processManager, "explorer.exe");
  var win = make("File Manager - All Files", 420.0, 320.0, "File Manager", (function () {
          LaptopState.closeApp(laptop.state.processManager, "explorer.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          win.container.destroy();
        }));
  win.container.x = 150.0;
  win.container.y = 100.0;
  var content = win.content;
  var currentPath = {
    contents: "C:\\"
  };
  var headerText = new PixiJs.Text({
        text: "Files on " + laptop.state.hostname + " (" + laptop.state.ipAddress + ")",
        style: {
          fontSize: 11,
          fill: 0,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  headerText.x = 10.0;
  headerText.y = 10.0;
  content.addChild(headerText);
  var pathText = new PixiJs.Text({
        text: "Path: " + currentPath.contents,
        style: {
          fontSize: 10,
          fill: 6710886,
          fontFamily: "monospace"
        }
      });
  pathText.x = 10.0;
  pathText.y = 25.0;
  content.addChild(pathText);
  var fileList = new PixiJs.Container();
  fileList.y = 45.0;
  content.addChild(fileList);
  var renderDirectory = function () {
    fileList.removeChildren();
    var yOffset = {
      contents: 0.0
    };
    if (currentPath.contents !== "C:\\") {
      var item = new PixiJs.Container();
      item.y = yOffset.contents;
      item.eventMode = "static";
      item.cursor = "pointer";
      var itemBg = new PixiJs.Graphics();
      itemBg.rect(0.0, 0.0, 400.0, 20.0).fill({
            color: 16119285
          });
      item.addChild(itemBg);
      var itemText = new PixiJs.Text({
            text: "[DIR]  ..",
            style: {
              fontSize: 11,
              fill: 0,
              fontFamily: "monospace"
            }
          });
      itemText.x = 10.0;
      itemText.y = 3.0;
      item.addChild(itemText);
      item.on("pointertap", (function (param) {
              var parts = currentPath.contents.split("\\");
              var newParts = parts.slice(0, parts.length - 1 | 0);
              var newPath = newParts.length <= 1 ? "C:\\" : newParts.join("\\");
              currentPath.contents = newPath;
              pathText.text = "Path: " + currentPath.contents;
              renderDirectory();
            }));
      fileList.addChild(item);
      yOffset.contents = yOffset.contents + 22.0;
    }
    var items = DeviceView.listFiles(laptop.state.ipAddress, currentPath.contents);
    if (items !== undefined) {
      items.forEach(function (param) {
            var sizeMB = param[3];
            var isLocked = param[2];
            var isDir = param[1];
            var itemName = param[0];
            var itemContainer = new PixiJs.Container();
            itemContainer.y = yOffset.contents;
            itemContainer.eventMode = "static";
            itemContainer.cursor = "pointer";
            var itemBg = new PixiJs.Graphics();
            var bgColor = (yOffset.contents / 22.0 | 0) % 2 === 0 ? 16777215 : 16119285;
            itemBg.rect(0.0, 0.0, 400.0, 20.0).fill({
                  color: bgColor
                });
            itemContainer.addChild(itemBg);
            var prefix = isDir ? "[DIR]  " : "[FILE] ";
            var color = isLocked ? 16711680 : 0;
            var suffix = isLocked ? " [LOCKED]" : "";
            var sizeStr;
            if (sizeMB >= 1.0) {
              sizeStr = " (" + sizeMB.toFixed(1) + " MB)";
            } else if (sizeMB > 0.0) {
              var kb = sizeMB * 1024.0;
              sizeStr = " (" + kb.toFixed(0) + " KB)";
            } else {
              sizeStr = "";
            }
            var itemText = new PixiJs.Text({
                  text: prefix + itemName + suffix + sizeStr,
                  style: {
                    fontSize: 11,
                    fill: color,
                    fontFamily: "monospace"
                  }
                });
            itemText.x = 10.0;
            itemText.y = 3.0;
            itemContainer.addChild(itemText);
            itemContainer.on("pointertap", (function (param) {
                    if (isDir) {
                      var newPath = currentPath.contents === "C:\\" ? currentPath.contents + itemName : currentPath.contents + "\\" + itemName;
                      currentPath.contents = newPath;
                      pathText.text = "Path: " + currentPath.contents;
                      return renderDirectory();
                    }
                    if (isLocked) {
                      return ;
                    }
                    if (!(itemName.endsWith(".txt") || itemName.endsWith(".log") || itemName.endsWith(".conf") || itemName.endsWith(".key") || itemName.endsWith(".dat") || itemName.endsWith(".json") || itemName.endsWith(".env"))) {
                      return ;
                    }
                    var fullPath = currentPath.contents === "C:\\" ? currentPath.contents + itemName : currentPath.contents + "\\" + itemName;
                    openNotepad(laptop, desktop, fullPath, undefined);
                  }));
            fileList.addChild(itemContainer);
            yOffset.contents = yOffset.contents + 22.0;
          });
      return ;
    }
    
  };
  renderDirectory();
  desktop.addChild(win.container);
}

function getGlobalManager(prim) {
  return GlobalNetworkManagerResMjs.get();
}

var getDevicesFromManager = (function(manager) {
    return Object.values(manager.devices);
  });

function isReachableFromManager(prim0, prim1, prim2) {
  return NetworkManagerResMjs.isReachableFrom(prim0, prim1, prim2);
}

function openNetworkManager(laptop, desktop) {
  var pid = LaptopState.openApp(laptop.state.processManager, "netman.exe");
  var win = make("Network Topology", 700.0, 500.0, "Network Topology", (function () {
          LaptopState.closeApp(laptop.state.processManager, "netman.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          win.container.destroy();
        }));
  win.container.x = 100.0;
  win.container.y = 50.0;
  var content = win.content;
  var manager = GlobalNetworkManagerResMjs.get();
  var allDevices = getDevicesFromManager(manager);
  var sourceIp = laptop.state.ipAddress;
  var devices = allDevices.filter(function (device) {
        var info = device.getInfo();
        return NetworkManagerResMjs.isReachableFrom(manager, sourceIp, info.ipAddress);
      });
  var lanDevices = {
    contents: []
  };
  var ruralDevices = {
    contents: []
  };
  var dmzDevices = {
    contents: []
  };
  var internalDevices = {
    contents: []
  };
  var devDevices = {
    contents: []
  };
  var securityDevices = {
    contents: []
  };
  var managementDevices = {
    contents: []
  };
  var iotDevices = {
    contents: []
  };
  var scadaDevices = {
    contents: []
  };
  var atlasDevices = {
    contents: []
  };
  var nexusDevices = {
    contents: []
  };
  var devhubDevices = {
    contents: []
  };
  devices.forEach(function (device) {
        var info = device.getInfo();
        var ip = info.ipAddress;
        var name = info.name;
        var deviceType = info.deviceType;
        if (deviceType !== "Router") {
          if (ip.startsWith("192.168.1.")) {
            lanDevices.contents = lanDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("192.168.2.")) {
            ruralDevices.contents = ruralDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("10.0.0.")) {
            dmzDevices.contents = dmzDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("10.0.1.")) {
            internalDevices.contents = internalDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("10.0.2.")) {
            devDevices.contents = devDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("10.0.3.")) {
            securityDevices.contents = securityDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("172.16.0.")) {
            managementDevices.contents = managementDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("192.168.100.")) {
            iotDevices.contents = iotDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("10.10.1.")) {
            scadaDevices.contents = scadaDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("8.8.8.") || ip.startsWith("142.250.")) {
            atlasDevices.contents = atlasDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("1.1.1.") || ip.startsWith("104.16.")) {
            nexusDevices.contents = nexusDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else if (ip.startsWith("140.82.")) {
            devhubDevices.contents = devhubDevices.contents.concat([[
                    ip,
                    name,
                    deviceType
                  ]]);
            return ;
          } else {
            return ;
          }
        }
        
      });
  var connectionLayer = new PixiJs.Graphics();
  content.addChild(connectionLayer);
  var drawRouter = function (x, y, label, color) {
    var icon = new PixiJs.Graphics();
    icon.circle(0.0, 0.0, 8.0).fill({
            color: color
          }).stroke({
          color: 0,
          width: 1.5
        });
    icon.x = x;
    icon.y = y;
    content.addChild(icon);
    var text = new PixiJs.Text({
          text: label,
          style: {
            fontSize: 7,
            fill: 0,
            fontWeight: "bold",
            align: "center"
          }
        });
    text.x = x - 25.0;
    text.y = y + 10.0;
    content.addChild(text);
  };
  var drawConnection = function (x1, y1, x2, y2, color, width) {
    connectionLayer.moveTo(x1, y1).lineTo(x2, y2).stroke({
          color: color,
          width: width,
          alpha: 0.6
        });
  };
  drawRouter(80.0, 120.0, "Downtown\nRouter", 16750592);
  drawRouter(80.0, 280.0, "Rural\nRouter", 16750592);
  drawRouter(200.0, 80.0, "Business\nISP", 16776960);
  drawRouter(200.0, 240.0, "Rural\nISP", 16776960);
  drawRouter(300.0, 160.0, "Regional\nISP", 16750592);
  drawRouter(400.0, 160.0, "Internet\nBackbone", 16711680);
  drawRouter(550.0, 80.0, "Atlas", 4359668);
  drawRouter(550.0, 200.0, "Nexus", 15958048);
  drawRouter(550.0, 320.0, "DevHub", 6710886);
  drawConnection(80.0, 120.0, 200.0, 80.0, 16776960, 2.0);
  drawConnection(80.0, 280.0, 200.0, 240.0, 16776960, 2.0);
  drawConnection(200.0, 80.0, 300.0, 160.0, 16750592, 2.5);
  drawConnection(200.0, 240.0, 300.0, 160.0, 16750592, 2.5);
  drawConnection(300.0, 160.0, 400.0, 160.0, 16711680, 3.0);
  drawConnection(400.0, 160.0, 550.0, 80.0, 16777215, 2.0);
  drawConnection(400.0, 160.0, 550.0, 200.0, 16777215, 2.0);
  drawConnection(400.0, 160.0, 550.0, 320.0, 16777215, 2.0);
  var downtownDevices = lanDevices.contents.concat(dmzDevices.contents.concat(internalDevices.contents.concat(devDevices.contents.concat(securityDevices.contents.concat(managementDevices.contents.concat(iotDevices.contents.concat(scadaDevices.contents)))))));
  downtownDevices.forEach(function (param, i) {
        var angle = i * (6.28 / downtownDevices.length);
        var dx = 80.0 + 35.0 * Math.cos(angle);
        var dy = 120.0 + 35.0 * Math.sin(angle);
        var dot = new PixiJs.Graphics();
        dot.circle(0.0, 0.0, 2.0).fill({
              color: 5025616
            });
        dot.x = dx;
        dot.y = dy;
        content.addChild(dot);
        drawConnection(80.0, 120.0, dx, dy, 5025616, 1.0);
      });
  ruralDevices.contents.forEach(function (param, i) {
        var dx = 80.0 + 30.0;
        var dy = 280.0 + 25.0 + i * 12.0;
        var dot = new PixiJs.Graphics();
        dot.circle(0.0, 0.0, 2.0).fill({
              color: 5025616
            });
        dot.x = dx;
        dot.y = dy;
        content.addChild(dot);
        drawConnection(80.0, 280.0, dx, dy, 5025616, 1.0);
      });
  atlasDevices.contents.forEach(function (param, i) {
        var dx = 550.0 + 20.0;
        var dy = 80.0 - 10.0 + i * 12.0;
        var dot = new PixiJs.Graphics();
        dot.circle(0.0, 0.0, 2.0).fill({
              color: 4359668
            });
        dot.x = dx;
        dot.y = dy;
        content.addChild(dot);
        drawConnection(550.0, 80.0, dx, dy, 16777215, 1.0);
      });
  nexusDevices.contents.forEach(function (param, i) {
        var dx = 550.0 + 20.0;
        var dy = 200.0 - 10.0 + i * 12.0;
        var dot = new PixiJs.Graphics();
        dot.circle(0.0, 0.0, 2.0).fill({
              color: 15958048
            });
        dot.x = dx;
        dot.y = dy;
        content.addChild(dot);
        drawConnection(550.0, 200.0, dx, dy, 16777215, 1.0);
      });
  devhubDevices.contents.forEach(function (param, i) {
        var dx = 550.0 + 20.0;
        var dy = 320.0 - 10.0 + i * 12.0;
        var dot = new PixiJs.Graphics();
        dot.circle(0.0, 0.0, 2.0).fill({
              color: 6710886
            });
        dot.x = dx;
        dot.y = dy;
        content.addChild(dot);
        drawConnection(550.0, 320.0, dx, dy, 16777215, 1.0);
      });
  var legend = new PixiJs.Text({
        text: "Yellow=Tier3 Orange=Tier2 Red=Tier1 White=Services Green=LAN Blue=VLAN",
        style: {
          fontSize: 7,
          fill: 6710886
        }
      });
  legend.x = 10.0;
  legend.y = 470.0;
  content.addChild(legend);
  desktop.addChild(win.container);
}

var $$setInterval = (function(fn, ms) { return setInterval(fn, ms); });

var $$clearInterval = (function(id) { clearInterval(id); });

function openProcessExplorer(laptop, desktop) {
  var pid = LaptopState.openApp(laptop.state.processManager, "taskmgr.exe");
  var intervalId = {
    contents: 0
  };
  var win = make("Process Explorer", 480.0, 350.0, "Process Explorer", (function () {
          $$clearInterval(intervalId.contents);
          LaptopState.closeApp(laptop.state.processManager, "taskmgr.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          $$clearInterval(intervalId.contents);
          win.container.destroy();
        }));
  win.container.x = 160.0;
  win.container.y = 80.0;
  var content = win.content;
  var statsText = new PixiJs.Text({
        text: "",
        style: {
          fontSize: 11,
          fill: 26316,
          fontFamily: "monospace"
        }
      });
  statsText.x = 10.0;
  statsText.y = 10.0;
  content.addChild(statsText);
  var header = new PixiJs.Text({
        text: "PID    NAME                     CPU%     Gq",
        style: {
          fontSize: 11,
          fill: 0,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  header.x = 10.0;
  header.y = 35.0;
  content.addChild(header);
  var processList = new PixiJs.Container();
  processList.y = 55.0;
  content.addChild(processList);
  var renderProcesses = function () {
    var match = LaptopState.getTotalStorageUsage(laptop.state.processManager, laptop.state.ipAddress);
    var cpuUsage = LaptopState.getCpuUsage(laptop.state.processManager);
    statsText.text = "Storage: " + match[0].toString() + " Gq / " + match[1].toString() + " Gq   CPU: " + cpuUsage.toFixed(1) + "%";
    processList.removeChildren();
    var processes = LaptopState.getProcesses(laptop.state.processManager);
    processes.forEach(function (proc, i) {
          if (i >= 15) {
            return ;
          }
          var pidStr = proc.pid.toString().padStart(5, " ");
          var nameStr = proc.name.padEnd(24, " ");
          var cpuStr = proc.cpuPercent.toFixed(1).padStart(5, " ");
          var gqStr = proc.sizeGq.toString().padStart(6, " ");
          var color = proc.isSystem ? 6710886 : 0;
          var procText = new PixiJs.Text({
                text: pidStr + "  " + nameStr + " " + cpuStr + "%  " + gqStr,
                style: {
                  fontSize: 10,
                  fill: color,
                  fontFamily: "monospace"
                }
              });
          procText.x = 10.0;
          procText.y = i * 18.0;
          processList.addChild(procText);
        });
  };
  renderProcesses();
  intervalId.contents = $$setInterval(renderProcesses, 1000);
  desktop.addChild(win.container);
}

function openRecycleBin(laptop, desktop) {
  var pid = LaptopState.openApp(laptop.state.processManager, "recyclebin.exe");
  var win = make("Recycle Bin", 350.0, 200.0, "Recycle Bin", (function () {
          LaptopState.closeApp(laptop.state.processManager, "recyclebin.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          win.container.destroy();
        }));
  win.container.x = 220.0;
  win.container.y = 180.0;
  var content = win.content;
  var msg = new PixiJs.Text({
        text: "Recycle Bin is empty.",
        style: {
          fontSize: 12,
          fill: 6710886,
          fontStyle: "italic"
        }
      });
  msg.x = 10.0;
  msg.y = 50.0;
  content.addChild(msg);
  desktop.addChild(win.container);
}

var openRemoteDesktopRef = {
  contents: undefined
};

function openTerminal(laptop, desktop) {
  var pid = LaptopState.openApp(laptop.state.processManager, "cmd.exe");
  var win = make("Command Prompt", 500.0, 380.0, "Terminal", (function () {
          LaptopState.closeApp(laptop.state.processManager, "cmd.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, pid, (function () {
          win.container.destroy();
        }));
  win.container.x = 140.0;
  win.container.y = 60.0;
  var content = win.content;
  var terminal = Terminal.make(490.0, 345.0, laptop.state.hostname + "> ", laptop.state.ipAddress, laptop.state, undefined);
  content.addChild(terminal.container);
  desktop.addChild(win.container);
}

function createDesktopIcon(name, x, y, onOpen) {
  var icon = new PixiJs.Container();
  icon.x = x;
  icon.y = y;
  icon.eventMode = "static";
  icon.cursor = "pointer";
  var iconBg = new PixiJs.Graphics();
  iconBg.rect(0.0, 0.0, 60.0, 60.0).fill({
          color: 16777215
        }).stroke({
        width: 2,
        color: 0
      });
  icon.addChild(iconBg);
  var label = new PixiJs.Text({
        text: name,
        style: {
          fontSize: 10,
          fill: 16777215,
          align: "center",
          wordWrap: true,
          wordWrapWidth: 60
        }
      });
  label.anchor.set(0.5, 0.0);
  label.x = 30.0;
  label.y = 65.0;
  icon.addChild(label);
  icon.on("pointertap", (function (param) {
          onOpen();
        }));
  return icon;
}

function createRemoteDesktop(remoteState, width, height, param, param$1) {
  var container = new PixiJs.Container();
  container.sortableChildren = true;
  container.eventMode = "static";
  container.interactiveChildren = true;
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, height).fill({
        color: 1985912
      });
  container.addChild(bg);
  var innerDesktop = new PixiJs.Container();
  innerDesktop.sortableChildren = true;
  innerDesktop.eventMode = "static";
  innerDesktop.interactiveChildren = true;
  container.addChild(innerDesktop);
  var remoteLaptop = {
    container: container,
    desktop: innerDesktop,
    taskbar: new PixiJs.Graphics(),
    state: remoteState,
    currentPath: "C:\\Users\\Admin"
  };
  var filesIcon = createDesktopIcon("Files", 15.0, 15.0, (function () {
          openFileManager(remoteLaptop, innerDesktop);
        }));
  filesIcon.scale.set(0.8, 0.8);
  innerDesktop.addChild(filesIcon);
  var notepadIcon = createDesktopIcon("Notepad", 15.0, 15.0 + 70.0, (function () {
          openNotepad(remoteLaptop, innerDesktop, undefined, undefined);
        }));
  notepadIcon.scale.set(0.8, 0.8);
  innerDesktop.addChild(notepadIcon);
  var tasksIcon = createDesktopIcon("Tasks", 15.0, 15.0 + 70.0 * 2.0, (function () {
          openProcessExplorer(remoteLaptop, innerDesktop);
        }));
  tasksIcon.scale.set(0.8, 0.8);
  innerDesktop.addChild(tasksIcon);
  var terminalIcon = createDesktopIcon("Terminal", 15.0, 15.0 + 70.0 * 3.0, (function () {
          openTerminal(remoteLaptop, innerDesktop);
        }));
  terminalIcon.scale.set(0.8, 0.8);
  innerDesktop.addChild(terminalIcon);
  var rdpIcon = createDesktopIcon("RDP", 15.0 + 70.0, 15.0, (function () {
          openTerminal(remoteLaptop, innerDesktop);
        }));
  rdpIcon.scale.set(0.8, 0.8);
  innerDesktop.addChild(rdpIcon);
  var taskbar = new PixiJs.Graphics();
  taskbar.rect(0.0, height - 25.0, width, 25.0).fill({
        color: 657930
      });
  container.addChild(taskbar);
  var hostLabel = new PixiJs.Text({
        text: "[RDP] " + remoteState.hostname + " (" + remoteState.ipAddress + ")",
        style: {
          fontSize: 10,
          fill: 65280,
          fontFamily: "monospace"
        }
      });
  hostLabel.x = 5.0;
  hostLabel.y = height - 20.0;
  container.addChild(hostLabel);
  return container;
}

function openRemoteDesktop(laptop, desktop, remoteState, remoteHost) {
  var clientPid = LaptopState.openApp(laptop.state.processManager, "mstsc.exe");
  LaptopState.openApp(remoteState.processManager, "rdpserver.exe");
  var win = make("Remote Desktop - " + remoteState.hostname + " [" + remoteHost + "]", 520.0, 420.0, "Remote Desktop", (function () {
          LaptopState.closeApp(laptop.state.processManager, "mstsc.exe");
          LaptopState.closeApp(remoteState.processManager, "rdpserver.exe");
        }), undefined);
  LaptopState.registerWindowCloser(laptop.state.processManager, clientPid, (function () {
          LaptopState.closeApp(remoteState.processManager, "rdpserver.exe");
          win.container.destroy();
        }));
  win.container.x = 80.0;
  win.container.y = 40.0;
  var content = win.content;
  var remoteDesktopContainer = createRemoteDesktop(remoteState, 510.0, 380.0, desktop, laptop.state);
  content.addChild(remoteDesktopContainer);
  desktop.addChild(win.container);
}

openRemoteDesktopRef.contents = openRemoteDesktop;

function makeWithStateInternal(width, height, state, param) {
  var container = new PixiJs.Container();
  container.sortableChildren = true;
  container.eventMode = "static";
  container.interactiveChildren = true;
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, height).fill({
        color: 2840471
      });
  container.addChild(bg);
  var desktop = new PixiJs.Container();
  desktop.sortableChildren = true;
  desktop.eventMode = "static";
  desktop.interactiveChildren = true;
  container.addChild(desktop);
  var laptop = {
    container: container,
    desktop: desktop,
    taskbar: new PixiJs.Graphics(),
    state: state,
    currentPath: "C:\\Users\\Admin"
  };
  var togglePower = function () {
    var ip = state.ipAddress;
    var isShutdown = PowerManager.isDeviceShutdown(ip);
    if (isShutdown) {
      if (PowerManager.deviceHasPower(ip)) {
        return PowerManager.bootDevice(ip);
      } else {
        return ;
      }
    } else {
      return PowerManager.manualShutdownDevice(ip);
    }
  };
  var icons = [
    [
      "Recycle Bin",
      20.0,
      20.0,
      (function () {
          openRecycleBin(laptop, desktop);
        })
    ],
    [
      "File Manager",
      20.0,
      100.0,
      (function () {
          openFileManager(laptop, desktop);
        })
    ],
    [
      "Network",
      20.0,
      180.0,
      (function () {
          openNetworkManager(laptop, desktop);
        })
    ],
    [
      "Notepad",
      20.0,
      260.0,
      (function () {
          openNotepad(laptop, desktop, undefined, undefined);
        })
    ],
    [
      "Tasks",
      100.0,
      20.0,
      (function () {
          openProcessExplorer(laptop, desktop);
        })
    ],
    [
      "Terminal",
      100.0,
      100.0,
      (function () {
          openTerminal(laptop, desktop);
        })
    ],
    [
      "Power",
      100.0,
      180.0,
      togglePower
    ]
  ];
  icons.forEach(function (param) {
        var icon = createDesktopIcon(param[0], param[1], param[2], param[3]);
        desktop.addChild(icon);
      });
  var taskbar = new PixiJs.Graphics();
  taskbar.rect(0.0, height - 40.0, width, 40.0).fill({
        color: 1973790
      });
  container.addChild(taskbar);
  var startBtn = new PixiJs.Text({
        text: "START",
        style: {
          fontSize: 14,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  startBtn.x = 10.0;
  startBtn.y = height - 30.0;
  container.addChild(startBtn);
  return {
          container: laptop.container,
          desktop: laptop.desktop,
          taskbar: taskbar,
          state: laptop.state,
          currentPath: laptop.currentPath
        };
}

function makeWithState(width, height, state, param) {
  return makeWithStateInternal(width, height, state, undefined);
}

function make$1(width, height, ipAddressOpt, hostnameOpt, param) {
  var ipAddress = ipAddressOpt !== undefined ? ipAddressOpt : "192.168.1.102";
  var hostname = hostnameOpt !== undefined ? hostnameOpt : "WORKSTATION-PC";
  var state = LaptopState.createLaptopState(ipAddress, hostname, undefined, undefined);
  return makeWithStateInternal(width, height, state, undefined);
}

export {
  AppWindow ,
  splitPath ,
  openNotepad ,
  openFileManager ,
  getGlobalManager ,
  getDevicesFromManager ,
  isReachableFromManager ,
  openNetworkManager ,
  $$setInterval ,
  $$clearInterval ,
  openProcessExplorer ,
  openRecycleBin ,
  openRemoteDesktopRef ,
  openTerminal ,
  createDesktopIcon ,
  createRemoteDesktop ,
  openRemoteDesktop ,
  makeWithStateInternal ,
  makeWithState ,
  make$1 as make,
}
/*  Not a pure module */
