// Generated by ReScript, PLEASE EDIT WITH CARE


var allZones = [
  {
    id: "downtown-lan",
    name: "Downtown Corporate LAN",
    subnet: "192.168.1.",
    category: "LAN",
    color: 5025616,
    securityLevel: "Medium",
    description: "Corporate employee workstations and office equipment",
    canAccessZones: [
      "downtown-dmz",
      "downtown-internal",
      "downtown-dev",
      "downtown-iot",
      "downtown-mgmt",
      "isp-tier3-business",
      "public"
    ]
  },
  {
    id: "rural-lan",
    name: "Rural Home LAN",
    subnet: "192.168.2.",
    category: "LAN",
    color: 5025616,
    securityLevel: "Low",
    description: "Home network at rural outpost",
    canAccessZones: [
      "downtown-dmz",
      "isp-tier3-rural",
      "public"
    ]
  },
  {
    id: "downtown-dmz",
    name: "Downtown DMZ",
    subnet: "10.0.0.",
    category: "DMZ",
    color: 16750592,
    securityLevel: "High",
    description: "Public-facing services - mail, web, VPN",
    canAccessZones: [
      "downtown-internal",
      "downtown-security",
      "isp-tier3-business",
      "public"
    ]
  },
  {
    id: "downtown-internal",
    name: "Downtown Internal Apps",
    subnet: "10.0.1.",
    category: "Internal",
    color: 2201331,
    securityLevel: "High",
    description: "Protected business applications - database, intranet, file server",
    canAccessZones: [
      "downtown-dmz",
      "downtown-dev",
      "downtown-security",
      "downtown-mgmt"
    ]
  },
  {
    id: "downtown-dev",
    name: "Downtown Development",
    subnet: "10.0.2.",
    category: "Internal",
    color: 10233776,
    securityLevel: "Medium",
    description: "Development and testing environment",
    canAccessZones: [
      "downtown-internal",
      "downtown-security",
      "public"
    ]
  },
  {
    id: "downtown-security",
    name: "Downtown Security/Monitoring",
    subnet: "10.0.3.",
    category: "Internal",
    color: 16007990,
    securityLevel: "High",
    description: "IDS/IPS, SIEM, backup systems",
    canAccessZones: [
      "downtown-lan",
      "downtown-dmz",
      "downtown-internal",
      "downtown-dev",
      "downtown-iot",
      "downtown-mgmt",
      "downtown-scada"
    ]
  },
  {
    id: "downtown-iot",
    name: "Downtown IoT",
    subnet: "192.168.100.",
    category: "IoT",
    color: 15277667,
    securityLevel: "Low",
    description: "IoT devices - cameras, locks, sensors",
    canAccessZones: ["downtown-security"]
  },
  {
    id: "downtown-mgmt",
    name: "Downtown Management",
    subnet: "172.16.0.",
    category: "Management",
    color: 48340,
    securityLevel: "High",
    description: "Network management and administration tools",
    canAccessZones: [
      "downtown-lan",
      "downtown-dmz",
      "downtown-internal",
      "downtown-dev",
      "downtown-security",
      "downtown-iot",
      "downtown-scada"
    ]
  },
  {
    id: "downtown-scada",
    name: "Downtown SCADA",
    subnet: "10.10.1.",
    category: "SCADA",
    color: 16733986,
    securityLevel: "Critical",
    description: "Industrial control - power distribution, HVAC, physical access",
    canAccessZones: []
  },
  {
    id: "isp-tier3-rural",
    name: "Rural ISP (Tier 3)",
    subnet: "100.64.1.",
    category: "ISP",
    color: 16776960,
    securityLevel: "Medium",
    description: "Local ISP serving rural areas",
    canAccessZones: ["isp-tier2-regional"]
  },
  {
    id: "isp-tier3-business",
    name: "Business ISP (Tier 3)",
    subnet: "100.64.2.",
    category: "ISP",
    color: 16776960,
    securityLevel: "Medium",
    description: "Local ISP serving business customers",
    canAccessZones: ["isp-tier2-regional"]
  },
  {
    id: "isp-tier2-regional",
    name: "Regional ISP (Tier 2)",
    subnet: "198.51.100.",
    category: "ISP",
    color: 16750592,
    securityLevel: "High",
    description: "Regional ISP aggregating local providers",
    canAccessZones: ["isp-tier1-backbone"]
  },
  {
    id: "isp-tier1-backbone",
    name: "Internet Backbone (Tier 1)",
    subnet: "203.0.113.",
    category: "ISP",
    color: 16711680,
    securityLevel: "High",
    description: "Core internet routing infrastructure",
    canAccessZones: [
      "service-atlas",
      "service-nexus",
      "service-devhub"
    ]
  },
  {
    id: "service-atlas",
    name: "Atlas Network",
    subnet: "8.8.8.",
    category: "Service",
    color: 4359668,
    securityLevel: "High",
    description: "Atlas DNS and web services",
    canAccessZones: [
      "isp-tier1-backbone",
      "public"
    ]
  },
  {
    id: "service-nexus",
    name: "Nexus Network",
    subnet: "1.1.1.",
    category: "Service",
    color: 15958048,
    securityLevel: "High",
    description: "Nexus CDN and DNS services",
    canAccessZones: [
      "isp-tier1-backbone",
      "public"
    ]
  },
  {
    id: "service-devhub",
    name: "DevHub Network",
    subnet: "140.82.",
    category: "Service",
    color: 2369838,
    securityLevel: "High",
    description: "DevHub code repository",
    canAccessZones: [
      "isp-tier1-backbone",
      "public"
    ]
  },
  {
    id: "public",
    name: "Public Internet",
    subnet: "",
    category: "Service",
    color: 16777215,
    securityLevel: "Low",
    description: "General internet access",
    canAccessZones: []
  }
];

function getZoneByIp(ip) {
  if (ip.startsWith("142.250.")) {
    return allZones.find(function (zone) {
                return zone.id === "service-atlas";
              });
  } else if (ip.startsWith("104.16.")) {
    return allZones.find(function (zone) {
                return zone.id === "service-nexus";
              });
  } else {
    return allZones.find(function (zone) {
                if (zone.subnet !== "") {
                  return ip.startsWith(zone.subnet);
                } else {
                  return false;
                }
              });
  }
}

function getZoneById(id) {
  return allZones.find(function (zone) {
              return zone.id === id;
            });
}

function canZoneAccessZone(sourceZoneId, destZoneId) {
  if (sourceZoneId === destZoneId) {
    return true;
  }
  var sourceZone = getZoneById(sourceZoneId);
  if (sourceZone !== undefined) {
    return sourceZone.canAccessZones.includes(destZoneId);
  } else {
    return false;
  }
}

function canRouteViaISP(sourceZone, destZone) {
  if (destZone.category !== "Service") {
    if (destZone.category === "ISP") {
      if (sourceZone.canAccessZones.includes(destZone.id) || sourceZone.canAccessZones.includes("isp-tier3-business") || sourceZone.canAccessZones.includes("isp-tier3-rural")) {
        return true;
      } else {
        return sourceZone.canAccessZones.includes("public");
      }
    } else {
      return false;
    }
  }
  var canReachISP = sourceZone.canAccessZones.includes("isp-tier3-business") || sourceZone.canAccessZones.includes("isp-tier3-rural") || sourceZone.canAccessZones.includes("isp-tier2-regional") || sourceZone.canAccessZones.includes("isp-tier1-backbone");
  if (canReachISP) {
    return true;
  } else {
    return sourceZone.canAccessZones.includes("public");
  }
}

function canIpAccessIp(sourceIp, destIp) {
  if (sourceIp === destIp) {
    return true;
  }
  var sourceZone = getZoneByIp(sourceIp);
  var destZone = getZoneByIp(destIp);
  if (sourceZone !== undefined) {
    if (destZone !== undefined) {
      if (canZoneAccessZone(sourceZone.id, destZone.id)) {
        return true;
      } else {
        return canRouteViaISP(sourceZone, destZone);
      }
    } else if (sourceZone.canAccessZones.includes("public") || sourceZone.canAccessZones.includes("isp-tier3-business")) {
      return true;
    } else {
      return sourceZone.canAccessZones.includes("isp-tier3-rural");
    }
  } else {
    return false;
  }
}

function getZonesByCategory(category) {
  return allZones.filter(function (zone) {
              return zone.category === category;
            });
}

function getZoneColor(ip) {
  var zone = getZoneByIp(ip);
  if (zone !== undefined) {
    return zone.color;
  } else {
    return 6710886;
  }
}

function getZoneName(ip) {
  var zone = getZoneByIp(ip);
  if (zone !== undefined) {
    return zone.name;
  } else {
    return "Unknown Zone";
  }
}

function getAllZoneIds() {
  return allZones.map(function (zone) {
              return zone.id;
            });
}

export {
  allZones ,
  getZoneByIp ,
  getZoneById ,
  canZoneAccessZone ,
  canRouteViaISP ,
  canIpAccessIp ,
  getZonesByCategory ,
  getZoneColor ,
  getZoneName ,
  getAllZoneIds ,
}
/* No side effect */
