// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  PowerManager.setMainPowerStation(ipAddress);
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "PowerStation",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

function createPowerStationInterface(container, ipAddress) {
  var state = PowerManager.getPowerStationState(ipAddress);
  var headerStyle = {
    fontFamily: "monospace",
    fontSize: 16,
    fill: 16771899,
    fontWeight: "bold"
  };
  var header = new PixiJs.Text({
        text: "POWER STATION CONTROL",
        style: headerStyle
      });
  header.x = 20.0;
  header.y = 15.0;
  container.addChild(header);
  var statusBg = new PixiJs.Graphics();
  statusBg.rect(20.0, 50.0, 360.0, 120.0).fill({
          color: 1710618
        }).stroke({
        width: 2,
        color: 3355443
      });
  container.addChild(statusBg);
  var statusIndicator = new PixiJs.Graphics();
  statusIndicator.circle(50.0, 90.0, 20.0).fill({
        color: state.isOnline ? 65280 : 16711680
      });
  container.addChild(statusIndicator);
  var statusLabel = new PixiJs.Text({
        text: state.isOnline ? "ONLINE" : "OFFLINE",
        style: {
          fontSize: 18,
          fill: state.isOnline ? 65280 : 16711680,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  statusLabel.x = 85.0;
  statusLabel.y = 80.0;
  container.addChild(statusLabel);
  var outputLabel = new PixiJs.Text({
        text: "Output: " + state.outputPower.toString() + "W",
        style: {
          fontSize: 14,
          fill: 11184810,
          fontFamily: "monospace"
        }
      });
  outputLabel.x = 85.0;
  outputLabel.y = 110.0;
  container.addChild(outputLabel);
  var connectedUPS = PowerManager.getPowerStationConnectedUPS(ipAddress);
  var upsCountLabel = new PixiJs.Text({
        text: "Connected UPS Units: " + connectedUPS.length.toString(),
        style: {
          fontSize: 14,
          fill: 11184810,
          fontFamily: "monospace"
        }
      });
  upsCountLabel.x = 85.0;
  upsCountLabel.y = 135.0;
  container.addChild(upsCountLabel);
  var meterBg = new PixiJs.Graphics();
  meterBg.rect(20.0, 185.0, 360.0, 30.0).fill({
          color: 2236962
        }).stroke({
        width: 1,
        color: 4473924
      });
  container.addChild(meterBg);
  var meterFill = new PixiJs.Graphics();
  var fillWidth = state.isOnline ? 340.0 : 0.0;
  meterFill.rect(25.0, 190.0, fillWidth, 20.0).fill({
        color: 16771899
      });
  container.addChild(meterFill);
  var meterLabel = new PixiJs.Text({
        text: "POWER OUTPUT",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  meterLabel.x = 160.0;
  meterLabel.y = 220.0;
  container.addChild(meterLabel);
  var toggleBtn = new PixiJs.Graphics();
  toggleBtn.rect(20.0, 260.0, 150.0, 40.0).fill({
          color: state.isOnline ? 16729156 : 4521796
        }).stroke({
        width: 2,
        color: 0
      });
  toggleBtn.eventMode = "static";
  toggleBtn.cursor = "pointer";
  container.addChild(toggleBtn);
  var toggleText = new PixiJs.Text({
        text: state.isOnline ? "SHUTDOWN" : "START",
        style: {
          fontSize: 14,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  toggleText.anchor.set(0.5, 0.5);
  toggleText.x = 95.0;
  toggleText.y = 260.0 + 20.0;
  container.addChild(toggleText);
  toggleBtn.on("pointertap", (function (param) {
          var newState = !state.isOnline;
          PowerManager.setPowerStationOnline(ipAddress, newState);
          statusIndicator.clear();
          statusIndicator.circle(50.0, 90.0, 20.0).fill({
                color: newState ? 65280 : 16711680
              });
          statusLabel.text = newState ? "ONLINE" : "OFFLINE";
          meterFill.clear();
          var newFillWidth = newState ? 340.0 : 0.0;
          meterFill.rect(25.0, 190.0, newFillWidth, 20.0).fill({
                color: 16771899
              });
          toggleBtn.clear();
          toggleBtn.rect(20.0, 260.0, 150.0, 40.0).fill({
                  color: newState ? 16729156 : 4521796
                }).stroke({
                width: 2,
                color: 0
              });
          toggleText.text = newState ? "SHUTDOWN" : "START";
          PowerManager.notifyPowerChange();
        }));
  var warningLabel = new PixiJs.Text({
        text: "⚠ Shutting down will cut power to all non-UPS devices",
        style: {
          fontSize: 11,
          fill: 16746496,
          fontFamily: "monospace"
        }
      });
  warningLabel.x = 20.0;
  warningLabel.y = 315.0;
  container.addChild(warningLabel);
}

function openGUI(device) {
  var win = DeviceWindow.make("POWER STATION - " + device.name + " [" + device.ipAddress + "]", 400.0, 380.0, DeviceTypes.getDeviceColor("PowerStation"), 657930, undefined);
  createPowerStationInterface(DeviceWindow.getContent(win), device.ipAddress);
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  createPowerStationInterface ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
