// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";

var powerStationStates = {};

var upsStates = {};

var shutdownDevices = new Set();

var manuallyShutdownDevices = new Set();

var mainPowerStationIp = {
  contents: "192.168.1.250"
};

function getPowerStationState(ip) {
  var state = powerStationStates[ip];
  if (state !== undefined) {
    return state;
  }
  var state$1 = {
    isOnline: true,
    outputPower: 5000.0,
    connectedUPS: []
  };
  powerStationStates[ip] = state$1;
  return state$1;
}

function getUPSState(ip) {
  var state = upsStates[ip];
  if (state !== undefined) {
    return state;
  }
  var state$1 = {
    batteryLevel: 100.0,
    isCharging: true,
    connectedDevices: []
  };
  upsStates[ip] = state$1;
  return state$1;
}

function setMainPowerStation(ip) {
  mainPowerStationIp.contents = ip;
}

function connectUPSToPowerStation(upsIp, stationIp) {
  var station = getPowerStationState(stationIp);
  if (!station.connectedUPS.includes(upsIp)) {
    station.connectedUPS = station.connectedUPS.concat([upsIp]);
    return ;
  }
  
}

function connectDeviceToUPS(deviceIp, upsIp) {
  var ups = getUPSState(upsIp);
  if (!ups.connectedDevices.includes(deviceIp)) {
    ups.connectedDevices = ups.connectedDevices.concat([deviceIp]);
    return ;
  }
  
}

function isMainPowerOnline() {
  return getPowerStationState(mainPowerStationIp.contents).isOnline;
}

function setPowerStationOnline(ip, online) {
  var state = getPowerStationState(ip);
  state.isOnline = online;
  state.connectedUPS.forEach(function (upsIp) {
        var ups = getUPSState(upsIp);
        ups.isCharging = online;
      });
}

function getDevicePowerSource(deviceIp) {
  var connectedUps = Object.entries(upsStates).find(function (param) {
        return param[1].connectedDevices.includes(deviceIp);
      });
  if (connectedUps === undefined) {
    if (isMainPowerOnline()) {
      return "MainsPower";
    } else {
      return "NoPower";
    }
  }
  var ups = connectedUps[1];
  var upsIp = connectedUps[0];
  var connectedStation = Object.entries(powerStationStates).find(function (param) {
        return param[1].connectedUPS.includes(upsIp);
      });
  if (connectedStation !== undefined) {
    if (connectedStation[1].isOnline) {
      return "MainsPower";
    } else if (ups.batteryLevel > 0.0) {
      return "UPSBattery";
    } else {
      return "NoPower";
    }
  } else if (ups.batteryLevel > 0.0) {
    return "UPSBattery";
  } else {
    return "NoPower";
  }
}

function deviceHasPower(deviceIp) {
  return getDevicePowerSource(deviceIp) !== "NoPower";
}

function updateUPSBatteries(deltaSeconds) {
  Core__Dict.forEachWithKey(upsStates, (function (ups, _ip) {
          if (ups.isCharging) {
            var newLevel = ups.batteryLevel + deltaSeconds * (10.0 / 60.0);
            ups.batteryLevel = newLevel > 100.0 ? 100.0 : newLevel;
            return ;
          }
          var drainRate = ups.connectedDevices.length * (1.0 / 30.0);
          var newLevel$1 = ups.batteryLevel - deltaSeconds * drainRate;
          ups.batteryLevel = newLevel$1 < 0.0 ? 0.0 : newLevel$1;
        }));
}

function getUPSBatteryLevel(upsIp) {
  return getUPSState(upsIp).batteryLevel;
}

function isUPSCharging(upsIp) {
  return getUPSState(upsIp).isCharging;
}

function getUPSConnectedDevices(upsIp) {
  return getUPSState(upsIp).connectedDevices;
}

function getPowerStationConnectedUPS(stationIp) {
  return getPowerStationState(stationIp).connectedUPS;
}

var powerChangeCallbacks = {};

function registerPowerChangeCallback(deviceIp, callback) {
  powerChangeCallbacks[deviceIp] = callback;
}

function unregisterPowerChangeCallback(deviceIp) {
  Core__Dict.$$delete(powerChangeCallbacks, deviceIp);
}

function notifyPowerChange() {
  Core__Dict.forEachWithKey(powerChangeCallbacks, (function (callback, deviceIp) {
          callback(deviceHasPower(deviceIp));
        }));
}

function isDeviceShutdown(deviceIp) {
  return shutdownDevices.has(deviceIp);
}

function shutdownDevice(deviceIp) {
  shutdownDevices.add(deviceIp);
}

function manualShutdownDevice(deviceIp) {
  shutdownDevices.add(deviceIp);
  manuallyShutdownDevices.add(deviceIp);
}

function isManuallyShutdown(deviceIp) {
  return manuallyShutdownDevices.has(deviceIp);
}

function bootDevice(deviceIp) {
  shutdownDevices.delete(deviceIp);
  manuallyShutdownDevices.delete(deviceIp);
}

function isDeviceOperational(deviceIp) {
  if (deviceHasPower(deviceIp)) {
    return !shutdownDevices.has(deviceIp);
  } else {
    return false;
  }
}

function updateAllDevicePowerStates(allDeviceIps) {
  var changes = {
    contents: []
  };
  allDeviceIps.forEach(function (ip) {
        var hasPower = deviceHasPower(ip);
        var wasShutdown = shutdownDevices.has(ip);
        var wasManuallyShutdown = manuallyShutdownDevices.has(ip);
        if (!hasPower && !wasShutdown) {
          shutdownDevices.add(ip);
          changes.contents = changes.contents.concat([[
                  ip,
                  false,
                  true
                ]]);
          return ;
        } else if (hasPower && wasShutdown && !wasManuallyShutdown) {
          bootDevice(ip);
          changes.contents = changes.contents.concat([[
                  ip,
                  true,
                  false
                ]]);
          return ;
        } else {
          return ;
        }
      });
  return changes.contents;
}

export {
  powerStationStates ,
  upsStates ,
  shutdownDevices ,
  manuallyShutdownDevices ,
  mainPowerStationIp ,
  getPowerStationState ,
  getUPSState ,
  setMainPowerStation ,
  connectUPSToPowerStation ,
  connectDeviceToUPS ,
  isMainPowerOnline ,
  setPowerStationOnline ,
  getDevicePowerSource ,
  deviceHasPower ,
  updateUPSBatteries ,
  getUPSBatteryLevel ,
  isUPSCharging ,
  getUPSConnectedDevices ,
  getPowerStationConnectedUPS ,
  powerChangeCallbacks ,
  registerPowerChangeCallback ,
  unregisterPowerChangeCallback ,
  notifyPowerChange ,
  isDeviceShutdown ,
  shutdownDevice ,
  manualShutdownDevice ,
  isManuallyShutdown ,
  bootDevice ,
  isDeviceOperational ,
  updateAllDevicePowerStates ,
}
/* shutdownDevices Not a pure module */
