// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Ui from "@pixi/ui";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "Router",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

function createInputBg(widthOpt, param) {
  var width = widthOpt !== undefined ? widthOpt : 200.0;
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, 25.0).fill({
          color: 16777215
        }).stroke({
        width: 1,
        color: 0
      });
  return bg;
}

var globalNetworkManagerRef = {
  contents: undefined
};

function setGlobalNetworkManager(manager) {
  globalNetworkManagerRef.contents = manager;
}

function createRouterInterface(container, ipAddress) {
  var headerStyle = {
    fontFamily: "Arial",
    fontSize: 14,
    fill: 16777215,
    fontWeight: "bold"
  };
  var labelStyle = {
    fontFamily: "Arial",
    fontSize: 12,
    fill: 14540253
  };
  var header = new PixiJs.Text({
        text: "Router Configuration",
        style: headerStyle
      });
  header.x = 20.0;
  header.y = 15.0;
  container.addChild(header);
  var nm = globalNetworkManagerRef.contents;
  var currentDns = nm !== undefined ? nm.getConfiguredDns() : "8.8.8.8";
  var yPos = {
    contents: 50.0
  };
  var dnsLabel = new PixiJs.Text({
        text: "DNS Server:",
        style: labelStyle
      });
  dnsLabel.x = 20.0;
  dnsLabel.y = yPos.contents;
  container.addChild(dnsLabel);
  var dnsInput = new Ui.Input({
        bg: createInputBg(undefined, undefined),
        placeholder: "Enter DNS...",
        value: currentDns,
        textStyle: {
          fontSize: 11,
          fill: 0
        },
        padding: 5
      });
  dnsInput.x = 150.0;
  dnsInput.y = yPos.contents - 5.0;
  container.addChild(dnsInput);
  dnsInput.onEnter.connect(function (newDns) {
        var nm = globalNetworkManagerRef.contents;
        if (nm !== undefined) {
          return nm.setConfiguredDns(newDns);
        }
        
      });
  var dnsStatusRef = new PixiJs.Text({
        text: "",
        style: {
          fontSize: 9,
          fill: 65280
        }
      });
  dnsStatusRef.x = 360.0;
  dnsStatusRef.y = yPos.contents + 3.0;
  container.addChild(dnsStatusRef);
  var applyBtn = new PixiJs.Graphics();
  applyBtn.rect(360.0, yPos.contents - 5.0, 60.0, 25.0).fill({
          color: 30932
        }).stroke({
        width: 1,
        color: 23198
      });
  applyBtn.eventMode = "static";
  applyBtn.cursor = "pointer";
  container.addChild(applyBtn);
  var applyText = new PixiJs.Text({
        text: "Apply",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  applyText.x = 375.0;
  applyText.y = yPos.contents;
  applyBtn.addChild(applyText);
  applyBtn.on("pointertap", (function (param) {
          var newDns = dnsInput.value;
          var nm = globalNetworkManagerRef.contents;
          if (nm !== undefined) {
            return nm.setConfiguredDns(newDns);
          }
          
        }));
  yPos.contents = yPos.contents + 40.0;
  var dhcpLabel = new PixiJs.Text({
        text: "DHCP:",
        style: labelStyle
      });
  dhcpLabel.x = 20.0;
  dhcpLabel.y = yPos.contents;
  container.addChild(dhcpLabel);
  var dhcpBtn = new PixiJs.Graphics();
  dhcpBtn.rect(150.0, yPos.contents - 5.0, 80.0, 25.0).fill({
          color: 65280
        }).stroke({
        width: 1,
        color: 0
      });
  dhcpBtn.eventMode = "static";
  dhcpBtn.cursor = "pointer";
  container.addChild(dhcpBtn);
  var dhcpText = new PixiJs.Text({
        text: "ENABLED",
        style: {
          fontSize: 11,
          fill: 0,
          fontWeight: "bold"
        }
      });
  dhcpText.x = 158.0;
  dhcpText.y = yPos.contents;
  dhcpBtn.addChild(dhcpText);
  yPos.contents = yPos.contents + 45.0;
  var devHeader = new PixiJs.Text({
        text: "Connected Devices:",
        style: headerStyle
      });
  devHeader.x = 20.0;
  devHeader.y = yPos.contents;
  container.addChild(devHeader);
  yPos.contents = yPos.contents + 25.0;
  var colHeaders = new PixiJs.Text({
        text: "NAME                 IP ADDRESS        MAC ADDRESS",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  colHeaders.x = 20.0;
  colHeaders.y = yPos.contents;
  container.addChild(colHeaders);
  var nm$1 = globalNetworkManagerRef.contents;
  var devices = nm$1 !== undefined ? nm$1.getConnectedDevices() : [];
  yPos.contents = yPos.contents + 18.0;
  devices.forEach(function (param) {
        var nameStr = param[0].padEnd(20, " ");
        var ipStr = param[1].padEnd(18, " ");
        var devText = new PixiJs.Text({
              text: nameStr + ipStr + param[2],
              style: {
                fontSize: 10,
                fill: 11184810,
                fontFamily: "monospace"
              }
            });
        devText.x = 20.0;
        devText.y = yPos.contents;
        container.addChild(devText);
        yPos.contents = yPos.contents + 18.0;
      });
  if (devices.length === 0) {
    var noDevText = new PixiJs.Text({
          text: "(no devices connected)",
          style: {
            fontSize: 10,
            fill: 6710886,
            fontStyle: "italic"
          }
        });
    noDevText.x = 20.0;
    noDevText.y = yPos.contents;
    container.addChild(noDevText);
  }
  var powerBtn = new PixiJs.Graphics();
  var isShutdown = PowerManager.isDeviceShutdown(ipAddress);
  var powerBtnColor = isShutdown ? 43520 : 11141120;
  powerBtn.rect(350.0, 340.0, 100.0, 30.0).fill({
          color: powerBtnColor
        }).stroke({
        width: 1,
        color: 0
      });
  powerBtn.eventMode = "static";
  powerBtn.cursor = "pointer";
  container.addChild(powerBtn);
  var powerText = new PixiJs.Text({
        text: isShutdown ? "POWER ON" : "POWER OFF",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  powerText.anchor.set(0.5, 0.5);
  powerText.x = 400.0;
  powerText.y = 340.0 + 15.0;
  container.addChild(powerText);
  powerBtn.on("pointertap", (function (param) {
          var currentlyShutdown = PowerManager.isDeviceShutdown(ipAddress);
          if (currentlyShutdown) {
            if (PowerManager.deviceHasPower(ipAddress)) {
              PowerManager.bootDevice(ipAddress);
              powerText.text = "POWER OFF";
              powerBtn.clear();
              powerBtn.rect(350.0, 340.0, 100.0, 30.0).fill({
                      color: 11141120
                    }).stroke({
                    width: 1,
                    color: 0
                  });
              return ;
            } else {
              return ;
            }
          } else {
            PowerManager.manualShutdownDevice(ipAddress);
            powerText.text = "POWER ON";
            powerBtn.clear();
            powerBtn.rect(350.0, 340.0, 100.0, 30.0).fill({
                    color: 43520
                  }).stroke({
                  width: 1,
                  color: 0
                });
            return ;
          }
        }));
}

function openGUI(device) {
  var win = DeviceWindow.make("ROUTER - " + device.name + " [" + device.ipAddress + "]", 500.0, 400.0, DeviceTypes.getDeviceColor("Router"), 1710618, undefined);
  createRouterInterface(DeviceWindow.getContent(win), device.ipAddress);
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  createInputBg ,
  globalNetworkManagerRef ,
  setGlobalNetworkManager ,
  createRouterInterface ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
