// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Random from "../../engine/utils/Random.res.mjs";
import * as PixiJs from "pixi.js";
import * as Ui from "@pixi/ui";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";
import * as DeviceActivity from "./DeviceActivity.res.mjs";
import * as NetworkTransfer from "./NetworkTransfer.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

var $$setInterval = (function(fn, ms) { return setInterval(fn, ms); });

var $$clearInterval = (function(id) { clearInterval(id); });

var getCurrentTime = (function() { return Date.now(); });

var bootTimes = {};

function recordBoot(ip) {
  bootTimes[ip] = getCurrentTime();
}

function getUptime(ip) {
  var bootTime = bootTimes[ip];
  if (bootTime !== undefined) {
    return getCurrentTime() - bootTime;
  }
  
}

function initialize(ip) {
  var match = bootTimes[ip];
  if (match !== undefined) {
    return ;
  } else {
    return recordBoot(ip);
  }
}

var RouterUptime = {
  bootTimes: bootTimes,
  recordBoot: recordBoot,
  getUptime: getUptime,
  initialize: initialize
};

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "Router",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

function createInputBg(widthOpt, param) {
  var width = widthOpt !== undefined ? widthOpt : 200.0;
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, 25.0).fill({
          color: 16777215
        }).stroke({
        width: 1,
        color: 0
      });
  return bg;
}

var globalNetworkManagerRef = {
  contents: undefined
};

function setGlobalNetworkManager(manager) {
  globalNetworkManagerRef.contents = manager;
}

function createRouterInterface(container, ipAddress) {
  initialize(ipAddress);
  var headerStyle = {
    fontFamily: "Arial",
    fontSize: 14,
    fill: 16777215,
    fontWeight: "bold"
  };
  var labelStyle = {
    fontFamily: "Arial",
    fontSize: 12,
    fill: 14540253
  };
  var uploadSpeed = {
    contents: 500.0
  };
  var downloadSpeed = {
    contents: 1200.0
  };
  var statsBg = new PixiJs.Graphics();
  statsBg.rect(10.0, 10.0, 580.0, 50.0).fill({
          color: 2763306
        }).stroke({
        width: 1,
        color: 4473924
      });
  container.addChild(statsBg);
  var isOnline = !PowerManager.isDeviceShutdown(ipAddress);
  var statusDot = new PixiJs.Graphics();
  statusDot.circle(25.0, 10.0 + 15.0, 6.0).fill({
        color: isOnline ? 65280 : 6710886
      });
  container.addChild(statusDot);
  var statusLabel = new PixiJs.Text({
        text: "STATUS",
        style: {
          fontFamily: "Arial",
          fontSize: 10,
          fill: 14540253
        }
      });
  statusLabel.x = 40.0;
  statusLabel.y = 10.0 + 5.0;
  container.addChild(statusLabel);
  var statusText = new PixiJs.Text({
        text: isOnline ? "ONLINE" : "OFFLINE",
        style: {
          fontFamily: "monospace",
          fontSize: 14,
          fill: isOnline ? 65280 : 16711680
        }
      });
  statusText.x = 40.0;
  statusText.y = 10.0 + 20.0;
  container.addChild(statusText);
  var trafficLabel = new PixiJs.Text({
        text: "TRAFFIC",
        style: {
          fontFamily: "Arial",
          fontSize: 10,
          fill: 14540253
        }
      });
  trafficLabel.x = 230.0;
  trafficLabel.y = 10.0 + 5.0;
  container.addChild(trafficLabel);
  var trafficText = new PixiJs.Text({
        text: "↑500 KB/s ↓1.2 MB/s",
        style: {
          fontFamily: "monospace",
          fontSize: 14,
          fill: 43775
        }
      });
  trafficText.x = 230.0;
  trafficText.y = 10.0 + 20.0;
  container.addChild(trafficText);
  var uptimeLabel = new PixiJs.Text({
        text: "UPTIME",
        style: {
          fontFamily: "Arial",
          fontSize: 10,
          fill: 14540253
        }
      });
  uptimeLabel.x = 450.0;
  uptimeLabel.y = 10.0 + 5.0;
  container.addChild(uptimeLabel);
  var uptimeText = new PixiJs.Text({
        text: "0d 0h 0m",
        style: {
          fontFamily: "monospace",
          fontSize: 14,
          fill: 65280
        }
      });
  uptimeText.x = 450.0;
  uptimeText.y = 10.0 + 20.0;
  container.addChild(uptimeText);
  var nm = globalNetworkManagerRef.contents;
  var currentDns = nm !== undefined ? nm.getConfiguredDns() : "8.8.8.8";
  var configHeader = new PixiJs.Text({
        text: "CONFIGURATION",
        style: headerStyle
      });
  configHeader.x = 20.0;
  configHeader.y = 70.0;
  container.addChild(configHeader);
  var dnsY = 70.0 + 30.0;
  var dnsLabel = new PixiJs.Text({
        text: "DNS Server:",
        style: labelStyle
      });
  dnsLabel.x = 20.0;
  dnsLabel.y = dnsY;
  container.addChild(dnsLabel);
  var dnsInput = new Ui.Input({
        bg: createInputBg(undefined, undefined),
        placeholder: "Enter DNS...",
        value: currentDns,
        textStyle: {
          fontSize: 11,
          fill: 0
        },
        padding: 5
      });
  dnsInput.x = 130.0;
  dnsInput.y = dnsY - 5.0;
  container.addChild(dnsInput);
  dnsInput.onEnter.connect(function (newDns) {
        var nm = globalNetworkManagerRef.contents;
        if (nm !== undefined) {
          return nm.setConfiguredDns(newDns);
        }
        
      });
  var applyBtn = new PixiJs.Graphics();
  applyBtn.rect(340.0, dnsY - 5.0, 60.0, 25.0).fill({
          color: 30932
        }).stroke({
        width: 1,
        color: 23198
      });
  applyBtn.eventMode = "static";
  applyBtn.cursor = "pointer";
  container.addChild(applyBtn);
  var applyText = new PixiJs.Text({
        text: "Apply",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  applyText.x = 355.0;
  applyText.y = dnsY;
  applyBtn.addChild(applyText);
  applyBtn.on("pointertap", (function (param) {
          var newDns = dnsInput.value;
          var nm = globalNetworkManagerRef.contents;
          if (nm !== undefined) {
            return nm.setConfiguredDns(newDns);
          }
          
        }));
  var dhcpY = dnsY + 40.0;
  var dhcpLabel = new PixiJs.Text({
        text: "DHCP:",
        style: labelStyle
      });
  dhcpLabel.x = 20.0;
  dhcpLabel.y = dhcpY;
  container.addChild(dhcpLabel);
  var dhcpBtn = new PixiJs.Graphics();
  dhcpBtn.rect(130.0, dhcpY - 5.0, 80.0, 25.0).fill({
          color: 65280
        }).stroke({
        width: 1,
        color: 0
      });
  dhcpBtn.eventMode = "static";
  dhcpBtn.cursor = "pointer";
  container.addChild(dhcpBtn);
  var dhcpText = new PixiJs.Text({
        text: "ENABLED",
        style: {
          fontSize: 11,
          fill: 0,
          fontWeight: "bold"
        }
      });
  dhcpText.x = 138.0;
  dhcpText.y = dhcpY;
  dhcpBtn.addChild(dhcpText);
  var devHeader = new PixiJs.Text({
        text: "CONNECTED DEVICES",
        style: headerStyle
      });
  devHeader.x = 20.0;
  devHeader.y = 180.0;
  container.addChild(devHeader);
  var colHeaders = new PixiJs.Text({
        text: "  NAME                 IP ADDRESS        STATUS",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  colHeaders.x = 20.0;
  colHeaders.y = 180.0 + 22.0;
  container.addChild(colHeaders);
  var devicesContainer = new PixiJs.Container();
  devicesContainer.y = 180.0 + 40.0;
  container.addChild(devicesContainer);
  var routingHeader = new PixiJs.Text({
        text: "ROUTING TABLE",
        style: headerStyle
      });
  routingHeader.x = 20.0;
  routingHeader.y = 350.0;
  container.addChild(routingHeader);
  var routingColHeaders = new PixiJs.Text({
        text: "DESTINATION          GATEWAY            INTERFACE",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  routingColHeaders.x = 20.0;
  routingColHeaders.y = 350.0 + 22.0;
  container.addChild(routingColHeaders);
  var routes = [
    [
      "0.0.0.0/0",
      "10.0.0.1",
      "WAN"
    ],
    [
      "192.168.1.0/24",
      "0.0.0.0",
      "LAN"
    ],
    [
      "10.0.0.0/24",
      "0.0.0.0",
      "VLAN"
    ]
  ];
  var routingContainer = new PixiJs.Container();
  routingContainer.y = 350.0 + 40.0;
  container.addChild(routingContainer);
  routes.forEach(function (route, idx) {
        var destStr = route[0].padEnd(21, " ");
        var gatewayStr = route[1].padEnd(19, " ");
        var routeText = new PixiJs.Text({
              text: destStr + gatewayStr + route[2],
              style: {
                fontSize: 10,
                fill: 11184810,
                fontFamily: "monospace"
              }
            });
        routeText.x = 20.0;
        routeText.y = idx * 16.0;
        routingContainer.addChild(routeText);
      });
  var powerBtn = new PixiJs.Graphics();
  var isShutdown = PowerManager.isDeviceShutdown(ipAddress);
  var powerBtnColor = isShutdown ? 43520 : 11141120;
  powerBtn.rect(490.0, 460.0, 100.0, 30.0).fill({
          color: powerBtnColor
        }).stroke({
        width: 1,
        color: 0
      });
  powerBtn.eventMode = "static";
  powerBtn.cursor = "pointer";
  container.addChild(powerBtn);
  var powerText = new PixiJs.Text({
        text: isShutdown ? "POWER ON" : "POWER OFF",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  powerText.anchor.set(0.5, 0.5);
  powerText.x = 540.0;
  powerText.y = 460.0 + 15.0;
  container.addChild(powerText);
  powerBtn.on("pointertap", (function (param) {
          var currentlyShutdown = PowerManager.isDeviceShutdown(ipAddress);
          if (currentlyShutdown) {
            if (PowerManager.deviceHasPower(ipAddress)) {
              PowerManager.bootDevice(ipAddress);
              recordBoot(ipAddress);
              powerText.text = "POWER OFF";
              powerBtn.clear();
              powerBtn.rect(490.0, 460.0, 100.0, 30.0).fill({
                      color: 11141120
                    }).stroke({
                    width: 1,
                    color: 0
                  });
              return ;
            } else {
              return ;
            }
          } else {
            PowerManager.manualShutdownDevice(ipAddress);
            powerText.text = "POWER ON";
            powerBtn.clear();
            powerBtn.rect(490.0, 460.0, 100.0, 30.0).fill({
                    color: 43520
                  }).stroke({
                  width: 1,
                  color: 0
                });
            return ;
          }
        }));
  var updateStats = function () {
    var isOnline = !PowerManager.isDeviceShutdown(ipAddress);
    statusDot.clear();
    statusDot.circle(25.0, 10.0 + 15.0, 6.0).fill({
          color: isOnline ? 65280 : 6710886
        });
    statusText.text = isOnline ? "ONLINE" : "OFFLINE";
    var match = NetworkTransfer.getRouterTraffic(ipAddress);
    var noise = Random.$$float(undefined, 0.01, 0.05);
    uploadSpeed.contents = match[0] + noise;
    downloadSpeed.contents = match[1] + noise;
    var upStr = uploadSpeed.contents >= 1.0 ? "↑" + uploadSpeed.contents.toFixed(1) + " MB/s" : "↑" + (uploadSpeed.contents * 1024.0).toFixed(0) + " KB/s";
    var downStr = downloadSpeed.contents >= 1.0 ? "↓" + downloadSpeed.contents.toFixed(1) + " MB/s" : "↓" + (downloadSpeed.contents * 1024.0).toFixed(0) + " KB/s";
    trafficText.text = upStr + " " + downStr;
    var uptimeMs = getUptime(ipAddress);
    if (uptimeMs !== undefined) {
      var uptimeSeconds = uptimeMs / 1000.0;
      var days = uptimeSeconds / 86400.0 | 0;
      var hours = uptimeSeconds / 3600.0 % 24.0 | 0;
      var minutes = uptimeSeconds / 60.0 % 60.0 | 0;
      uptimeText.text = days.toString() + "d " + hours.toString() + "h " + minutes.toString() + "m";
      return ;
    }
    uptimeText.text = "0d 0h 0m";
  };
  var updateDeviceList = function () {
    devicesContainer.removeChildren();
    var nm = globalNetworkManagerRef.contents;
    var devices = nm !== undefined ? nm.getConnectedDevices() : [];
    if (devices.length === 0) {
      var noDevText = new PixiJs.Text({
            text: "(no devices connected)",
            style: {
              fontSize: 10,
              fill: 6710886,
              fontStyle: "italic"
            }
          });
      noDevText.x = 20.0;
      devicesContainer.addChild(noDevText);
      return ;
    }
    devices.forEach(function (param, idx) {
          var ip = param[1];
          var isActive = DeviceActivity.isActive(ip);
          var dot = new PixiJs.Graphics();
          dot.circle(0.0, 6.0, 4.0).fill({
                color: isActive ? 65280 : 6710886
              });
          dot.x = 20.0;
          dot.y = idx * 16.0;
          devicesContainer.addChild(dot);
          var nameStr = param[0].padEnd(20, " ");
          var ipStr = ip.padEnd(18, " ");
          var statusStr = isActive ? "ACTIVE" : "IDLE";
          var devText = new PixiJs.Text({
                text: "  " + nameStr + ipStr + statusStr,
                style: {
                  fontSize: 10,
                  fill: 11184810,
                  fontFamily: "monospace"
                }
              });
          devText.x = 20.0;
          devText.y = idx * 16.0;
          devicesContainer.addChild(devText);
        });
  };
  updateStats();
  updateDeviceList();
  var intervalId = $$setInterval((function () {
          updateStats();
          updateDeviceList();
        }), 2000);
  var cleanup = function () {
    $$clearInterval(intervalId);
  };
  return [
          cleanup,
          intervalId
        ];
}

function openGUI(device) {
  var win = DeviceWindow.make("ROUTER - " + device.name + " [" + device.ipAddress + "]", 600.0, 500.0, DeviceTypes.getDeviceColor("Router"), 1710618, undefined);
  var match = createRouterInterface(DeviceWindow.getContent(win), device.ipAddress);
  DeviceWindow.setOnClose(win, match[0]);
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  $$setInterval ,
  $$clearInterval ,
  getCurrentTime ,
  RouterUptime ,
  getInfo ,
  createInputBg ,
  globalNetworkManagerRef ,
  setGlobalNetworkManager ,
  createRouterInterface ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
