// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Terminal from "./Terminal.res.mjs";
import * as SystemLogs from "./SystemLogs.res.mjs";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as LaptopState from "./LaptopState.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "Server",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

function securityLevelToString(level) {
  switch (level) {
    case "Open" :
        return "OPEN";
    case "Weak" :
        return "WEAK";
    case "Medium" :
        return "MEDIUM";
    case "Strong" :
        return "STRONG";
    
  }
}

var $$setInterval = (function(fn, ms) { return setInterval(fn, ms); });

var $$clearInterval = (function(id) { clearInterval(id); });

var getCurrentTime = (function() { return Date.now(); });

var states = {};

function register(ip, state) {
  states[ip] = state;
  SystemLogs.initializeLogs(ip);
  state.bootTime = getCurrentTime();
}

function get(ip) {
  return states[ip];
}

var ServerStates = {
  states: states,
  register: register,
  get: get
};

function openGUI(device) {
  var win = DeviceWindow.make("SERVER - " + device.name + " [" + device.ipAddress + "] SEC:" + securityLevelToString(device.securityLevel), 600.0, 700.0, DeviceTypes.getDeviceColor("Server"), 0, undefined);
  var content = DeviceWindow.getContent(win);
  var s = states[device.ipAddress];
  var state;
  if (s !== undefined) {
    state = s;
  } else {
    var newState = LaptopState.createLaptopState(device.ipAddress, device.name, true, undefined);
    register(device.ipAddress, newState);
    state = newState;
  }
  var headerStyle = {
    fontFamily: "Arial",
    fontSize: 12,
    fill: 12289788,
    fontWeight: "bold"
  };
  var labelStyle = {
    fontFamily: "Arial",
    fontSize: 10,
    fill: 14540253
  };
  var statsBg = new PixiJs.Graphics();
  statsBg.rect(10.0, 10.0, 580.0, 40.0).fill({
          color: 2763306
        }).stroke({
        width: 1,
        color: 4473924
      });
  content.addChild(statsBg);
  var cpuLabel = new PixiJs.Text({
        text: "CPU",
        style: labelStyle
      });
  cpuLabel.x = 25.0;
  cpuLabel.y = 10.0 + 8.0;
  content.addChild(cpuLabel);
  var cpuText = new PixiJs.Text({
        text: "0.0%",
        style: {
          fontFamily: "monospace",
          fontSize: 16,
          fill: 65280
        }
      });
  cpuText.x = 25.0;
  cpuText.y = 10.0 + 20.0;
  content.addChild(cpuText);
  var storageLabel = new PixiJs.Text({
        text: "STORAGE",
        style: labelStyle
      });
  storageLabel.x = 230.0;
  storageLabel.y = 10.0 + 8.0;
  content.addChild(storageLabel);
  var storageText = new PixiJs.Text({
        text: "0/8192 Gq",
        style: {
          fontFamily: "monospace",
          fontSize: 16,
          fill: 65280
        }
      });
  storageText.x = 230.0;
  storageText.y = 10.0 + 20.0;
  content.addChild(storageText);
  var uptimeLabel = new PixiJs.Text({
        text: "UPTIME",
        style: labelStyle
      });
  uptimeLabel.x = 450.0;
  uptimeLabel.y = 10.0 + 8.0;
  content.addChild(uptimeLabel);
  var uptimeText = new PixiJs.Text({
        text: "0d 0h 0m",
        style: {
          fontFamily: "monospace",
          fontSize: 16,
          fill: 65280
        }
      });
  uptimeText.x = 450.0;
  uptimeText.y = 10.0 + 20.0;
  content.addChild(uptimeText);
  var processHeader = new PixiJs.Text({
        text: "RUNNING PROCESSES",
        style: headerStyle
      });
  processHeader.x = 10.0;
  processHeader.y = 60.0;
  content.addChild(processHeader);
  var procColHeaders = new PixiJs.Text({
        text: "PID     NAME                 CPU%    Gq",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  procColHeaders.x = 10.0;
  procColHeaders.y = 60.0 + 20.0;
  content.addChild(procColHeaders);
  var processContainer = new PixiJs.Container();
  processContainer.y = 60.0 + 38.0;
  content.addChild(processContainer);
  var networkHeader = new PixiJs.Text({
        text: "NETWORK CONNECTIONS",
        style: headerStyle
      });
  networkHeader.x = 10.0;
  networkHeader.y = 250.0;
  content.addChild(networkHeader);
  var networkColHeaders = new PixiJs.Text({
        text: "PROTO  LOCAL              REMOTE             STATE",
        style: {
          fontSize: 10,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  networkColHeaders.x = 10.0;
  networkColHeaders.y = 250.0 + 20.0;
  content.addChild(networkColHeaders);
  var connections = [
    [
      "TCP",
      device.ipAddress + ":22",
      "0.0.0.0:*",
      "LISTEN"
    ],
    [
      "TCP",
      device.ipAddress + ":80",
      "0.0.0.0:*",
      "LISTEN"
    ],
    [
      "TCP",
      device.ipAddress + ":3389",
      "0.0.0.0:*",
      "LISTEN"
    ]
  ];
  var networkContainer = new PixiJs.Container();
  networkContainer.y = 250.0 + 38.0;
  content.addChild(networkContainer);
  connections.forEach(function (param, idx) {
        var protoStr = param[0].padEnd(7, " ");
        var localStr = param[1].padEnd(19, " ");
        var remoteStr = param[2].padEnd(19, " ");
        var connText = new PixiJs.Text({
              text: protoStr + localStr + remoteStr + param[3],
              style: {
                fontSize: 10,
                fill: 11184810,
                fontFamily: "monospace"
              }
            });
        connText.x = 10.0;
        connText.y = idx * 16.0;
        networkContainer.addChild(connText);
      });
  var logHeader = new PixiJs.Text({
        text: "SYSTEM LOG",
        style: headerStyle
      });
  logHeader.x = 10.0;
  logHeader.y = 365.0;
  content.addChild(logHeader);
  var logContainer = new PixiJs.Container();
  logContainer.y = 365.0 + 20.0;
  content.addChild(logContainer);
  var terminalHeader = new PixiJs.Text({
        text: "TERMINAL",
        style: headerStyle
      });
  terminalHeader.x = 10.0;
  terminalHeader.y = 420.0;
  content.addChild(terminalHeader);
  var terminal = Terminal.make(580.0, 220.0, "root@" + device.name + ":~# ", device.ipAddress, state, undefined);
  terminal.container.y = 420.0 + 25.0;
  content.addChild(terminal.container);
  var powerBtn = new PixiJs.Graphics();
  var isShutdown = PowerManager.isDeviceShutdown(device.ipAddress);
  var powerBtnColor = isShutdown ? 43520 : 11141120;
  powerBtn.rect(490.0, 660.0, 100.0, 30.0).fill({
          color: powerBtnColor
        }).stroke({
        width: 1,
        color: 0
      });
  powerBtn.eventMode = "static";
  powerBtn.cursor = "pointer";
  content.addChild(powerBtn);
  var powerText = new PixiJs.Text({
        text: isShutdown ? "POWER ON" : "POWER OFF",
        style: {
          fontSize: 10,
          fill: 16777215,
          fontWeight: "bold"
        }
      });
  powerText.anchor.set(0.5, 0.5);
  powerText.x = 540.0;
  powerText.y = 660.0 + 15.0;
  content.addChild(powerText);
  powerBtn.on("pointertap", (function (param) {
          var currentlyShutdown = PowerManager.isDeviceShutdown(device.ipAddress);
          if (currentlyShutdown) {
            if (PowerManager.deviceHasPower(device.ipAddress)) {
              PowerManager.bootDevice(device.ipAddress);
              state.bootTime = getCurrentTime();
              SystemLogs.addLog(device.ipAddress, "System booted", "Info");
              powerText.text = "POWER OFF";
              powerBtn.clear();
              powerBtn.rect(490.0, 660.0, 100.0, 30.0).fill({
                      color: 11141120
                    }).stroke({
                    width: 1,
                    color: 0
                  });
              return ;
            } else {
              return ;
            }
          } else {
            PowerManager.manualShutdownDevice(device.ipAddress);
            SystemLogs.addLog(device.ipAddress, "System shutdown", "Warning");
            powerText.text = "POWER ON";
            powerBtn.clear();
            powerBtn.rect(490.0, 660.0, 100.0, 30.0).fill({
                    color: 43520
                  }).stroke({
                  width: 1,
                  color: 0
                });
            return ;
          }
        }));
  var updateStats = function () {
    var cpu = LaptopState.getCpuUsage(state.processManager);
    cpuText.text = cpu.toFixed(1) + "%";
    var match = LaptopState.getTotalStorageUsage(state.processManager, state.ipAddress);
    storageText.text = match[0].toString() + "/" + match[1].toString() + " Gq";
    var uptimeMs = getCurrentTime() - state.bootTime;
    var uptimeSeconds = uptimeMs / 1000.0;
    var days = uptimeSeconds / 86400.0 | 0;
    var hours = uptimeSeconds / 3600.0 % 24.0 | 0;
    var minutes = uptimeSeconds / 60.0 % 60.0 | 0;
    uptimeText.text = days.toString() + "d " + hours.toString() + "h " + minutes.toString() + "m";
  };
  var updateProcesses = function () {
    LaptopState.syncServicesWithProcesses(state.processManager, state.ipAddress);
    processContainer.removeChildren();
    var processes = LaptopState.getProcesses(state.processManager);
    var sortedProcs = processes.toSorted(function (a, b) {
          if (a.cpuPercent > b.cpuPercent) {
            return -1.0;
          } else if (a.cpuPercent < b.cpuPercent) {
            return 1.0;
          } else {
            return 0.0;
          }
        });
    var displayProcs = sortedProcs.slice(0, 8);
    displayProcs.forEach(function (proc, idx) {
          var pidStr = proc.pid.toString().padEnd(8, " ");
          var nameStr = proc.name.padEnd(21, " ");
          var cpuStr = proc.cpuPercent.toFixed(1).padStart(6, " ");
          var sizeStr = proc.sizeGq.toString().padStart(4, " ");
          var procText = new PixiJs.Text({
                text: pidStr + nameStr + cpuStr + "  " + sizeStr,
                style: {
                  fontSize: 10,
                  fill: 11184810,
                  fontFamily: "monospace"
                }
              });
          procText.x = 10.0;
          procText.y = idx * 16.0;
          processContainer.addChild(procText);
        });
  };
  var updateLogs = function () {
    logContainer.removeChildren();
    var logs = SystemLogs.getLogs(device.ipAddress, 3);
    logs.forEach(function (log, idx) {
          var match = log.level;
          var levelColor = match === "Error" ? 16711680 : (
              match === "Info" ? 65280 : 16755200
            );
          var logText = new PixiJs.Text({
                text: "[" + log.timestamp + "] " + log.message,
                style: {
                  fontSize: 10,
                  fill: levelColor,
                  fontFamily: "monospace"
                }
              });
          logText.x = 10.0;
          logText.y = idx * 16.0;
          logContainer.addChild(logText);
        });
  };
  updateStats();
  updateProcesses();
  updateLogs();
  var intervalId = $$setInterval((function () {
          updateStats();
          updateProcesses();
          updateLogs();
        }), 1000);
  DeviceWindow.setOnClose(win, (function () {
          $$clearInterval(intervalId);
        }));
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  securityLevelToString ,
  $$setInterval ,
  $$clearInterval ,
  getCurrentTime ,
  ServerStates ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
