// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Terminal from "./Terminal.res.mjs";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";

function make(name, ipAddress, securityLevel, param) {
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "Server",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

function securityLevelToString(level) {
  switch (level) {
    case "Open" :
        return "OPEN";
    case "Weak" :
        return "WEAK";
    case "Medium" :
        return "MEDIUM";
    case "Strong" :
        return "STRONG";
    
  }
}

function openGUI(device) {
  var win = DeviceWindow.make("SERVER - " + device.name + " [" + device.ipAddress + "] SEC:" + securityLevelToString(device.securityLevel), 500.0, 400.0, DeviceTypes.getDeviceColor("Server"), 0, undefined);
  var terminal = Terminal.make(490.0, 360.0, "root@server:~# ", device.ipAddress, undefined);
  DeviceWindow.getContent(win).addChild(terminal.container);
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  securityLevelToString ,
  openGUI ,
  toDevice ,
}
/* Terminal Not a pure module */
