// Generated by ReScript, PLEASE EDIT WITH CARE


var getCurrentTime = (function() { return Date.now(); });

var logs = {};

function formatTime() {
  ((new Date()));
  var hours = (date.getHours().toString().padStart(2, '0'));
  var minutes = (date.getMinutes().toString().padStart(2, '0'));
  return hours + ":" + minutes;
}

function addLog(ip, message, level) {
  var entry_timestamp = formatTime();
  var entry = {
    timestamp: entry_timestamp,
    message: message,
    level: level
  };
  var l = logs[ip];
  var currentLogs = l !== undefined ? l : [];
  var newLogs = currentLogs.concat([entry]);
  var trimmedLogs = newLogs.length > 50 ? newLogs.slice(newLogs.length - 50 | 0, newLogs.length) : newLogs;
  logs[ip] = trimmedLogs;
}

function getLogs(ip, limit) {
  var l = logs[ip];
  if (l === undefined) {
    return [];
  }
  var len = l.length;
  if (len <= limit) {
    return l;
  } else {
    return l.slice(len - limit | 0, len);
  }
}

function initializeLogs(ip) {
  addLog(ip, "System initialized", "Info");
  addLog(ip, "Network services started", "Info");
  addLog(ip, "Security monitor active", "Info");
}

var maxLogs = 50;

export {
  getCurrentTime ,
  logs ,
  maxLogs ,
  formatTime ,
  addLog ,
  getLogs ,
  initializeLogs ,
}
/* No side effect */
