// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

function createFilesystem() {
  return {
          TAG: "Dir",
          contents: Object.fromEntries([
                [
                  "home",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "user",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([
                                    [
                                      "documents",
                                      {
                                        TAG: "Dir",
                                        contents: Object.fromEntries([
                                              [
                                                "passwords.txt",
                                                {
                                                  TAG: "File",
                                                  content: "admin:P@ssw0rd123\nroot:toor\ndbuser:mysql_secure_2024",
                                                  locked: true
                                                }
                                              ],
                                              [
                                                "notes.txt",
                                                {
                                                  TAG: "File",
                                                  content: "Meeting at 3pm\nRemember to update firewall rules",
                                                  locked: false
                                                }
                                              ]
                                            ])
                                      }
                                    ],
                                    [
                                      "downloads",
                                      {
                                        TAG: "Dir",
                                        contents: {}
                                      }
                                    ]
                                  ])
                            }
                          ]])
                  }
                ],
                [
                  "sys",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "config",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([[
                                      "network.conf",
                                      {
                                        TAG: "File",
                                        content: "DHCP=enabled\nDNS=8.8.8.8",
                                        locked: true
                                      }
                                    ]])
                            }
                          ]])
                  }
                ],
                [
                  "var",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "log",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([[
                                      "access.log",
                                      {
                                        TAG: "File",
                                        content: "[2024-12-06 10:23] User login: admin\n[2024-12-06 10:45] Failed login attempt: user",
                                        locked: false
                                      }
                                    ]])
                            }
                          ]])
                  }
                ]
              ])
        };
}

function resolvePath(terminal, path) {
  if (path === "/") {
    return terminal.filesystem;
  }
  var parts;
  if (path.startsWith("/")) {
    parts = path.slice(1).split("/").filter(function (p) {
          return p !== "";
        });
  } else {
    var currentPath = terminal.currentDirectory.slice(1);
    parts = (currentPath + "/" + path).split("/").filter(function (p) {
          return p !== "";
        });
  }
  var current = {
    contents: terminal.filesystem
  };
  var found = {
    contents: true
  };
  parts.forEach(function (part) {
        if (!(found.contents && part !== "..")) {
          return ;
        }
        var match = current.contents;
        if (match.TAG !== "Dir") {
          found.contents = false;
          return ;
        }
        var node = match.contents[part];
        if (node !== undefined) {
          current.contents = node;
        } else {
          found.contents = false;
        }
      });
  if (found.contents) {
    return current.contents;
  }
  
}

function addOutput(terminal, text) {
  var monoStyle = {
    fontFamily: "monospace",
    fontSize: 11,
    fill: 65280
  };
  var lines = text.split("\n");
  lines.forEach(function (line) {
        var textObj = new PixiJs.Text({
              text: line,
              style: monoStyle
            });
        textObj.x = 10.0;
        textObj.y = 10.0 + terminal.outputLines.length * terminal.lineHeight;
        terminal.container.addChild(textObj);
        terminal.outputLines = terminal.outputLines.concat([textObj]);
      });
  while(terminal.outputLines.length > terminal.maxLines) {
    var oldLine = terminal.outputLines[0];
    if (oldLine !== undefined) {
      Caml_option.valFromOption(oldLine).destroy();
      terminal.outputLines = terminal.outputLines.slice(1);
    }
    
  };
  terminal.outputLines.forEach(function (line, i) {
        line.y = 10.0 + i * terminal.lineHeight;
      });
}

function updateInputLine(terminal) {
  var cursor = terminal.showCursor ? "_" : " ";
  terminal.inputLine.text = terminal.currentDirectory + terminal.prompt + terminal.currentInput + cursor;
}

function listDirectory(terminal, path) {
  var match = resolvePath(terminal, path);
  if (match === undefined) {
    return "ls: cannot access '" + path + "': No such file or directory";
  }
  if (match.TAG !== "Dir") {
    return "ls: " + path + ": Not a directory";
  }
  var contents = match.contents;
  var items = Object.keys(contents).map(function (name) {
        var match = contents[name];
        if (match === undefined) {
          return "";
        }
        if (match.TAG === "Dir") {
          return "[DIR] " + name;
        }
        var lock = match.locked ? " [LOCKED]" : "";
        return "[FILE] " + name + lock;
      });
  if (items.length === 0) {
    return "(empty directory)";
  } else {
    return items.join("\n");
  }
}

function changeDirectory(terminal, path) {
  if (path === "..") {
    var parts = terminal.currentDirectory.split("/").filter(function (p) {
          return p !== "";
        });
    parts.pop();
    terminal.currentDirectory = "/" + parts.join("/");
    if (terminal.currentDirectory === "/") {
      terminal.currentDirectory = "/";
    }
    return "";
  }
  var match = resolvePath(terminal, path);
  if (match === undefined) {
    return "cd: " + path + ": No such file or directory";
  }
  if (match.TAG !== "Dir") {
    return "cd: " + path + ": Not a directory";
  }
  terminal.currentDirectory = path.startsWith("/") ? path : terminal.currentDirectory + "/" + path;
  if (!terminal.currentDirectory.startsWith("/")) {
    terminal.currentDirectory = "/" + terminal.currentDirectory;
  }
  return "";
}

function readFile(terminal, path) {
  var match = resolvePath(terminal, path);
  if (match === undefined) {
    return "cat: " + path + ": No such file or directory";
  }
  if (match.TAG === "Dir") {
    return "cat: " + path + ": Is a directory";
  }
  if (match.locked) {
    return "cat: " + path + ": Permission denied";
  }
  var content = match.content;
  if (content === "") {
    return "(empty file)";
  } else {
    return content;
  }
}

function handleBuiltInCommand(terminal, cmd, args) {
  switch (cmd) {
    case "cat" :
        var path = args[0];
        if (path !== undefined) {
          return readFile(terminal, path);
        } else {
          return "cat: missing file operand";
        }
    case "cd" :
        var path$1 = Core__Option.getOr(args[0], "/");
        return changeDirectory(terminal, path$1);
    case "clear" :
        terminal.outputLines.forEach(function (line) {
              line.destroy();
            });
        terminal.outputLines = [];
        return "";
    case "cp" :
        return "cp: operation not yet implemented";
    case "help" :
        return "Available commands:\n  ls [path]       - List directory contents\n  cd <path>       - Change directory\n  cat <file>      - Display file contents\n  pwd             - Print working directory\n  mkdir <name>    - Create directory\n  rm <file>       - Remove file\n  cp <src> <dst>  - Copy file\n  clear           - Clear terminal\n  shutdown        - Shutdown this device\n  reboot          - Reboot this device\n  help            - Show this help";
    case "ls" :
        var path$2 = Core__Option.getOr(args[0], terminal.currentDirectory);
        return listDirectory(terminal, path$2);
    case "mkdir" :
        return "mkdir: operation not yet implemented";
    case "pwd" :
        return terminal.currentDirectory;
    case "reboot" :
        var ip = terminal.ipAddress;
        if (ip === undefined) {
          return "reboot: cannot determine device IP";
        }
        var wasShutdown = PowerManager.isDeviceShutdown(ip);
        if (wasShutdown) {
          if (PowerManager.deviceHasPower(ip)) {
            PowerManager.bootDevice(ip);
            return "System is rebooting...";
          } else {
            return "reboot: no power available";
          }
        } else {
          PowerManager.manualShutdownDevice(ip);
          if (PowerManager.deviceHasPower(ip)) {
            PowerManager.bootDevice(ip);
            return "System is rebooting...";
          } else {
            return "reboot: no power available after shutdown";
          }
        }
    case "rm" :
        return "rm: operation requires elevated privileges";
    case "shutdown" :
        var ip$1 = terminal.ipAddress;
        if (ip$1 !== undefined) {
          PowerManager.manualShutdownDevice(ip$1);
          return "System is shutting down...";
        } else {
          return "shutdown: cannot determine device IP";
        }
    default:
      return "bash: " + cmd + ": command not found";
  }
}

function executeCommand(terminal) {
  var fullCommand = terminal.currentInput.trim();
  if (fullCommand === "") {
    addOutput(terminal, "");
    terminal.currentInput = "";
    return updateInputLine(terminal);
  }
  addOutput(terminal, terminal.currentDirectory + terminal.prompt + fullCommand);
  var parts = fullCommand.split(" ").filter(function (p) {
        return p !== "";
      });
  var cmd = Core__Option.getOr(parts[0], "");
  var args = parts.slice(1);
  var output = handleBuiltInCommand(terminal, cmd, args);
  if (output !== "") {
    addOutput(terminal, output);
  }
  terminal.commandHistory = terminal.commandHistory.concat([fullCommand]);
  terminal.currentInput = "";
  updateInputLine(terminal);
}

var setGlobalFocusedTerminal = (function(terminal) {
    window.__focusedTerminal = terminal;
  });

var getGlobalFocusedTerminal = (function() {
    return window.__focusedTerminal || undefined;
  });

function handleKeyInput(terminal, key) {
  if (key === "Enter") {
    return executeCommand(terminal);
  } else if (key === "Backspace") {
    terminal.currentInput = terminal.currentInput.slice(0, terminal.currentInput.length - 1 | 0);
    return updateInputLine(terminal);
  } else if (key.length === 1) {
    terminal.currentInput = terminal.currentInput + key;
    return updateInputLine(terminal);
  } else {
    return ;
  }
}

var setupGlobalKeyboardHandler = (function(getFocused, handleKey) {
    if (!window.__terminalKeyboardSetup) {
      window.__terminalKeyboardSetup = true;
      console.log('[Terminal] Setting up global keyboard handler');
      window.addEventListener('keydown', (e) => {
        const focused = getFocused();
        // PixiJS v8 uses 'visible' property, check if container exists and is visible
        const isVisible = focused?.container?.visible !== false;
        if (!focused || !isVisible) return;

        // Only prevent default for our terminal keys
        if (e.key === 'Enter' || e.key === 'Backspace' || (e.key.length === 1 && !e.ctrlKey && !e.metaKey)) {
          e.preventDefault();
          handleKey(focused, e.key);
        }
      });
    }
  });

var logFocus = (function(msg) { console.log('[Terminal]', msg); });

function focus(terminal) {
  logFocus("Focusing terminal");
  setGlobalFocusedTerminal(terminal);
  terminal.bg.alpha = 1.0;
}

function unfocus(terminal) {
  var focused = getGlobalFocusedTerminal();
  if (focused !== undefined && focused === terminal) {
    setGlobalFocusedTerminal(undefined);
    terminal.bg.alpha = 0.9;
    return ;
  }
  
}

function make(width, height, promptOpt, ipAddress, param) {
  var prompt = promptOpt !== undefined ? promptOpt : "> ";
  var container = new PixiJs.Container();
  container.eventMode = "static";
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, height).fill(0);
  bg.eventMode = "static";
  bg.cursor = "text";
  container.addChild(bg);
  var monoStyle = {
    fontFamily: "monospace",
    fontSize: 11,
    fill: 65280
  };
  var inputLine = new PixiJs.Text({
        text: prompt,
        style: monoStyle
      });
  inputLine.x = 10.0;
  inputLine.y = height - 25.0;
  container.addChild(inputLine);
  var terminal = {
    container: container,
    bg: bg,
    outputLines: [],
    commandHistory: [],
    currentDirectory: "/",
    currentInput: "",
    showCursor: true,
    cursorBlink: 0.0,
    inputLine: inputLine,
    prompt: prompt,
    width: width,
    height: height,
    maxLines: 20,
    lineHeight: 16.0,
    filesystem: createFilesystem(),
    ipAddress: ipAddress
  };
  addOutput(terminal, "Terminal initialized. Type 'help' for commands.");
  addOutput(terminal, "");
  bg.on("pointerdown", (function (param) {
          focus(terminal);
        }));
  setupGlobalKeyboardHandler(getGlobalFocusedTerminal, handleKeyInput);
  return terminal;
}

function update(terminal, deltaTime) {
  terminal.cursorBlink = terminal.cursorBlink + deltaTime;
  if (terminal.cursorBlink > 0.5) {
    terminal.showCursor = !terminal.showCursor;
    terminal.cursorBlink = 0.0;
    return updateInputLine(terminal);
  }
  
}

export {
  createFilesystem ,
  resolvePath ,
  addOutput ,
  updateInputLine ,
  listDirectory ,
  changeDirectory ,
  readFile ,
  handleBuiltInCommand ,
  executeCommand ,
  setGlobalFocusedTerminal ,
  getGlobalFocusedTerminal ,
  handleKeyInput ,
  setupGlobalKeyboardHandler ,
  logFocus ,
  focus ,
  unfocus ,
  make ,
  update ,
}
/* pixi.js Not a pure module */
