// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as DeviceView from "./DeviceView.res.mjs";
import * as SystemLogs from "./SystemLogs.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LaptopState from "./LaptopState.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";
import * as DeviceActivity from "./DeviceActivity.res.mjs";

function createFilesystem() {
  return {
          TAG: "Dir",
          contents: Object.fromEntries([
                [
                  "home",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "user",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([
                                    [
                                      "documents",
                                      {
                                        TAG: "Dir",
                                        contents: Object.fromEntries([
                                              [
                                                "passwords.txt",
                                                {
                                                  TAG: "File",
                                                  content: "admin:P@ssw0rd123\nroot:toor\ndbuser:mysql_secure_2024",
                                                  locked: true
                                                }
                                              ],
                                              [
                                                "notes.txt",
                                                {
                                                  TAG: "File",
                                                  content: "Meeting at 3pm\nRemember to update firewall rules",
                                                  locked: false
                                                }
                                              ]
                                            ])
                                      }
                                    ],
                                    [
                                      "downloads",
                                      {
                                        TAG: "Dir",
                                        contents: {}
                                      }
                                    ]
                                  ])
                            }
                          ]])
                  }
                ],
                [
                  "sys",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "config",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([[
                                      "network.conf",
                                      {
                                        TAG: "File",
                                        content: "DHCP=enabled\nDNS=8.8.8.8",
                                        locked: true
                                      }
                                    ]])
                            }
                          ]])
                  }
                ],
                [
                  "var",
                  {
                    TAG: "Dir",
                    contents: Object.fromEntries([[
                            "log",
                            {
                              TAG: "Dir",
                              contents: Object.fromEntries([[
                                      "access.log",
                                      {
                                        TAG: "File",
                                        content: "[2024-12-06 10:23] User login: admin\n[2024-12-06 10:45] Failed login attempt: user",
                                        locked: false
                                      }
                                    ]])
                            }
                          ]])
                  }
                ]
              ])
        };
}

function resolvePath(terminal, path) {
  if (path === "/") {
    return terminal.filesystem;
  }
  var parts;
  if (path.startsWith("/")) {
    parts = path.slice(1).split("/").filter(function (p) {
          return p !== "";
        });
  } else {
    var currentPath = terminal.currentDirectory.slice(1);
    parts = (currentPath + "/" + path).split("/").filter(function (p) {
          return p !== "";
        });
  }
  var current = {
    contents: terminal.filesystem
  };
  var found = {
    contents: true
  };
  parts.forEach(function (part) {
        if (!(found.contents && part !== "..")) {
          return ;
        }
        var match = current.contents;
        if (match.TAG !== "Dir") {
          found.contents = false;
          return ;
        }
        var node = match.contents[part];
        if (node !== undefined) {
          current.contents = node;
        } else {
          found.contents = false;
        }
      });
  if (found.contents) {
    return current.contents;
  }
  
}

function addOutput(terminal, text) {
  var monoStyle = {
    fontFamily: "monospace",
    fontSize: 11,
    fill: 65280
  };
  var lines = text.split("\n");
  lines.forEach(function (line) {
        var textObj = new PixiJs.Text({
              text: line,
              style: monoStyle
            });
        textObj.x = 10.0;
        textObj.y = 10.0 + terminal.outputLines.length * terminal.lineHeight;
        terminal.container.addChild(textObj);
        terminal.outputLines = terminal.outputLines.concat([textObj]);
      });
  while(terminal.outputLines.length > terminal.maxLines) {
    var oldLine = terminal.outputLines[0];
    if (oldLine !== undefined) {
      Caml_option.valFromOption(oldLine).destroy();
      terminal.outputLines = terminal.outputLines.slice(1);
    }
    
  };
  terminal.outputLines.forEach(function (line, i) {
        line.y = 10.0 + i * terminal.lineHeight;
      });
}

function updateInputLine(terminal) {
  var cursor = terminal.showCursor ? "_" : " ";
  terminal.inputLine.text = terminal.currentPrompt + terminal.currentInput + cursor;
}

function listDirectory(terminal, path, activeIp) {
  var ip = activeIp;
  var fullPath = path.startsWith("C:\\") || path.startsWith("/") ? path : terminal.currentDirectory + "\\" + path;
  var items = DeviceView.listFiles(ip, fullPath);
  if (items === undefined) {
    return "ls: cannot access '" + path + "': No such file or directory";
  }
  if (items.length === 0) {
    return "(empty directory)";
  }
  var formatted = items.map(function (param) {
        var sizeMB = param[3];
        var typeStr = param[1] ? "[DIR] " : "[FILE]";
        var lockStr = param[2] ? " 🔒" : "";
        var sizeStr;
        if (sizeMB >= 1.0) {
          sizeStr = " (" + sizeMB.toFixed(1) + " MB)";
        } else if (sizeMB > 0.0) {
          var kb = sizeMB * 1024.0;
          sizeStr = " (" + kb.toFixed(0) + " KB)";
        } else {
          sizeStr = "";
        }
        return typeStr + " " + param[0] + lockStr + sizeStr;
      });
  return formatted.join("\n");
}

function changeDirectory(terminal, path, activeIp) {
  var ip = activeIp;
  if (path === "..") {
    var parts = terminal.currentDirectory.split("\\").filter(function (p) {
          if (p !== "") {
            return p !== "C:";
          } else {
            return false;
          }
        });
    parts.pop();
    terminal.currentDirectory = parts.length === 0 ? "C:\\" : "C:\\" + parts.join("\\");
    return "";
  }
  var newPath = path.startsWith("C:\\") ? path : terminal.currentDirectory + "\\" + path;
  var match = DeviceView.listFiles(ip, newPath);
  if (match !== undefined) {
    terminal.currentDirectory = newPath;
    return "";
  } else {
    return "cd: " + path + ": No such file or directory";
  }
}

function readFile(terminal, fileName, activeIp) {
  var ip = activeIp;
  var fullPath = fileName.startsWith("C:\\") ? fileName : terminal.currentDirectory + "\\" + fileName;
  var content = DeviceView.readFile(ip, fullPath);
  if (content.TAG !== "Ok") {
    return "cat: " + content._0;
  }
  var content$1 = content._0;
  if (content$1 === "") {
    return "(empty file)";
  } else {
    return content$1;
  }
}

function getActiveState(terminal) {
  var sshStackLen = terminal.sshStack.length;
  if (sshStackLen <= 0) {
    return terminal.deviceState;
  }
  var session = terminal.sshStack[sshStackLen - 1 | 0];
  if (session !== undefined) {
    return session.remoteState;
  } else {
    return terminal.deviceState;
  }
}

function handleBuiltInCommand(terminal, cmd, args) {
  switch (cmd) {
    case "cat" :
        var path = args[0];
        if (path === undefined) {
          return "cat: missing file operand";
        }
        var activeState = getActiveState(terminal);
        if (activeState !== undefined) {
          return readFile(terminal, path, activeState.ipAddress);
        } else {
          return "cat: no device state";
        }
    case "cd" :
        var activeState$1 = getActiveState(terminal);
        if (activeState$1 === undefined) {
          return "cd: no device state";
        }
        var path$1 = Core__Option.getOr(args[0], "/");
        return changeDirectory(terminal, path$1, activeState$1.ipAddress);
    case "clear" :
        terminal.outputLines.forEach(function (line) {
              line.destroy();
            });
        terminal.outputLines = [];
        return "";
    case "cp" :
        var match = args[0];
        var match$1 = args[1];
        if (match === undefined) {
          return "cp: missing file operand";
        }
        if (match$1 === undefined) {
          return "cp: missing destination file operand";
        }
        var activeState$2 = getActiveState(terminal);
        if (activeState$2 === undefined) {
          return "cp: no device state";
        }
        var sourcePath = match.startsWith("C:\\") ? match : terminal.currentDirectory + "\\" + match;
        var destPath = terminal.currentDirectory;
        var msg = DeviceView.copyFile(activeState$2.ipAddress, sourcePath, destPath, match$1);
        if (msg.TAG === "Ok") {
          return "Copied '" + match + "' to '" + match$1 + "'";
        } else {
          return "cp: " + msg._0;
        }
    case "exit" :
        if (terminal.sshStack.length <= 0) {
          return "exit: not in SSH session (use 'shutdown' to power off)";
        }
        var session = terminal.sshStack[terminal.sshStack.length - 1 | 0];
        if (session === undefined) {
          return "";
        }
        SystemLogs.addLog(session.remoteHost, "SSH connection closed from client", "Info");
        terminal.currentDirectory = session.previousDir;
        terminal.sshStack = terminal.sshStack.slice(0, terminal.sshStack.length - 1 | 0);
        var tmp;
        if (terminal.sshStack.length > 0) {
          var prevSession = terminal.sshStack[terminal.sshStack.length - 1 | 0];
          tmp = prevSession !== undefined ? prevSession.remoteState.hostname + "> " : terminal.prompt;
        } else {
          tmp = terminal.prompt;
        }
        terminal.currentPrompt = tmp;
        return "Connection to " + session.remoteHost + " closed.";
    case "help" :
        return "Available commands:\n  ls [path]       - List directory contents\n  cd <path>       - Change directory\n  cat <file>      - Display file contents\n  pwd             - Print working directory\n  mkdir <name>    - Create directory\n  rm <file>       - Remove file\n  cp <src> <dst>  - Copy file\n  kill <pid>      - Kill process by PID\n  ssh <host>      - SSH to remote host\n  ping <host>     - Ping remote host\n  exit            - Exit SSH session\n  clear           - Clear terminal\n  shutdown        - Shutdown this device\n  reboot          - Reboot this device\n  help            - Show this help";
    case "kill" :
        var pidStr = args[0];
        if (pidStr === undefined) {
          return "Usage: kill <pid>";
        }
        var pid = Core__Int.fromString(pidStr, undefined);
        if (pid === undefined) {
          return "kill: invalid PID";
        }
        var activeState$3 = getActiveState(terminal);
        if (activeState$3 === undefined) {
          return "kill: no device state";
        }
        var err = LaptopState.killProcess(activeState$3.processManager, pid, activeState$3.ipAddress);
        if (err.TAG !== "Ok") {
          return "kill: " + err._0;
        }
        SystemLogs.addLog(activeState$3.ipAddress, "Process " + pidStr + " terminated", "Info");
        return "Process " + pidStr + " terminated.";
    case "ls" :
        var activeState$4 = getActiveState(terminal);
        if (activeState$4 === undefined) {
          return "ls: no device state";
        }
        var path$2 = Core__Option.getOr(args[0], terminal.currentDirectory);
        return listDirectory(terminal, path$2, activeState$4.ipAddress);
    case "mkdir" :
        var dirName = args[0];
        if (dirName === undefined) {
          return "mkdir: missing operand";
        }
        var activeState$5 = getActiveState(terminal);
        if (activeState$5 === undefined) {
          return "mkdir: no device state";
        }
        var msg$1 = DeviceView.createDirectory(activeState$5.ipAddress, terminal.currentDirectory, dirName);
        if (msg$1.TAG === "Ok") {
          return "Created directory: " + dirName;
        } else {
          return "mkdir: " + msg$1._0;
        }
    case "ping" :
        var host = args[0];
        if (host === undefined) {
          return "Usage: ping <host>";
        }
        var activeState$6 = getActiveState(terminal);
        if (activeState$6 === undefined) {
          return "ping: terminal not properly initialized";
        }
        LaptopState.addCpuSpike(activeState$6.processManager, 1.0);
        var ni = activeState$6.networkInterface;
        if (ni !== undefined) {
          if (ni.ping(host)) {
            return "Pinging " + host + "...\n\nReply from " + host + ": bytes=32 time=12ms TTL=64\nReply from " + host + ": bytes=32 time=15ms TTL=64\nReply from " + host + ": bytes=32 time=10ms TTL=64\n\nPing statistics for " + host + ":\n    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss)";
          } else {
            return "Pinging " + host + "...\nRequest timed out.\nRequest timed out.\nRequest timed out.\n\nPing statistics for " + host + ":\n    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss)";
          }
        } else {
          return "ping: No network interface available";
        }
    case "pwd" :
        return terminal.currentDirectory;
    case "reboot" :
        var ip = terminal.ipAddress;
        if (ip === undefined) {
          return "reboot: cannot determine device IP";
        }
        var wasShutdown = PowerManager.isDeviceShutdown(ip);
        if (wasShutdown) {
          if (PowerManager.deviceHasPower(ip)) {
            PowerManager.bootDevice(ip);
            return "System is rebooting...";
          } else {
            return "reboot: no power available";
          }
        } else {
          PowerManager.manualShutdownDevice(ip);
          if (PowerManager.deviceHasPower(ip)) {
            PowerManager.bootDevice(ip);
            return "System is rebooting...";
          } else {
            return "reboot: no power available after shutdown";
          }
        }
    case "rm" :
        var hasRecursive = args.some(function (arg) {
              if (arg === "-r" || arg === "-rf") {
                return true;
              } else {
                return arg === "-fr";
              }
            });
        var hasForce = args.some(function (arg) {
              if (arg === "-f" || arg === "-rf") {
                return true;
              } else {
                return arg === "-fr";
              }
            });
        var fileName = args.find(function (arg) {
              return !arg.startsWith("-");
            });
        if (fileName === undefined) {
          return "rm: missing operand";
        }
        var activeState$7 = getActiveState(terminal);
        if (activeState$7 === undefined) {
          return "rm: no device state";
        }
        var msg$2 = DeviceView.deleteFile(activeState$7.ipAddress, terminal.currentDirectory, fileName, hasRecursive);
        if (msg$2.TAG === "Ok") {
          SystemLogs.addLog(activeState$7.ipAddress, "File deleted: " + fileName, "Info");
          return "Removed '" + fileName + "'";
        }
        var msg$3 = msg$2._0;
        if (hasForce && !msg$3.includes("Permission")) {
          return "";
        } else {
          return "rm: " + msg$3;
        }
    case "shutdown" :
        var ip$1 = terminal.ipAddress;
        if (ip$1 !== undefined) {
          PowerManager.manualShutdownDevice(ip$1);
          return "System is shutting down...";
        } else {
          return "shutdown: cannot determine device IP";
        }
    case "ssh" :
        var target = args[0];
        if (target === undefined) {
          return "Usage: ssh <user@host>";
        }
        var activeState$8 = getActiveState(terminal);
        if (activeState$8 === undefined) {
          return "ssh: terminal not properly initialized";
        }
        LaptopState.addCpuSpike(activeState$8.processManager, 2.0);
        var sshParts = target.split("@");
        var host$1 = sshParts.length > 1 ? Core__Option.getOr(sshParts[1], target) : target;
        var ni$1 = activeState$8.networkInterface;
        if (ni$1 === undefined) {
          return "ssh: connect to host " + target + ": Connection refused\n(No network interface available)";
        }
        if (!ni$1.hasSSH(host$1)) {
          if (ni$1.ping(host$1)) {
            return "ssh: connect to host " + host$1 + ": Connection refused\n(SSH service not running on this host)";
          } else {
            return "ssh: connect to host " + host$1 + ": No route to host";
          }
        }
        var remoteState = ni$1.getRemoteState(host$1);
        if (remoteState === undefined) {
          return "ssh: connect to host " + host$1 + ": Connection refused";
        }
        var clientPid = LaptopState.openApp(activeState$8.processManager, "ssh.exe");
        LaptopState.openApp(remoteState.processManager, "sshd.exe");
        DeviceActivity.recordActivity(activeState$8.ipAddress);
        DeviceActivity.recordActivity(host$1);
        SystemLogs.addLog(host$1, "SSH connection from " + activeState$8.ipAddress, "Info");
        var session_previousDir = terminal.currentDirectory;
        var session$1 = {
          remoteState: remoteState,
          remoteHost: host$1,
          previousDir: session_previousDir
        };
        terminal.sshStack = terminal.sshStack.concat([session$1]);
        terminal.currentDirectory = "C:\\";
        terminal.currentPrompt = remoteState.hostname + "> ";
        return "Connecting to " + host$1 + "...\n[Local PID " + clientPid.toString() + "] SSH client started\nSSH connection established to " + remoteState.hostname + ".\nWelcome to " + remoteState.hostname + "\nType 'exit' to disconnect.";
    default:
      return "bash: " + cmd + ": command not found";
  }
}

function executeCommand(terminal) {
  var fullCommand = terminal.currentInput.trim();
  if (fullCommand === "") {
    addOutput(terminal, "");
    terminal.currentInput = "";
    return updateInputLine(terminal);
  }
  addOutput(terminal, terminal.currentDirectory + terminal.prompt + fullCommand);
  var parts = fullCommand.split(" ").filter(function (p) {
        return p !== "";
      });
  var cmd = Core__Option.getOr(parts[0], "");
  var args = parts.slice(1);
  var output = handleBuiltInCommand(terminal, cmd, args);
  if (output !== "") {
    addOutput(terminal, output);
  }
  terminal.commandHistory = terminal.commandHistory.concat([fullCommand]);
  terminal.currentInput = "";
  updateInputLine(terminal);
}

var setGlobalFocusedTerminal = (function(terminal) {
    window.__focusedTerminal = terminal;
  });

var getGlobalFocusedTerminal = (function() {
    return window.__focusedTerminal || undefined;
  });

function handleKeyInput(terminal, key) {
  if (key === "Enter") {
    return executeCommand(terminal);
  } else if (key === "Backspace") {
    terminal.currentInput = terminal.currentInput.slice(0, terminal.currentInput.length - 1 | 0);
    return updateInputLine(terminal);
  } else if (key.length === 1) {
    terminal.currentInput = terminal.currentInput + key;
    return updateInputLine(terminal);
  } else {
    return ;
  }
}

var setupGlobalKeyboardHandler = (function(getFocused, handleKey, unfocusAll) {
    if (!window.__terminalKeyboardSetup) {
      window.__terminalKeyboardSetup = true;
      console.log('[Terminal] Setting up global keyboard handler');

      // Unfocus terminal when clicking on input elements
      document.addEventListener('focusin', (e) => {
        if (e.target && (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA')) {
          console.log('[Terminal] DOM input focused, unfocusing terminal');
          unfocusAll();
        }
      });

      window.addEventListener('keydown', (e) => {
        const focused = getFocused();
        // PixiJS v8 uses 'visible' property, check if container exists and is visible
        const isVisible = focused?.container?.visible !== false;
        if (!focused || !isVisible) return;

        // Check if any DOM input/textarea has focus (PixiUI inputs, HTML inputs, etc.)
        const activeElement = document.activeElement;
        if (activeElement && (activeElement.tagName === 'INPUT' || activeElement.tagName === 'TEXTAREA')) {
          return; // DOM input has focus, don't handle terminal input
        }

        // Check if any PixiUI Input is focused (they set a global flag)
        if (window.__pixiui_input_focused) {
          return; // PixiUI Input has focus, don't handle terminal input
        }

        // Only prevent default for our terminal keys
        if (e.key === 'Enter' || e.key === 'Backspace' || (e.key.length === 1 && !e.ctrlKey && !e.metaKey)) {
          e.preventDefault();
          handleKey(focused, e.key);
        }
      });
    }
  });

var logFocus = (function(msg) { console.log('[Terminal]', msg); });

function focus(terminal) {
  logFocus("Focusing terminal");
  setGlobalFocusedTerminal(terminal);
  terminal.bg.alpha = 1.0;
}

function unfocus(terminal) {
  var focused = getGlobalFocusedTerminal();
  if (focused !== undefined && focused === terminal) {
    setGlobalFocusedTerminal(undefined);
    terminal.bg.alpha = 0.9;
    return ;
  }
  
}

function make(width, height, promptOpt, ipAddress, deviceState, param) {
  var prompt = promptOpt !== undefined ? promptOpt : "> ";
  var container = new PixiJs.Container();
  container.eventMode = "static";
  var bg = new PixiJs.Graphics();
  bg.rect(0.0, 0.0, width, height).fill(0);
  bg.eventMode = "static";
  bg.cursor = "text";
  container.addChild(bg);
  var monoStyle = {
    fontFamily: "monospace",
    fontSize: 11,
    fill: 65280
  };
  var inputLine = new PixiJs.Text({
        text: prompt,
        style: monoStyle
      });
  inputLine.x = 10.0;
  inputLine.y = height - 25.0;
  container.addChild(inputLine);
  var maxLines = (height - 30.0) / 16.0 | 0;
  var terminal = {
    container: container,
    bg: bg,
    outputLines: [],
    commandHistory: [],
    currentDirectory: "C:\\",
    currentInput: "",
    showCursor: true,
    cursorBlink: 0.0,
    inputLine: inputLine,
    prompt: prompt,
    currentPrompt: prompt,
    width: width,
    height: height,
    maxLines: maxLines,
    lineHeight: 16.0,
    filesystem: createFilesystem(),
    ipAddress: ipAddress,
    deviceState: deviceState,
    sshStack: []
  };
  addOutput(terminal, "Terminal initialized. Type 'help' for commands.");
  addOutput(terminal, "");
  bg.on("pointerdown", (function (param) {
          focus(terminal);
        }));
  var unfocusAll = function () {
    setGlobalFocusedTerminal(undefined);
  };
  setupGlobalKeyboardHandler(getGlobalFocusedTerminal, handleKeyInput, unfocusAll);
  return terminal;
}

function update(terminal, deltaTime) {
  terminal.cursorBlink = terminal.cursorBlink + deltaTime;
  if (terminal.cursorBlink > 0.5) {
    terminal.showCursor = !terminal.showCursor;
    terminal.cursorBlink = 0.0;
    return updateInputLine(terminal);
  }
  
}

export {
  createFilesystem ,
  resolvePath ,
  addOutput ,
  updateInputLine ,
  listDirectory ,
  changeDirectory ,
  readFile ,
  getActiveState ,
  handleBuiltInCommand ,
  executeCommand ,
  setGlobalFocusedTerminal ,
  getGlobalFocusedTerminal ,
  handleKeyInput ,
  setupGlobalKeyboardHandler ,
  logFocus ,
  focus ,
  unfocus ,
  make ,
  update ,
}
/* pixi.js Not a pure module */
