// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PixiJs from "pixi.js";
import * as DeviceTypes from "./types/DeviceTypes.res.mjs";
import * as DeviceWindow from "./common/DeviceWindow.res.mjs";
import * as PowerManager from "./PowerManager.res.mjs";

function make(name, ipAddress, securityLevel, connectedStationIp, param) {
  PowerManager.connectUPSToPowerStation(ipAddress, connectedStationIp);
  return {
          name: name,
          ipAddress: ipAddress,
          securityLevel: securityLevel,
          connectedStationIp: connectedStationIp
        };
}

function getInfo(device) {
  return {
          name: device.name,
          deviceType: "UPS",
          ipAddress: device.ipAddress,
          securityLevel: device.securityLevel
        };
}

var $$setInterval = (function(fn, ms) { return setInterval(fn, ms); });

var $$clearInterval = (function(id) { clearInterval(id); });

function createUPSInterface(container, ipAddress) {
  var upsState = PowerManager.getUPSState(ipAddress);
  var headerStyle = {
    fontFamily: "monospace",
    fontSize: 16,
    fill: 7951688,
    fontWeight: "bold"
  };
  var header = new PixiJs.Text({
        text: "UPS CONTROL PANEL",
        style: headerStyle
      });
  header.x = 20.0;
  header.y = 15.0;
  container.addChild(header);
  var statusBg = new PixiJs.Graphics();
  statusBg.rect(20.0, 50.0, 360.0, 100.0).fill({
          color: 1710618
        }).stroke({
        width: 2,
        color: 3355443
      });
  container.addChild(statusBg);
  var powerSource = PowerManager.getDevicePowerSource(ipAddress);
  var sourceColor;
  switch (powerSource) {
    case "MainsPower" :
        sourceColor = 65280;
        break;
    case "UPSBattery" :
        sourceColor = 16755200;
        break;
    case "NoPower" :
        sourceColor = 16711680;
        break;
    
  }
  var sourceText;
  switch (powerSource) {
    case "MainsPower" :
        sourceText = "AC MAINS";
        break;
    case "UPSBattery" :
        sourceText = "BATTERY";
        break;
    case "NoPower" :
        sourceText = "NO POWER";
        break;
    
  }
  var sourceIndicator = new PixiJs.Graphics();
  sourceIndicator.circle(50.0, 85.0, 15.0).fill({
        color: sourceColor
      });
  container.addChild(sourceIndicator);
  var sourceLabel = new PixiJs.Text({
        text: sourceText,
        style: {
          fontSize: 14,
          fill: sourceColor,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  sourceLabel.x = 75.0;
  sourceLabel.y = 75.0;
  container.addChild(sourceLabel);
  var chargingLabel = new PixiJs.Text({
        text: upsState.isCharging ? "⚡ CHARGING" : "🔋 DISCHARGING",
        style: {
          fontSize: 12,
          fill: upsState.isCharging ? 65280 : 16755200,
          fontFamily: "monospace"
        }
      });
  chargingLabel.x = 75.0;
  chargingLabel.y = 100.0;
  container.addChild(chargingLabel);
  var connectedDevices = PowerManager.getUPSConnectedDevices(ipAddress);
  var devicesLabel = new PixiJs.Text({
        text: "Protected Devices: " + connectedDevices.length.toString(),
        style: {
          fontSize: 12,
          fill: 11184810,
          fontFamily: "monospace"
        }
      });
  devicesLabel.x = 75.0;
  devicesLabel.y = 120.0;
  container.addChild(devicesLabel);
  var batteryLabel = new PixiJs.Text({
        text: "BATTERY LEVEL",
        style: {
          fontSize: 12,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  batteryLabel.x = 20.0;
  batteryLabel.y = 165.0;
  container.addChild(batteryLabel);
  var batteryBg = new PixiJs.Graphics();
  batteryBg.rect(20.0, 185.0, 300.0, 30.0).fill({
          color: 2236962
        }).stroke({
        width: 2,
        color: 4473924
      });
  container.addChild(batteryBg);
  var batteryFill = new PixiJs.Graphics();
  var batteryWidth = upsState.batteryLevel / 100.0 * 296.0;
  var batteryColor = upsState.batteryLevel > 50.0 ? 65280 : (
      upsState.batteryLevel > 20.0 ? 16755200 : 16711680
    );
  batteryFill.rect(22.0, 187.0, batteryWidth, 26.0).fill({
        color: batteryColor
      });
  container.addChild(batteryFill);
  var batteryPercent = new PixiJs.Text({
        text: upsState.batteryLevel.toFixed(1) + "%",
        style: {
          fontSize: 14,
          fill: 16777215,
          fontFamily: "monospace",
          fontWeight: "bold"
        }
      });
  batteryPercent.x = 330.0;
  batteryPercent.y = 190.0;
  container.addChild(batteryPercent);
  var listLabel = new PixiJs.Text({
        text: "PROTECTED DEVICES:",
        style: {
          fontSize: 11,
          fill: 8947848,
          fontFamily: "monospace"
        }
      });
  listLabel.x = 20.0;
  listLabel.y = 230.0;
  container.addChild(listLabel);
  var listBg = new PixiJs.Graphics();
  listBg.rect(20.0, 250.0, 360.0, 80.0).fill({
          color: 657930
        }).stroke({
        width: 1,
        color: 3355443
      });
  container.addChild(listBg);
  connectedDevices.forEach(function (deviceIp, i) {
        if (i >= 4) {
          return ;
        }
        var deviceText = new PixiJs.Text({
              text: "• " + deviceIp,
              style: {
                fontSize: 11,
                fill: 65280,
                fontFamily: "monospace"
              }
            });
        deviceText.x = 30.0;
        deviceText.y = 255.0 + i * 18.0;
        container.addChild(deviceText);
      });
  if (connectedDevices.length === 0) {
    var noDevicesText = new PixiJs.Text({
          text: "No devices connected",
          style: {
            fontSize: 11,
            fill: 6710886,
            fontFamily: "monospace",
            fontStyle: "italic"
          }
        });
    noDevicesText.x = 30.0;
    noDevicesText.y = 280.0;
    container.addChild(noDevicesText);
  }
  var runtimeMinutes;
  if (upsState.isCharging) {
    runtimeMinutes = 999;
  } else {
    var deviceCount = connectedDevices.length;
    runtimeMinutes = deviceCount > 0 ? upsState.batteryLevel / (deviceCount * (1.0 / 30.0) * 60.0) | 0 : 999;
  }
  var runtimeText = runtimeMinutes >= 999 ? "Runtime: ∞" : "Runtime: ~" + runtimeMinutes.toString() + " min";
  var runtimeLabel = new PixiJs.Text({
        text: runtimeText,
        style: {
          fontSize: 12,
          fill: 11184810,
          fontFamily: "monospace"
        }
      });
  runtimeLabel.x = 20.0;
  runtimeLabel.y = 345.0;
  container.addChild(runtimeLabel);
  return $$setInterval((function () {
                var currentState = PowerManager.getUPSState(ipAddress);
                var currentSource = PowerManager.getDevicePowerSource(ipAddress);
                var newSourceColor;
                switch (currentSource) {
                  case "MainsPower" :
                      newSourceColor = 65280;
                      break;
                  case "UPSBattery" :
                      newSourceColor = 16755200;
                      break;
                  case "NoPower" :
                      newSourceColor = 16711680;
                      break;
                  
                }
                var newSourceText;
                switch (currentSource) {
                  case "MainsPower" :
                      newSourceText = "AC MAINS";
                      break;
                  case "UPSBattery" :
                      newSourceText = "BATTERY";
                      break;
                  case "NoPower" :
                      newSourceText = "NO POWER";
                      break;
                  
                }
                sourceIndicator.clear();
                sourceIndicator.circle(50.0, 85.0, 15.0).fill({
                      color: newSourceColor
                    });
                sourceLabel.text = newSourceText;
                chargingLabel.text = currentState.isCharging ? "⚡ CHARGING" : "🔋 DISCHARGING";
                var newBatteryWidth = currentState.batteryLevel / 100.0 * 296.0;
                var newBatteryColor = currentState.batteryLevel > 50.0 ? 65280 : (
                    currentState.batteryLevel > 20.0 ? 16755200 : 16711680
                  );
                batteryFill.clear();
                batteryFill.rect(22.0, 187.0, newBatteryWidth, 26.0).fill({
                      color: newBatteryColor
                    });
                batteryPercent.text = currentState.batteryLevel.toFixed(1) + "%";
              }), 500);
}

function openGUI(device) {
  var win = DeviceWindow.make("UPS - " + device.name + " [" + device.ipAddress + "]", 400.0, 400.0, DeviceTypes.getDeviceColor("UPS"), 657930, undefined);
  var intervalId = createUPSInterface(DeviceWindow.getContent(win), device.ipAddress);
  DeviceWindow.setOnClose(win, (function () {
          $$clearInterval(intervalId);
        }));
  return win;
}

function toDevice(t) {
  return {
          getInfo: (function () {
              return getInfo(t);
            }),
          openGUI: (function () {
              return openGUI(t);
            })
        };
}

export {
  make ,
  getInfo ,
  $$setInterval ,
  $$clearInterval ,
  createUPSInterface ,
  openGUI ,
  toDevice ,
}
/* pixi.js Not a pure module */
