// Generated by ReScript, PLEASE EDIT WITH CARE


function resize(w, h, minWidth, minHeight, letterbox) {
  var aspectRatio = minWidth / minHeight;
  var canvasWidth = w;
  var canvasHeight = h;
  if (letterbox) {
    if (minWidth < minHeight) {
      canvasHeight = window.innerHeight;
      canvasWidth = Math.min(Math.min(window.innerWidth, minWidth), canvasHeight * aspectRatio);
    } else {
      canvasWidth = window.innerWidth;
      canvasHeight = Math.min(Math.min(window.innerHeight, minHeight), canvasWidth / aspectRatio);
    }
  }
  var scaleX = canvasWidth < minWidth ? minWidth / canvasWidth : 1.0;
  var scaleY = canvasHeight < minHeight ? minHeight / canvasHeight : 1.0;
  var scale = scaleX > scaleY ? scaleX : scaleY;
  return {
          width: Math.floor(canvasWidth * scale),
          height: Math.floor(canvasHeight * scale)
        };
}

export {
  resize ,
}
/* No side effect */
